### ISSUE TITLE
Rugged::NetworkError: unsupported URL protocol

### ISSUE THREAD

**Issue by sebbbastien** [ytti/oxidized#1038]
Hi,

I'm running oxidized 0.20.0 on Debian 9.

This config file : 

```
---
interval: 3600
use_syslog: false
debug: false
threads: 30
timeout: 20
retries: 3
prompt: !ruby/regexp /^([\w.@-]+[#>]\s?)$/
rest: 127.0.0.1:8888
next_adds_job: false
vars: {}
groups:
  secu:
    username: bar
    password: **********
models: {}
pid: "/home/oxidized/.config/oxidized/pid"
input:
  default: ssh
  debug: false
  ssh:
    secure: false

output:
  default: git
  debug: true
  git:
    user: oxidized
    email: oxidized@foo.lab
    repo: "/home/oxidized/backups/default.git"

source:
  default: http
  http:
    scheme: http
    url: "http://git.foo.lab/backups/raw/master/router.db"
    map:
      name: hostname
      model: os
      group: group

hooks:
  push_to_remote:
    type: githubrepo
    events: [post_store]
    remote_repo:
      secu: git@git.foo.lab:backup/secu.git
    publickey: "/home/oxidized/.ssh/id_rsa"
    privatekey: "/home/oxidized/.ssh/id_rsa.pub"
```

This configuration file produces this error:

> `Rugged::NetworkError: unsupported URL protocol`

```
oxidized@host ~/backups> rm -rf secu.git/ ; oxidized 
I, [2017-09-21T20:02:31.628695 #26397]  INFO -- : Oxidized starting, running as pid 26397
I, [2017-09-21T20:02:31.682919 #26397]  INFO -- : lib/oxidized/nodes.rb: Loading nodes
I, [2017-09-21T20:02:31.886215 #26397]  INFO -- : lib/oxidized/nodes.rb: Loaded 3 nodes
Puma starting in single mode...
* Version 3.10.0 (ruby 2.3.3-p222), codename: Russell's Teapot
* Min threads: 0, max threads: 16
* Environment: development
* Listening on tcp://127.0.0.1:8888
Use Ctrl-C to stop
I, [2017-09-21T20:02:37.293355 #26397]  INFO -- : Configuration updated for secu/fw1
I, [2017-09-21T20:02:37.293780 #26397]  INFO -- : GithubRepo: Pushing local repository(/home/oxidized/backups/secu.git/)...
I, [2017-09-21T20:02:37.294541 #26397]  INFO -- : GithubRepo: to remote: git@git.foo.lab:backup/secu.git
E, [2017-09-21T20:02:37.294947 #26397] ERROR -- : Hook push_to_remote (#<GithubRepo:0x00560c9517d8b8>) failed (#<Rugged::NetworkError: unsupported URL protocol>) for event :post_store
I, [2017-09-21T20:02:41.298500 #26397]  INFO -- : Configuration updated for secu/fw2
I, [2017-09-21T20:02:41.298928 #26397]  INFO -- : GithubRepo: Pushing local repository(/home/oxidized/backups/secu.git/)...
I, [2017-09-21T20:02:41.299186 #26397]  INFO -- : GithubRepo: to remote: git@git.foo.lab:backup/secu.git
E, [2017-09-21T20:02:41.299534 #26397] ERROR -- : Hook push_to_remote (#<GithubRepo:0x00560c9517d8b8>) failed (#<Rugged::NetworkError: unsupported URL protocol>) for event :post_store
```

If I change the push_to_remote configuration: 

```
hooks:
  push_to_remote:
    type: githubrepo
    events: [post_store]
    remote_repo:
      secu: git@git.foo.lab:/backup/secu.git
    publickey: "/home/oxidized/.ssh/id_rsa"
    privatekey: "/home/oxidized/.ssh/id_rsa.pub"
```

With:
```
hooks:
  push_to_remote:
    type: githubrepo
    events: [post_store]
    remote_repo:
      secu: http://git.foo.lab/backup/secu.git
    username: bar
    password: ********
```

Everything is working fine.

No help needed on my side, let me know if other tests can help you to investigate.

Best regards,
(Thank you for you great tool!)
