### ISSUE TITLE
LibreNMS+Oxidized

### ISSUE THREAD

**Issue by AMMNTT** [ytti/oxidized#1072]
Hello i got a problem with setting up versioning in librenms. 
it worked once with the files. 
i don't know much about the git.
Oxidized crashed : 

[root@librenms ~]# oxidized
I, [2017-10-19T19:08:52.410786 #6024]  INFO -- : Oxidized starting, running as pid 6024
F, [2017-10-19T19:08:52.410981 #6024] FATAL -- : Oxidized crashed, crashfile written in /root/.config/oxidized/crash
undefined method `default' for nil:NilClass
/usr/local/share/gems/gems/oxidized-0.20.0/lib/oxidized/nodes.rb:12:in `block in load': undefined method `default' for nil:NilClass (NoMethodError)
        from /usr/local/share/gems/gems/oxidized-0.20.0/lib/oxidized/nodes.rb:127:in `synchronize'
        from /usr/local/share/gems/gems/oxidized-0.20.0/lib/oxidized/nodes.rb:127:in `with_lock'
        from /usr/local/share/gems/gems/oxidized-0.20.0/lib/oxidized/nodes.rb:10:in `load'
        from /usr/local/share/gems/gems/oxidized-0.20.0/lib/oxidized/nodes.rb:122:in `initialize'
        from /usr/local/share/gems/gems/oxidized-0.20.0/lib/oxidized/core.rb:14:in `new'
        from /usr/local/share/gems/gems/oxidized-0.20.0/lib/oxidized/core.rb:14:in `initialize'
        from /usr/local/share/gems/gems/oxidized-0.20.0/lib/oxidized/core.rb:4:in `new'
        from /usr/local/share/gems/gems/oxidized-0.20.0/lib/oxidized/core.rb:4:in `new'
        from /usr/local/share/gems/gems/oxidized-0.20.0/lib/oxidized/cli.rb:12:in `run'
        from /usr/local/share/gems/gems/oxidized-0.20.0/bin/oxidized:9:in `<top (required)>'
        from /usr/local/bin/oxidized:23:in `load'
        from /usr/local/bin/oxidized:23:in `<main>'

Config:
```yaml
username: username
password: password
model: junos
interval: 3600
use_syslog: false
debug: false
threads: 30
timeout: 20
retries: 3
prompt: !ruby/regexp /([\w.@-]+[#>]\s?)$/
rest: 127.0.0.1:8888
next_adds_job: false
vars: {}
groups: {}
models: {}
pid: /root/.config/oxidized/pid
input:
default: ssh, telnet
debug: true
output:
 default: git
 file:
 directory: /root/.config/oxidized/configs
output:
 default: git
 git:
 user: Oxidized
 email: o@example.com
 repo: "/var/lib/oxidized/devices.git"
source:
default: http
debug: true
http:
url: http://127.0.0.1/api/v0/oxidized
scheme: http
delimiter: !ruby/regexp /:/
map:
name: hostname
model: os
headers:
X-Auth-Token: 'c02b15656b7883fb09bf1081999c64ef'
```

**Comment by laf** [comment]
You have two outputs which isn't currently supported afaik.

Can you paste a formatted version of your config please?

**Comment by AMMNTT** [comment]
Sorry laf , i don't know how to do it .
i'm totally new to github i don't know how to use it well.
this is the config file .

[config.zip](https://github.com/ytti/oxidized/files/1403434/config.zip)

**Comment by okand** [comment]
The initial post and the zip are formatted the same.

Anyway, I think you need to remove the first `output:` section and indent `user:`,`email:` and `repo:` in the second one. It is probably necessary to do some work to the `source:` section too. Indentation is important with YAML, it's the way it knows which options relate to each other. I use two spaces for each step but you can use any amount as long as it's consistent.

Here's my config that uses a router.db file and git as an example.

```
---
rest: 127.0.0.1:8888
interval: 3600

source:
  default: csv
  csv:
    file: /home/oxidized/.config/oxidized/router.db
    delimiter: !ruby/regexp /:/
    map:
      group: 0
      name: 1
      model: 2
      username: 3
      password: 4
output:
  default: git
  git:
      user: oxidized
      single_repo: true
      email: removed_so_I_can_post_online
      repo: "~/.config/oxidized/oxidized.git"
hooks:
  push_to_remote:
    type: githubrepo
    events: [post_store]
    remote_repo: https://intranet-gitlab-server.tld/oxidized.git
    username: oxidized
    password: removed_so_I_can_post_online
```
