### ISSUE TITLE
Inappropriate ioctl for device error

### ISSUE THREAD

**Issue by Noname2244** [ytti/oxidized#1130]
Connecting to devices works fine as long as username and passwords are the  global/default specified in the beginning of the conf file.

If I use coloums for username and password  4 and 5, it seems that oxid isnt using the data

ie:
devicename:12.12.12.13:group1:devicetype:username2:password2
 doesnt work

but if I add the username and password to the config file it works with
devicename:12.12.12.13:group1:devicetype

om the same propmt I can manually login to the units with the username and password.

are there too many map coloumns? is 4 and 5 to much ?

```yaml
---
username: username
password: password
model: ios
interval: 3600
use_syslog: true
debug: true
threads: 30
timeout: 20
retries: 3
prompt: !ruby/regexp /^([\w.@-]+[#>]\s?)$/
rest: 0.0.0.0:8888
next_adds_job: false
vars: {}
groups: {}
models: {}
pid: "/home/oxidized/.config/oxidized/pid"
input:
  default: ssh
  debug: true
  ssh:
    secure: false
output:
  default: git
  git:
    user: oxidized
    email: mail@mail.com
    repo: "/home/oxidized/oxidized/git"
source:
  default: csv
  csv:
    file: "/home/oxidized/.config/oxidized/router.db"
    delimiter: !ruby/regexp /:/
    map:
      name: 0
      ip: 1
      group: 2
      model: 3
      username: 4
      password: 5
    gpg: false
model_map:
  cisco: ios
  juniper: junos
```
