### ISSUE TITLE
Encrypting Email Hook

### ISSUE THREAD

**Issue by olaHalo** [ytti/oxidized#1133]
We are using the latest email hook (oxidized-report-git-commits) and if we set it to send plain text emails it works fine. However we want to encrypt these emails and when we do a blank email is sent.
If we run the same exact command in bash it sends the email encrypted as expected.

Config
```yaml
---
username: svc_oxi
password: 
model: junos
interval: 5400
use_syslog: false
debug: false
threads: 30
timeout: 180
retries: 5
prompt: !ruby/regexp /^([\w.@-]+[#>]\s?)$/
rest: 0.0.0.0:8888/securitydevices/
vars: {
  remove_secret: true
      }
groups: {}
input:
  default: ssh, telnet
  debug: /tmp/logs/oxidized_log_input
  ssh:
    secure: false
output:
  default: git
  git:
    user: Oxidized
    email: email@me.com
    repo: "/opt/oxidized/deviceconfigs/devices.git"
log: /var/log/oxidized.log
source:
  default: csv
  csv:
    file: /etc/oxidized/firewall.db
    delimiter: !ruby/regexp /:/
    map:
      name: 0
      model: 1
      username: 2
      password: 3
      group: 4
    vars_map:
      enable: 4
model_map:
  cisco: ios
  juniper: junos
  checkpoint: gaiaos
  bigip: tmos
hooks:
  email_for_failed_nodes:
    type: exec
    events: [node_fail]
    cmd: '/etc/oxidized/extra/oxidized-report-git-commits-new | gpg --batch  -ae -r "XXXXXXX" -r "XXXXXXX" | mail -s "Security Oxidized Failed to contact ${OX_NODE_NAME}" emails@here.etc, emails@here.com'
    async: true
    timeout: 120
  email_successful_changes:
    type: exec
    events: [post_store]
    cmd: '/etc/oxidized/extra/oxidized-report-git-commits-new |  gpg --batch  -ae -r "XXXXXXX" -r "XXXXXXX" | mail -r email.com -s "Security Oxidized Detected New Changes for ${OX_NODE_NAME}" emails@here, email@here.etc'
    async: true
    timeout: 120
```
The post_store event is the one I am concerned about. 

Again if I run this command in bash it seems to work as expected and encrypts the email.
bash$ ./etc/oxidized/extra/oxidized-report-git-commits-new | gpg --batch  -ae -r "XXXXXXX" -r "XXXXXXX" | mail -r email.com -s "Security Oxidized Detected New Changes for ${OX_NODE_NAME}" emails@here, email@here.etc

Not sure what I am missing. It is most likely something on my end but since the command runs properly outside of Oxidized I thought I'd ask here. The weirdest thing is this worked fine when we were using the older version of the oxidized-report-git-commit file. 

Thanks
