### ISSUE TITLE
Slackdiff hook throws error when there is no diff

### ISSUE THREAD

**Issue by yzguy** [ytti/oxidized#1150]
Hello,

I started oxidized for the first time, using CSV source, and git output. I configured the slack hook, and I received the below error.

```
[2018-01-16T22:08:02.817068 #15] ERROR -- : Hook slack (#<SlackDiff:0x000055c35b519c98>) failed (#<TypeError: no implicit conversion of Symbol into Integer>) for event :post_store
```

I investigated a little bit and it seems when [this line](https://github.com/ytti/oxidized/blob/master/lib/oxidized/hook/slackdiff.rb#L36) runs, it throws a TypeError seen above

I used `diff.inspect` to see what was up and it showed just `no diffs` instead of a hash. This makes sense as the configuration hasn't changed from what was on the remote, however I did not even have `diff` turned on for the Slack hook.

Looks like there needs to be a check to only post when there is a diff.

**Comment by yzguy** [comment]
Also curious about `diff[:patch].lines.to_a[4..-1].join`

If the diff was less than 4 lines, then it would return `nil`

```
-> irb
irb(main):001:0> a =["a", "b"]
=> ["a", "b"]
irb(main):002:0> a[4..-1]
=> nil
irb(main):003:0> a[4..-1].join
NoMethodError: undefined method `join' for nil:NilClass
irb(main):004:0> a = ["a", "b", "c", "d", "e", "f"]
=> ["a", "b", "c", "d", "e", "f"]
irb(main):005:0> a[4..-1]
=> ["e", "f"]
```

**Comment by laf** [comment]
What's your config for the slack hook?

**Comment by yzguy** [comment]
Here is the config:

```
hooks:
  push_to_remote:
    type: githubrepo
    events: [post_store]
    remote_repo: git@git.example.com:yzguy/network-configs.git
    publickey: "~/.config/oxidized/.ssh/id_rsa.pub"
    privatekey: "~/.config/oxidized/.ssh/id_rsa"
```

Nothing crazy.
