### ISSUE TITLE
Slackdiff sending code snippets when diff: false

### ISSUE THREAD

**Issue by GitStoph** [ytti/oxidized#1154]
[https://github.com/ytti/oxidized/commit/aa0e1808f25e5e8b1a76f34c29f2eeb7db75a7c7](url) 
I was reading through this, and thought that'd be great for my environment. We'd like to leave `remove_secret` set to false to have true configs of our equipment. However, when I went to employ/test the configuration, it was not working. My slack hook config:
```
hooks:
  slack:
    type: slackdiff
    diff: false
    events: [post_store]
    token: xoxb-############################
    channel: "#network-changes"
```
![image](https://user-images.githubusercontent.com/20820226/35065519-15533a1c-fb93-11e7-9cfa-7f7ebdbd2696.png)
Any help would be very appreciated!

I dont suppose there's a way to have `remove_secret` only be applied to what's sent to Slack? I'd love to keep the code snippet in the message, however we dont want passwords or SNMP communities going through external resources of course. 

Thanks!
