### ISSUE TITLE
git - put configs into a subfolder

### ISSUE THREAD

**Issue by hmhackmaster** [ytti/oxidized#1170]
Before I go down a rabbit hole of things I don't fully comprehend, I figured I would post here:

I am looking to back up switch configs to a subfolder of a project on a hosted git server. I have gotten everything to work great except my desire to put the configs in a subfolder.

It seems like Oxidized drops the configs into the top level directory in the git repo:
`Test-Oxidized.git/HPSwitch01`
What I would like to do is to put the config files into a subfolder of this git repo:
`Test-Oxidized.git/Switches/HPSwitch01`

I assume this isn't going to be natively supported, so I was trying to dig through to see where I can prepend the folder name (it will always be "Switches" but I haven't been able to locate that yet.
I am assuming it's somewhere in https://github.com/ytti/oxidized/blob/master/lib/oxidized/output/git.rb

Any thoughts or direction are appreciated!

**Comment by laf** [comment]
You need to use groups and then the configs will be put in those folders. Works fine, it's what we do here.

**Comment by hmhackmaster** [comment]
I read up on [#396](https://github.com/ytti/oxidized/issues/396) ahead of posting this, but it didn't seem to come to a conclusion.

Mind sharing an example of your config?

This is an excerpt of what I am currently using:

config:
```
vars: {}
groups: 
  Test1:
    username: Test1Username
    password: Test1Password
  Test2:
     username: Test2Username
     password: Test2Password
models: {}
pid: "/home/oxidized/.config/oxidized/pid"
input:
  default: ssh
  debug: false
  ssh:
    secure: false
output:
  default: git
  git:
    user: oxidized
    email: oxidized@domain.com
    repo: "/home/oxidized/oxidized-git/git-repos/default.git"
source:
  default: csv
  csv:
    file: "/home/oxidized/.config/oxidized/router.db"
    delimiter: !ruby/regexp /:/
    map:
      name: 0
      ip: 1
      model: 2
      group: 3
    gpg: false
```

router.db:
```
Test1Switch1:172.1.1.1:hpswitch:Test1
Test2Switch1:172.1.2.1:hpswitch:Test2
Test2Switch2:172.1.2.2:hpswitch:Test2
```

**Comment by laf** [comment]
Try single repo:

```
output:
  default: git
  git:
    single_repo: true

```

**Comment by hmhackmaster** [comment]
I'll try this, but I do expect that I will want to have a couple repos (I know this is getting crazy, but I have a couple seperate networks that I want to backup to separate git repos all viewable from the same console), with the switch configs being in a specific `switch/` subfolder inside each repo..

`Test-Oxidized.git/switch/Test1Switch1.config`
`Test2.git/switch/Test2Switch1.config`
`Test2.git/switch/Test2Switch2.config`

**Comment by laf** [comment]
I'm not sure that's possible.

**Comment by hmhackmaster** [comment]
I figured it would not possible without code modifications. I figured I would prepend the `/switches` bit to the git add part.

I think I am on to something on line 144: https://github.com/ytti/oxidized/blob/master/lib/oxidized/output/git.rb#L144

I'll report back with how horrifically I am able to ~~break~~ modify it.

**Comment by hmhackmaster** [comment]
So it ended up being far easier than I expected.

I was able to add the following to [git.rb#L188](https://github.com/ytti/oxidized/blob/8dbd596ed73ff9d9cbe68093372fee799b6fd482/lib/oxidized/output/git.rb#L188)
```
    if @cfg.subdirectories?
        index.add :path=> @opt[:subdirectory] + '/' + file, :oid=>oid, :mode=>0100644
      else
        index.add :path=> file, :oid=>oid, :mode=>0100644
    end
```

With the following additions to `config`
```
output:
  default: git
  git:
    user: oxidized
    subdirectories: true
    email: oxidized@jagaursit.com
    repo: "/home/oxidized/oxidized-git/git-repos/default.git"
source:
  default: csv
  csv:
    file: "/home/oxidized/.config/oxidized/router.db"
    delimiter: !ruby/regexp /:/
    map:
      name: 0
      ip: 1
      model: 2
      group: 3
      subdirectory: 4
```

My only issue now is the `@opt[:subdirectory]` variable thing is undefined as it's evidently not being passed along or something. I'll keep working on this and prepare a pr if it works well (and makes sense for the merging..)
