### ISSUE TITLE
Cannot push non-fastfowardable reference

### ISSUE THREAD

**Issue by fitzplb** [ytti/oxidized#1281]
I'm getting the following error when trying to push to Git:
```
I, [2018-04-13T15:31:32.513262 #26]  INFO -- : Configuration updated for /10.111.104.5
I, [2018-04-13T15:31:32.528987 #26]  INFO -- : GithubRepo: Pushing local repository(/root/.config/oxidized/oxidized.git/)...
I, [2018-04-13T15:31:32.529952 #26]  INFO -- : GithubRepo: to remote: git@github.mydomain.com:ORG/network_config_DEVELOPMENT.git
E, [2018-04-13T15:31:33.297138 #26] ERROR -- : Hook push_to_remote (#<GithubRepo:0x000000000252df08>) failed (#<Rugged::ReferenceError: cannot push non-fastforwardable reference>) for event :post_store
```
These are (I think) the relevant sections of my config file:
```
output:
  default: git
  git:
    user: oxidized
    email: oxidized@mydomain.com
    repo: "/root/.config/oxidized/oxidized.git"
.
.
.
hooks:
  push_to_remote:
    type: githubrepo
    events: [post_store]
    remote_repo: git@github.mydomain.com:ORG/network_config_DEVELOPMENT.git
    publickey: /root/.ssh/id_rsa.pub
    privatekey: /root/.ssh/id_rsa
```
I'm pretty sure this used to work as the github.mydomain.com:ORG/network_config_DEVELOPMENT.git repo does contain config backups from a couple of months ago but I'm picking up where a former colleague left off so I'm not sure at what point it stopped working.
