### ISSUE TITLE
resolve_dns: false not working?

### ISSUE THREAD

**Issue by KlaasT** [ytti/oxidized#1395]
I'm trying to fetch devices using a SSH Proxy however I cannot resolve the hostnames on the source server as the domain is not resolvable there.

So I configured the following:

```
resolve_dns: false
groups:
  groupname:
    username: YYY
    password: XXX
    vars:
      enable: ZZZ
      ssh_proxy: 192.0.2.1
```

However when I start oxidized it still tells me that the hostnames in this group cannot be resolved. I'm using oxidized 0.23.0

Thanks for your help.
