### ISSUE TITLE
How to send mail to different people according to deivce group

### ISSUE THREAD

**Issue by WWY507** [ytti/oxidized#1410]
hey,guys.
How to Send mail to different people according to the deivce group
for example,
Group1 device send mail to user1,
Group2 device send mail to user2

thx

**Comment by dalamanster** [comment]
Hey,

I suppose, you want to send email, when some 'diff' in configuration occurs.  
I was struggling with the same issue. And resolved it successfully as follows.

Explained in small steps:

1. Create simple bash script, which will return recipients name according to group name. There is only one argument expected, which is GROUP name:
```
#!/bin/bash
[ "$#" -eq 1 ] || exit 1

case "$1" in

 group1 ) echo "user1@example.com";;
 group2 ) echo "user2@example.com";;
 group3 ) echo "user1@example.com,user2@example.com,user3@example.com";;
 *) echo "user1@example.com";;
esac
exit 0
```

2. Create hook which is executed after  events post_store, node_fail and run following commands 
3. Create temporary file which contains template for a email with fields From, To, Subject and Encoding types:
```'echo -e "From: ConfigDiff<oxidized@example.com>\nTo: `/home/oxidized/oxidized-mail-list.sh ${OX_NODE_GROUP}`\nSubject: Config diff for ${OX_NODE_NAME}\nMIME-Version: 1.0\nContent-Type: text/html; charset=utf-8\n\n" > /tmp/${OX_NODE_NAME}; ```

4. Take the diff of configuration + colorize it for more readable output + convert to html --> append to tmp file
`oxidized/.config/oxidized/extra/oxidized-report-git-commits | colordiff | ansi2html `

5. Send mail from mail template in tmp file and remove tmp file
`msmtp < /tmp/${OX_NODE_NAME}; rm /tmp/${OX_NODE_NAME}`


This is final hook in oxidized config file. 
```
hooks:
....
email_output:
    type: exec
    events: [post_store, node_fail]
    cmd: 'echo -e "From: ConfigDiff<oxidized@example.com>\nTo: '/home/oxidized/oxidized-mail-list.sh ${OX_NODE_GROUP}`\nSubject: Config diff for ${OX_NODE_NAME}\nMIME-Version: 1.0\nContent-Type: text/html; charset=utf-8\n\n" > /tmp/${OX_NODE_NAME}; /home/oxidized/.config/oxidized/extra/oxidized-report-git-commits | tr -d \\r | colordiff | ansi2html >> /tmp/${OX_NODE_NAME}; msmtp < /tmp/${OX_NODE_NAME}; rm /tmp/${OX_NODE_NAME}'
    async: true
    timeout: 40
```
