### ISSUE TITLE
Group auth and ssh proxy

### ISSUE THREAD

**Issue by systeembeheerder** [ytti/oxidized#1516]
Somehow groups auth together with ssh proxy doesn't seem to work for me. Does anyone use this combination? Devices are accessed with a blank username.

relevant config:
```
---
groups:
  client1:
    username: admin
    password: verysecret
  client2:
    username: manager
    password: easyshouldbechanged
source:
  default: csv
  csv:
    file: /var/lib/oxidized/.config/oxidized/devices.db
    delimiter: !ruby/regexp /:/
    map:
      group: 0
      name: 1
      ip: 2
      model: 3
      username: 4
      password: 5
    vars_map:
      enable: 6
      ssh_proxy: 7
```

file devices.db
```
### Client1
#group:name:ip:model:username:password:var_maps
client1:fw01.mgmt.mycorp.net::junos
client1:swt01:172.29.0.2:procurve::::fw01.mgmt.mycorp.net
client1:swt02:172.29.0.12:procurve::::fw01.mgmt.mycorp.net
client1:swt04:172.29.0.18:procurve::::fw01.mgmt.mycorp.net
```

Any thoughs?
