### ISSUE TITLE
Oxidized uses "username" if no username is defined in config? (Telnet)

### ISSUE THREAD

**Issue by Atroskelis** [ytti/oxidized#1549]
Cisco with no username, only password -> enable password 

```
groups:
  cisco-ios:
    password: password1
    vars:
      enable: password2
```

Gives a 

```
Sep 24 11:30:27 librenms oxidized[3003]: 192.168.20.254 raised Oxidized::PromptUndetect with msg "unable to detect prompt: (?-mix:^([\w.@()-]+[#>]\s?)$)"
Sep 24 11:30:32 librenms oxidized[3003]: 192.168.20.254 raised Net::SSH::AuthenticationFailed with msg "Authentication failed for user username@192.168.20.254"
```

The group is matched, tested it with a random user. 

Setting an empty user crashes the node.
