### ISSUE TITLE
Cisco configs folder is empty after running oxidized command

### ISSUE THREAD

**Issue by wit12345** [ytti/oxidized#1562]

**Comment by activekerrar** [comment]
Unsure if required, but try adding a "default" option for "file":
```
output:
  default: file
  file:
    directory: /home/oxidized/.config/oxidized/configs
```

Also, what is a result of an "ls -al" on /home/oxidized/.config/oxidized/configs ?
