### ISSUE TITLE
Git with Oxidized  doesn't work

### ISSUE THREAD

**Issue by wit12345** [ytti/oxidized#1613]
Hello,

I have installed Oxidized and I'm trying to use Git. 

I've done the following steps:
  
   1.Install Git and dependencies
```
yum install git
gem install rugged
```
  2. Oxidized User Configuration
```
git config --global user.name "oxidized"
 git config --global user.email "oxidized@domain.com"
```

  3. Create ssh keys for the oxidized user
```sudo -H -u oxidized bash -c 'cat /dev/zero | ssh-keygen -q -N ""'```

  4. Add my ssh public key to the oxidized user account in gitlab.

  5. Change the Oxidized Config File:
```
output:
  default: git
  git:
    single_repo: true
    user: oxidized
    email: oxidized@domain.com
    repo: /home/oxidized/output/configs.git
hooks:
  push_to_remote:
     type: githubrepo
     events: [post_store]
     remote_repo: "git@git.domain.com:cisco/configs.git"
     publickey: /home/oxidized/.ssh/id_rsa.pub
     privatekey: /home/oxidized/.ssh/id_rsa
```

Now when I run the Oxidized I haven't any errors  in my log files, but my gitlab repo are empty.

My log file:
```
I, [2018-10-31T11:13:58.460810 #23964]  INFO -- : GithubRepo: Pushing local repository(/home/oxidized/output/configs.git/)...
I, [2018-10-31T11:13:58.461335 #23964]  INFO -- : GithubRepo: to remote: git@domain.com:wit-itteam/configs.git
D, [2018-10-31T11:13:58.560483 #23964] DEBUG -- : GithubRepo: Authenticating using ssh keys as 'git'
D, [2018-10-31T11:13:59.343673 #23964] DEBUG -- : GithubRepo: Authenticating using ssh keys as 'git'
D, [2018-10-31T11:17:31.906875 #24065] DEBUG -- : node.rb: resolving node key 'output', with passed global value of 'git' and node value ''
D, [2018-10-31T11:17:31.906988 #24065] DEBUG -- : node.rb: returning node key 'output' with value 'git'
D, [2018-10-31T11:17:31.926327 #24065] DEBUG -- : node.rb: resolving node key 'output', with passed global value of 'git' and node value ''
```
I don't understand what I'm missing. Any ideas?

Thank you
