### ISSUE TITLE
github-repo hook fails with nodes_done

### ISSUE THREAD

**Issue by mr-deamon** [ytti/oxidized#1631]
Possible duplicate of #636, but there was no solution.

I use oxidized with groups and push them to a github-repo.
If i use node_success, everything works as expected! If i switch to nodes_done, it fails with the following error:
`ERROR -- : Hook push_to_remote (#<GithubRepo:0x00000001974fb8>) failed (#<NoMethodError: undefined method repo' for nil:NilClass>) for event :nodes_done`
(even with debug switched on there is not more output. oxidized does not crash on that, it just pretends to be finished :)

```
interval: 86400
use_syslog: false
threads: 10
prompt: !ruby/regexp /^([\w.@-]+[#>]\s?)$/
rest: 0.0.0.0:8888
next_adds_job: false
vars:
  remove_secret: false
input:
  default: ssh,telnet
  ssh:
    secure: false
output:
  default: git
  git:
    user: user
    email: user@mail.ch
    repo: "/root/.config/oxidized/git/default.git"
source:
  default: http
  http:
    url: http://source.url/list.json
    scheme: http
    delimiter: !ruby/regexp /:/
    map:
      name: name
      ip: ip
      model: model
      username: username
      password: password
      group: domain
hooks:
  push_to_remote:
    remote_repo:
      group1: https://git.internal/group1.git
      group2: https://git.internal/group2.git
    type: githubrepo
    events: [nodes_done]
```

Using latest published version 0.24.0
