### ISSUE TITLE
Groups not getting the correct username and password

### ISSUE THREAD

**Issue by adambarnett52** [ytti/oxidized#1637]
Hi 

My router.db looks like this
```
fw1:sonicwall
```
I have set this a global username and password
```
# default username
username: admin
password: passwoedglobal
```
and my config looks like this

```
groups:
  arista:
    username: admin
    password: password
    vars:
      enable: true
      ssh_encryption: aes256-ctr
  aruba:
    usernmae: admin
    password: password2
  sonic:
    username: tech
    passowrd: password

models: {}
model_map:
  arista: eos
  hp: procurve
  aruba: aosw
  sonicwall: sonic
````

When i run in debug mode i can see that when it tries to access fw it is not using the tech username but the global one.

```
11-19T21:10:07.431755 #63995] DEBUG -- : resolving DNS for fw1...
D, [2018-11-19T21:10:07.431871 #63995] DEBUG -- : IPADDR 
D, [2018-11-19T21:10:07.434474 #63995] DEBUG -- : node.rb: resolving node key 'model', with passed global value of '' and node value 'sonic'
D, [2018-11-19T21:10:07.434575 #63995] DEBUG -- : node.rb: setting node key 'model' to value 'eos' from global
D, [2018-11-19T21:10:07.434651 #63995] DEBUG -- : node.rb: returning node key 'model' with value 'sonic'
D, [2018-11-19T21:10:07.434704 #63995] DEBUG -- : lib/oxidized/node.rb: Loading model "sonic"
D, [2018-11-19T21:10:07.437892 #63995] DEBUG -- : lib/oxidized/model/model.rb Added all to the commands list
D, [2018-11-19T21:10:07.437994 #63995] DEBUG -- : lib/oxidized/model/model.rb Added secret to the commands list
D, [2018-11-19T21:10:07.438056 #63995] DEBUG -- : lib/oxidized/model/model.rb Added show version to the commands list
D, [2018-11-19T21:10:07.438108 #63995] DEBUG -- : lib/oxidized/model/model.rb Added show inventory to the commands list
D, [2018-11-19T21:10:07.438207 #63995] DEBUG -- : lib/oxidized/model/model.rb Added show slots to the commands list
D, [2018-11-19T21:10:07.438305 #63995] DEBUG -- : lib/oxidized/model/model.rb Added show license to the commands list
D, [2018-11-19T21:10:07.438396 #63995] DEBUG -- : lib/oxidized/model/model.rb Added show running-config to the commands list
D, [2018-11-19T21:10:07.438934 #63995] DEBUG -- : node.rb: resolving node key 'input', with passed global value of 'ssh' and node value ''
D, [2018-11-19T21:10:07.439041 #63995] DEBUG -- : node.rb: returning node key 'input' with value 'ssh'
D, [2018-11-19T21:10:07.634183 #63995] DEBUG -- : node.rb: resolving node key 'output', with passed global value of 'git' and node value ''
D, [2018-11-19T21:10:07.634341 #63995] DEBUG -- : node.rb: returning node key 'output' with value 'git'
D, [2018-11-19T21:10:07.743337 #63995] DEBUG -- : node.rb: resolving node key 'username', with passed global value of '' and node value ''
D, [2018-11-19T21:10:07.743493 #63995] DEBUG -- : node.rb: setting node key 'username' to value 'admin' from global
D, [2018-11-19T21:10:07.743573 #63995] DEBUG -- : node.rb: returning node key 'username' with value 'admin'
D, [2018-11-19T21:10:07.743665 #63995] DEBUG -- : node.rb: resolving node key 'password', with passed global value of '' and node value ''
D, [2018-11-19T21:10:07.743815 #63995] DEBUG -- : node.rb: setting node key 'password' to value 'passwordglobal' from global
D, [2018-11-19T21:10:07.743908 #63995] DEBUG -- : node.rb: returning node key 'password' with value 'passwordglobal'
```
Do i have something wrong in my config

**Comment by adambarnett52** [comment]
Got it working, had to use models instead

**Comment by adambarnett52** [comment]
Figured it out , had to use models instead

**Comment by stfast** [comment]
Please share, how you did it.

**Comment by adambarnett52** [comment]
I set up models like so 

```
models:
  eos:
    username: admin
    password: REMOVED
    vars:
      enable: true
      ssh_encryption: aes256-ctr
  procurve:
    username: admin
    password: REMOVED
  aosw:
    usernmae: admin
    password: REMOVED
  sonicwall:
    username: tech
    passowrd: REMOVED
    vars:
      auth_methods: [ "password" ]
  powerconnect:
    username: admin
    password: REMOVED
    vars:
      auth_methods: ["password"]
```
and then in my router.db i set it up like so 

```
switch-s-1:hp
```
