### ISSUE TITLE
Git hook error when not using default SSH port

### ISSUE THREAD

**Issue by m1544506** [ytti/oxidized#1639]
Hi.

I'm getting an error when trying to push configurations using post_store and using a SSH port different than 22.

When oxidized tries to send configuration to git, this error is presented:

> GithubRepo: git@git.local:2712:oxidized/router.git
> GithubRepo: Authenticating using ssh keys as 'git'
> Hook push_to_remote (#<GithubRepo:0x00563ae4b600b0>) failed (#<Rugged::SshError: GitLab: The project you were looking for could not be found.#012>) for event :post_store

Current configuration:

```
hooks:
  push_to_remote:
    type: githubrepo
    events: [post_store]
    user: oxidized-user
    remote_repo:
      router: git@git.local:2712/oxidized/router.git
      switch: git@git.local:2712/oxidized/switch.git
    publickey: /home/oxidized/.ssh/id_rsa.pub
    privatekey: /home/oxidized/.ssh/id_rsa
```

Although oxidized should use port 2712, it's trying to access git server using port 22 (confirmed using tcpdump):

> IP 190.X.X.X.56864 > 190..Y.Y.Y.22: Flags [S], seq 1388051542, win 29200, options [mss 1460,sackOK,TS val 241441613 ecr 0,nop,wscale 7], length 0

If port 2712 is removed from hook configuration, oxidized can send configuration to git server properly using port 22.

What is the correct way to configure oxidized to use a different SSH port with remote_repo?

Thanks.
