### ISSUE TITLE
ciscosparkdiff Error when using diff: false

### ISSUE THREAD

**Issue by mb38291** [ytti/oxidized#1643]
Setting diff to false and using the custom message to post to Spark (WebEx Teams) results in:

`undefined method 'chat_postMessage' for #<CiscoSpark::Room:0x0000560e47c382b8>>) for event :pose_store`

It looks like **chat_postMessage** really doesn't exist. I'm using the following configuration related to the hook -- note that just using the diff option works just fine:

```
hooks:
  ciscospark:
    type: ciscosparkdiff
    events: [post_store]
    accesskey: $key
    space: $key
    diff: false
    message: "%{group}/%{node} modified"
```

I made it work by just mimicking the code (more or less) used for diff:true in **ciscosparkdiff.rb**. 

From gem list, versions are:
cisco_spark (0.3.1)
oxidized (0.24.0)
oxidized-script (0.5.1)
oxidized-web (0.11.1)

Did I overlook something or is this bugged?
