### ISSUE TITLE
PowerConnect is adding/removing 'show system' and 'show running-config' from git repo

### ISSUE THREAD

**Issue by dougthor42** [ytti/oxidized#1655]
### Summary
When running the PowerConnect with a git backend, it appears that some lines are repeatedly added and then removed.

### Expected behavior
If no changes are made to the hardware config, then no changes should be present in the git history.

### Details
These lines that get repeatedly added and removed are:
+ `! show system`
+ `show running-config`
+ `! show version`
+ some others

No other changes to the files are made. If we look at a git history, it looks something like:

```diff
# ab3b519 2018-12-10 11:05:50 update dell_powerconnet       # typo already fixed in router.db :-)
-! show system
# 32aac23 2018-12-10 10:00:27 update dell powerconnet
+! show system
# 7066548 2018-12-08 01:20:39 update dell_powerconnet
-show running-config
# 13f8b2c 2018-12-08 00:15:18 update dell_powerconnet
+show running-config
# e41046b 2018-11-23 03:19:59 update dell_powerconnet
-! show version
# e2ee3af 2018-11-13 02:14:35 update dell_powerconnet
+! show version
# d2ed5ad 2018-11-21 14:16:59 update dell_powerconnet
-! 12-Sep-2007 18:22:31 %SNMP-W-SNMPAUTHFAIL: Access attempted by unauthorized NMS
# 8c39f90 2018-11-21 13:11:37 update dell_powerconnet
+! 12-Sep-2007 18:22:31 %SNMP-W-SNMPAUTHFAIL: Access attempted by unauthorized NMS
# 44ac149 2018-11-21 12:06:15 update dell_powerconnet
-! show system
# 43c66f5 2018-11-21 11:00:51 update dell_powerconnet
+! show system
# b3e87b7 2018-11-10 21:06:56 update dell_powerconnet
-! show system
# 9746783 2018-11-10 20:01:34 update dell_powerconnet
+! show system
# ...
# older commits
```

I've included timestamps so that it's easy to see these things are happening on sequential checks. Oxidized is set up to pull the config every hour.

Things to note:
+ it's not *always* happening. There are periods of days or weeks between add-remove pairs.
+ There doesn't appear to be a pattern on which line is added-then-removed
+ It's not always comment lines

I only have the 1 PowerConnect switch, so I can't test to see if it's a hardware issue.

No other switches (mostly Cisco, some netgear, ubiquity) have this same issue.

### Version Info
```
$ oxidized --version
0.24.0-78-gb9a38db
$ uname -a
Linux oxidized 4.15.0-34-generic #37-Ubuntu SMP Mon Aug 27 15:21:48 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

### Oxidized config file
Irrelevant sections removed. Sensitive information removed.

```yaml
# Define how Oxidized should connect to things.
input:
  default: ssh, telnet
  debug: false
  ssh:
    secure: false
  ftp:
    passive: true
  utf8_encoded: true

# Define how the output should be formatted.
output:
  default: git
  file:
    directory: '/etc/oxidized/output/configs'
  git:
    user: me
    email: me@company.com
    repo: '/etc/oxidized/git-repos/default.git'

hooks:
  push_to_remote:
    type: githubrepo
    events: [post_store]
    remote_repo:
      115: 'git@gitlab.company.local:oxidized/115.git'
    publickey: '/home/oxidized/.ssh/id_rsa.pub'
    privatekey: '/home/oxidized/.ssh/id_rsa'

# Define how the `router.db` file looks.
# See https://github.com/ytti/oxidized/blob/master/docs/Sources.md
# for *slightly* more info.
source:
  default: csv
  csv:
    file: '/etc/oxidized/router.db'
    delimiter: !ruby/regexp /:/
    map:
      name: 0
      ip: 1
      model: 2
      group: 3
      username: 4
      password: 5
      # 'vars_map' allows us to override global variables on a per-source basis.
      # I think.
    vars_map:
      enable: 6
      ssh_kex: 7
      ssh_encryption: 8
```
