### ISSUE TITLE
Problem with ios device if default login to priviliged mode after upgrade to 0.25.1

### ISSUE THREAD

**Issue by dubbelj** [ytti/oxidized#1665]
Hi,
After I upgraded to 0.25.1 I got some issue with backup of ios device.
I have configured so that the default login to my devices is privileged mode and the new ios.rb enable section do a expect password prompt
    post_login do
      if vars(:enable) == true
        cmd "enable"
      elsif vars(:enable)
        **cmd "enable", /^[pP]assword:/**
        cmd vars(:enable)
      end
    end

So then I get a failed backup, as oxidized is already in enable mode there is no password prompt.

```
Dec 20 13:00:12 sea0020sas18 oxidized[23364]: lib/oxidized/input/cli.rb: Running post_login command: nil, block: #<Proc:0x0000563572a86828@/var/lib/gems/2.5.0/gems/oxidized-0.25.1/lib/oxidized/model/ios.rb:161> at 172.22.1.34
Dec 20 13:00:12 sea0020sas18 oxidized[23364]: lib/oxidized/input/ssh.rb enable @ 172.22.1.34 with expect: /^[pP]assword:/
Dec 20 13:00:12 sea0020sas18 oxidized[23364]: queueing packet nr 11 type 94 len 28
Dec 20 13:00:12 sea0020sas18 oxidized[23364]: lib/oxidized/input/ssh.rb: expecting [/^[pP]assword:/] at 172.22.1.34
...
Dec 20 13:00:32 sea0020sas18 oxidized[23364]: 172.22.1.34 raised Timeout::Error with msg "execution expired"

```
I am not very skilled with Oxidized/Ruby but would it be possible to do a check and skip enable if already in enable mode, like go next check if the prompt is like
hostname# 

As a work around I just comment out expect part
```
cmd "enable"#, /^[pP]assword:/
```

**Comment by ytti** [comment]
You need to not define your enable or set enable to false. 

It seems like you've defined enable, so it tries to enable. Empty enable string is considered empty password, which is config some people have.

**Comment by dubbelj** [comment]
Ok, I understand that but for ASA I still use enable. But I can check if I can get them to default enable mode aswell. Thanks for a great sysadmin tool and quick answer!

**Comment by ytti** [comment]
Just verbatim set 'false' as enable password to nodes where you don't want/need enable, if you still need it on some nodes.

**Comment by dwinurhadia** [comment]
Dear Sir, 
i have same issue with cisco IOS.
My device don't have password on `enable` command
If I set `false` on vars the `show running-config` cannot be execute.

Can you help me? How i can add parameter empty password on router.db??

This is for `config file`
```
vars: {
        enable: ''
      }
groups: {}
models: {}
source:
  default: csv
  csv:
    file: /home/oxidized/.config/oxidized/devices.db
    delimiter: !ruby/regexp /:/
    map:
      name: 0
      model: 1
      username: 2
      password: 3
      group: 4
    vars_map:
      ssh_port: 5
      enable: 6
    gpg: false
```

This for file router.db

`dc.dist.ugm:ios:oxidized:Secret@dssd1:Distribution: :` <-- **how i can add parameter enable if empty password for enable command**

**Comment by dwinurhadia** [comment]
Dear @dubbelj 
Thank you for your help. Its works.
Hope after I upgrade later i dont edit `ios.rb` again for cisco

**Comment by wk** [comment]
Please see the explanation on how to correctly use the enable field [here](https://github.com/ytti/oxidized/issues/1716#issuecomment-470539054). This normally should allow you to do this in configuration without having to modify the model at all.

**Comment by rpardim** [comment]
I made a lot of tests and finally I get this to work.

/etc/oxidized/config
```
username: user
password: pass
vars:
 enable: enablepass
 
source:
  default: csv
  csv:
    file: /etc/oxidized/router.db
    delimiter: !ruby/regexp /:/
    map:
      name: 0
      model: 1
      group: 2
      username: 3
      password: 4
    vars: (I changed here from vars_map to vars)
      enable: 5

groups:
  NOTENABLE:
    models:
      ios:
        vars:
          enable: false
```

/etc/oxidized/router.db
```
device1:ios:NOTENABLE
device2:ios:ENABLENODE:user:pass:enablepass
device3:ios:ENABLE
```
