### ISSUE TITLE
Fortigate issue - gathering configuration

### ISSUE THREAD

**Issue by tomicke** [ytti/oxidized#1699]
Hey!

I have just started using Oxidized, awesome software by the way :) I have a problem with gathering configuration from one of our Fortigate firewalls. I get the following in Oxidized log.

WARN -- : <IP-Address> raised Errno::EPIPE with msg "Broken pipe - send(2)"
WARN -- : <IP-Address> raised Timeout::Error with msg "execution expired"

The Fortigate i'm trying to gather configuration from is our datacenter firewall with several VDOMs and many lines. I have no issues with other Fortigates that have less configuration than our DC.
When i had issues in lab with Fortigate i could solve it by increasing the timeout value and i have tried up to 600 with our datacenter firewall without luck.  I have never seen the Broken Pipe message before.

If i SSH from the Oxidized server to the firewall i can run show full-configuration | grep . without any timeouts.

Does anyone have ideas on how this can be solved? Or suggestions on what i can do?

The following is our current Oxidized configuration, Oxidized is fed from LibreNMS.(I have indentation in the config file on the server)

```yaml
---
model: cisco
resolve_dns: true
interval: 86400
use_syslog: false
log: "/root/.config/oxidized/logs/log"
debug: false
threads: 30
timeout: 240
retries: 3
prompt: !ruby/regexp /^([\w.@-]+[#>]\s?)$/
next_adds_job: false
vars:
  remove_secret: true
models: {}
groups: {}
pid: "/root/.config/oxidized/pid"
crash:
  directory: "/root/.config/oxidized/crashes"
  hostnames: false
stats:
  history_size: 10
input:
  default: ssh
  debug: false
  ssh:
    secure: false
  ftp:
    passive: true
  utf8_encoded: true
output:
  default: git
  git:
    single_repo: true
    user: XXXX
    email: XXXXXXXX
    repo: "/opt/oxidized/data/devices.git"
source:
  default: http
  csv:
    file: "/root/.config/oxidized/devices.db"
    delimiter: !ruby/regexp /:/
    map:
      name: 0
      ip: 1
      model: 2
    gpg: false
  http:
    url: http://127.0.0.1/api/v0/oxidized
    secure: false
    map:
      name: hostname
      model: os
    headers:
      X-Auth-Token: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
model_map:
  nexus: nxos
  asr: iosxr
  fortigate: fortios
```
