### ISSUE TITLE
Oxidized to Gitlab don't work

### ISSUE THREAD

**Issue by barto95100** [ytti/oxidized#1729]
Hi,

is there anyone who could explain to me how to back up the config backup from oxidized to gitlab
I try several tutorial on the net

but I still can not ... :(

thank you so much

**Comment by MarcusCaepio** [comment]
- Create a Repo on your gitlab Server
- Create a SSH Key Pair for your **oxidized** user
- in the gitlab repo under "settings - repository - deploy keys" insert the public key of the oxidized user. Important: give write access
- in /home/oxidized/.config/oxidized/config set the git repo:
```
....
output:
  default: git
  git:
    user: oxidized
    email: oxidized@domain.de
    repo: "~/cisco-configs.git"
....
hooks:
  push_to_remote:
    type: githubrepo
    events: [post_store]
    remote_repo: git@yourgitlab.domain.de:your_repogroup/your_reponame
    publickey: /home/oxidized/.ssh/id_rsa.pub
    privatekey: /home/oxidized/.ssh/id_rsa
....
```
Works with V.0.24. and if you have installed it like it is described in the docs (with creating oxidized user) I did not update because of #1716
