### ISSUE TITLE
No configuration backup in my repository

### ISSUE THREAD

**Issue by MatteoCorleone** [ytti/oxidized#1817]
I have installed Oxidized on an Ubuntu Server 18.04.2 LTS without GUI. The first time I ran `oxidized`, I have configured the file `.config/oxidized/config` so that at the output, I can retrieve my config file in a git repository which is in `.config/oxidized/oxidized.git`. In order to test my config, I've settled the retrieval's interval to 60 seconds to make it faster. Here is my config file :

```yaml
username: adminstr
password: ubuntu
model: ios
resolve_dns: false
interval: 60
use_syslog: true
debug: false
threads: 30
timeout: 20
retries: 3
rest: false
prompt: !ruby/regexp /^([\w.@-]+[#>]\s?)$/
next_adds_job: false
vars: {}
groups: {}
models: {}
pid: "/home/oxidized/.config/oxidized/pid"
crash:
  directory: "/home/oxidized/.config/oxidized/crashes"
  hostnames: false
log: "/home/oxidized/.config/oxidized/log"
stats:
  history_size: 10
input:
  default: ssh, telnet
  debug: false
  ssh:
    secure: false
  ftp:
    passive: true
  utf8_encoded: true
output:
  default: git
  git:
    user: oxidized
    email: support@st-r.com
    single_repo: true
    repo: "/home/oxidized/.config/oxidized/oxidized.git"
source:
  default: csv
  csv:
    file: "/home/oxidized/.config/oxidized/router.db"
    delimiter: !ruby/regexp /:/
    map:
      name: 0
      model: 1
    gpg: false
model_map: 
  juniper: junos
  cisco: ios
```

And this is the tree of my directory:

```text
.config/
└── oxidized
    ├── config
    ├── configs
    ├── crash
    ├── logs
    ├── oxidized.git
    └── router.db
```

The problem is when I run `oxidized`, after one minute, I can't see anything in `oxidized.git`.
If someone could shed some light on the issue and tell me what I've forgotten to set, it would be nice.

PS: I also would like specify that I didn't install `oxidized-web` because I want to retrieve my config files directly  in command line.
