### ISSUE TITLE
custom ssh port not working

### ISSUE THREAD

**Issue by nunutuxcer** [ytti/oxidized#1861]
im using oxidized 0.26.3 with docker, im trying to backup my routeros with ssh custom port. i've trying but it still not working.

[https://github.com/ytti/oxidized/issues/173](url)

here is my config
```---
username: username
password: password
model: junos
resolve_dns: true
interval: 3600
use_syslog: false
debug: false
threads: 30
timeout: 20
retries: 3
prompt: !ruby/regexp /^([\w.@-]+[#>]\s?)$/
rest: 0.0.0.0:8888
next_adds_job: false
vars: {}
groups: {}
models: {}
pid: "/root/.config/oxidized/pid"
crash:
  directory: "/root/.config/oxidized/crashes"
  hostnames: false
stats:
  history_size: 10
input:
  default: ssh
  debug: true
  ssh:
    secure: false
  ftp:
    passive: true
  utf8_encoded: true
output:
  default: file
  file:
    directory: "/root/.config/oxidized/configs"
source:
  default: csv
  csv:
    file: "/root/.config/oxidized/router.db"
    delimiter: !ruby/regexp /:/
    map:
      name: 0
      ip: 1
      model: 2
      username: 3
      password: 4
 vars_map:
    ssh_port: 5
  gpg: false
model_map:
  juniper: junos
  cisco: ios
  mikrotik: ros
```

and router.db

```router02:192.168.1.2:routeros:admin:password-:2222```

**Comment by AlexsandrChee** [comment]
Hi!
My config:
```
 map:
      name: 0
      model: 1
      ip: 2
      username: 3
      password: 4
 vars_map:
      ssh_proxy: 5
      ssh_port: 6     
      enable: 7
```


and router.db is: 
`rb951:routeros:192.168.1.1:user_login:4eryS3cr3tP@ssw0Rd:false:34259`

It's working!
