### ISSUE TITLE
can't get ssh to pfsense/freebsd working

### ISSUE THREAD

**Issue by banananananananana** [ytti/oxidized#1926]
I can't for the life of me get ssh login to a pfsense device working.

It's as if i am using the wrong syntax in the oxidized config file. I've tried using a simple password for login, but keypairs are also failing.

```
D, [2019-10-08T09:47:44.438157 #21782] DEBUG -- : lib/oxidized/job.rb: Starting fetching process for pf1 at 2019-10-08 07:47:44 UTC
D, [2019-10-08T09:47:44.438473 #21782] DEBUG -- : lib/oxidized/input/ssh.rb: Connecting to pf1
W, [2019-10-08T09:47:44.768804 #21782]  WARN -- : 212.212.212.212 raised Net::SSH::AuthenticationFailed with msg "Authentication failed for user oxi-backup@212.212.212.212"
D, [2019-10-08T09:47:44.768913 #21782] DEBUG -- : lib/oxidized/node.rb: Oxidized::SSH failed for pf1
```

oxi config:
```
groups:
  pf-group:
    username: oxi-backup
    publickey: /home/oxidized/.config/oxidized/ssh-keys/oxi-backup-private-key.ppk
    vars:
      auth_methods: privatekey
```

```
oxidized --version
0.19.0
```

If someone could post a working example config snippet, i would be a happy bananaman.
