### ISSUE TITLE
Versions not showing up and need to add other devices

### ISSUE THREAD

**Issue by usaiat** [ytti/oxidized#1953]
Been running LibreNMS for a while now monitoring my network device ranging from Cisco (ios and nxos), Procurve/Aruba, Vyos, Ubiquiti Edge Router, pfSense and other devices. Just recently found out about oxidized and follow the instruction here to install on a different server with its own router.db file with some cisco, procurve and vyos device manually added to the router.db file, then I integrate it to LibreNMS.

Its working for the Procurve devices, and not the other devices. Status on Oxidized says “no connection” and they all showing Procurve as the model.
Also notice that the version doesnt show the difference in configuration after I test out some changes in the configuration of my procurve switches

I use RADIUS for authentication and a common service account for this. 
This is my oxdized configuration and any help will be really appreciated

---
username: username
password: password
model: procurve
resolve_dns: true
interval: 600
use_syslog: false
debug: false
threads: 30
timeout: 20
retries: 3
prompt: !ruby/regexp /^([\w.@-]+[#>]\s?)$/
rest: 0.0.0.0:8888
next_adds_job: false
vars: {}
groups: {}
models: {}
pid: "/home/oxidized/.config/oxidized/pid"
crash:
  directory: "/home/oxidized/.config/oxidized/crashes"
  hostnames: false
stats:
  history_size: 10
input:
  default: ssh, telnet
  debug: false
  ssh:
    secure: false
  ftp:
    passive: true
  utf8_encoded: true
output:
  default: file
  file:
    directory: /home/oxidized/deviceconfig
source:
  default: csv
  csv:
    file: /home/oxidized/.config/oxidized/router.db
    delimiter: !ruby/regexp /:/
    map:
      name: 0
      model: 1
      username: 2
      password: 3
    vars_map:
      enable: 4
model_map:
  juniper: junos
  cisco: ios

**Comment by shepherdjay** [comment]
So in your config file you set the default model as `procurve` in your `router.db` file did you include the model of ios for those devices that are ios?

**Comment by usaiat** [comment]
Thanks @shepherdjay. My router.db file only contain host-names or ip address of the device. So what will be the format I have to use for a device in my router.db file ? Do I have to do that for all the other types of device I have ? i.e Cisco (ios and nxos), Procurve/Aruba, Vyos, Ubiquiti Edge Router, pfSense

**Comment by shepherdjay** [comment]
So the format of your `router.db` file is this section

```
map:
    name: 0
    model: 1
    username: 2
    password: 3
vars_map:
    enable: 4
```
It is a field to index map of how your `router.db` looks so in this case it is expecting:

`name:model:username:password:enable`

Since you only contain hostnames it fills in the missing data with what you set globally. In this case you set the model to globally be inferred as `procurve`

> Do I have to do that for all the other types of device I have ? i.e Cisco (ios and nxos), Procurve/Aruba, Vyos, Ubiquiti Edge Router, pfSense

Yes. Though to be honest if you are already using Librenms you can let it do all the hard work. Librenms can provide an http source instead of having to use a `router.db` 

This is an example of the setup I am using in production:

```
source:
  default: http
  http:
    url: http://librenmsfqdn/api/v0/oxidized
    map:
      name: hostname
      ip: ip
      model: os
      group: group
    headers:
      X-Auth-Token: 'librenmsxauthtoken'
model_map:
  ios: ios
  iosxe: ios
  iosxr: iosxr
  nxos: nxos
  juniper: junos
  asa: asa
  paloalto: panos
  panos: panos
  arubaos: aosw
```
