### ISSUE TITLE
Disable some host from node list.

### ISSUE THREAD

**Issue by glaubway** [ytti/oxidized#2140]
Hello,
I'm using Oxidized with phpIPAM(collecting devices from MySQL database), and in IPAM I have many different devices, and from some of them I don't want get configuration. But, Oxidized added all devices to nodes list...
I have about ~800 devices in my network(and it's increase), but only from about 150-200 need save configuration...
So, maybe i can use some key to disable that devices in nodes list?

**Comment by jacp9** [comment]
You could add a simple column into your mysql table with nodes called 'o_enabled' or anything else really like below. Then, in your Oxidized config, have a filter to only export nodes where 'o_enabled' equals 1.

**Table Example:**
```
mysql> select * from nodes;
+--------+----------------+--------------+---------+----------------+------------+------------+-------------------+-----------+
| id     | o_name         | o_ip         | o_model | o_group        | o_username | o_password | o_enable_password | o_enabled |
+--------+----------------+--------------+---------+----------------+------------+------------+-------------------+-----------+
| 000014 | mx1.border.net | 192.168.0.30 | juniper | juniper_border | NULL       | NULL       | NULL              |         1 |
| 000015 | mx2.edge.net   | 192.168.0.31 | juniper | juniper_edge   | NULL       | NULL       | NULL              |           | 
+--------+----------------+--------------+---------+----------------+------------+------------+-------------------+-----------+
2 rows in set (0.00 sec)
```

**Oxidized Source Config:**
```
source:
  default: sql
  sql:
    adapter: mysql2
    host: <ip-of-mysql-host>
    database: <mysql-database-name>
    table: <mysql-table-containing-nodes>
    user: <mysql-user>
    password: <mysql-passwd>
    query: "SELECT * FROM nodes WHERE o_enabled = True"
    map:
      name: o_name
      ip: o_ip
      model: o_model
      group: o_group
      username: o_username
      password: o_password
    vars_map:
      enable: o_enable_password
```
