### ISSUE TITLE
Defunct hook exec process

### ISSUE THREAD

**Issue by eleksis** [ytti/oxidized#2218]
When having a custom script defined as (exec) hook, Oxidized in some situations does not read child process` status, making it a zombie. This does not occur on every hook trigger though, not exactly sure under which circumstances.

Config:
```
hooks:
  push_to_gitlab:
    type: exec
    events: [post_store]
    cmd: '/custom_script'
    async: false
    timeout: 10
```

ps aux output:
```
root     31990  0.0  0.0      0     0 ?        Z    Nov13   0:00 [custom_script] <defunct>
```
