### ISSUE TITLE
[Help] configure ssh_proxy for jumpbox

### ISSUE THREAD

**Issue by davama** [ytti/oxidized#2228]
Hello,

Trying to understand how `ssh_proxy` works but looking at old issues and this brief [doc](https://github.com/ytti/oxidized/blob/master/docs/Configuration.md#ssh-proxy-command) I cant seem to figure out.

So oxidized is one host and my myjumpbox (which accesses all the devices) is another host

My goal is to have oxidized ssh into the myjumpbox via sshkey then from there ssh into the network devices via password. (all of this by the same user `oxidized`)

I've tried moving the `ssh_proxy` around but no success.

```
username: oxidized
password: blabal
...
...
vars:
  remove_secret: true
  #auth_methods: [ "password" ]
  auth_methods: [ "publickey", "password" ]
  ssh_keys: "~/.config/oxidized/.ssh/id_ed25519"
...
...
source:
  default: sql
  sql:
    adapter: sqlite
    database: "/home/oxidized/oxidized-repo/region-oxidized.db"
    table: devices
    map:
      name: name
      ip: ip
      model: model
      group: group
    vars_map:
      ssh_proxy: proxy
```
My sql db looks like so:
```
<netdevicehostname>|<ipaddr>|ios|USA-HT_WIFI|myjumpbox
```
Here is a sample log of what I get:
```
D, [2020-12-03T14:44:37.053290 #30086] DEBUG -- : lib/oxidized/job.rb: Starting fetching process for netdevice at 2020-12-03 14:44:37 UTC
D, [2020-12-03T14:44:37.053485 #30086] DEBUG -- : lib/oxidized/input/ssh.rb: Connecting to netdevice
D, [2020-12-03T14:44:37.053633 #30086] DEBUG -- : AUTH METHODS::["publickey", "password"]
D, [2020-12-03T14:44:37.054652 #30086] DEBUG -- net.ssh.transport.session[3ff09e078428]: establishing connection to <ipaddr>:22 through proxy
Bad stdio forwarding specification '<ipaddr>:22'
W, [2020-12-03T14:44:37.063932 #30086]  WARN -- : <ipaddr> raised Net::SSH::Proxy::ConnectError (rescued RuntimeError) with msg "command failed: ssh -o StrictHostKeyChecking=no myjumpbox -W <ipaddr>:22"
D, [2020-12-03T14:44:37.064098 #30086] DEBUG -- : lib/oxidized/node.rb: Oxidized::SSH failed for netdevice
D, [2020-12-03T14:44:37.064314 #30086] DEBUG -- : lib/oxidized/job.rb: Config fetched for netdevice at 2020-12-03 14:44:37 UTC
W, [2020-12-03T14:44:38.053664 #30086]  WARN -- : USA-HW_WIFI/netdevice status no_connection, retries exhausted, giving up
```

Any input is much appreciated.

Thank you,
Dave
