### ISSUE TITLE
redirecting different groups to different remote repos

### ISSUE THREAD

**Issue by from88** [ytti/oxidized#2249]
hello,

i'm planning two have two devices groups, is it pssible to redirect each group to different repos ? currently my config is:

```
username: s-oxidized
password: password
model: cisco
interval: 3600
log: ~/.config/oxidized/log
debug: false
threads: 30
timeout: 180
retries: 3
prompt: !ruby/regexp /^([\w.@-]+[#>]\s?)$/
groups:
  defaultgroup:
    username: s-oxidized
    password: password
rest: 0.0.0.0:8888
pid: ~/.config/oxidized/oxidized.pid
input:
  default: ssh, telnet
  debug: false
  ssh:
    secure: false
output:
  default: git
  git:
    single_repo: true
    user: user
    email: oxidized@domain.com
    repo: /home/oxidized/.config/oxidized/oxidized.git
hooks:
  push_to_remote:
    type: githubrepo
    events: [post_store]
    remote_repo: "git@gitz.gitz.com:dc-network/network-configs.git"
    publickey: /etc/oxidized/.ssh/id_rsa.pub
    privatekey: /etc/oxidized/.ssh/id_rsa
source:
  default: csv
  csv:
    file: ~/.config/oxidized/router.db
    delimiter: !ruby/regexp /:/
    map:
      group: 0
      name: 1
      ip: 2
      model: 3
      username: 4
      password: 5
    vars_map:
      enable: 6
model_map:
  cisco: ios
  juniper: junos
```
so, as i will start having more than one group , how can ireference that one group should use one remote repo, and other group other repo ?

i left everything the same but changed this remote repo conf:

```
  push_to_remote:
    type: githubrepo
    events: [post_store]
    remote_repo: 
      defaultgroup: git@gitz.gitz.com:dc-network/network-configs.git
      vpngroup: git@gitz.gitz.com:dc-network/network-configs-vpn.git
    publickey: /etc/oxidized/.ssh/id_rsa.pub
    privatekey: /etc/oxidized/.ssh/id_rsa
```

And still i see that defaultgroup and vpn groups are pushed to the same network-configs.git repo..

Thank you
