### ISSUE TITLE
Edge case different password 

### ISSUE THREAD

**Issue by adambarnett52** [ytti/oxidized#2250]
Hi

I have got everything up and running, but now we have an edge case were one of our switches has a different password
i was using models  so my config looks like this: 

```
model_map:
  arista: eos
  hp: procurve
  aosw: aosw
  sonicwall: sonicwall
  dell: powerconnect
  unifi: airos
  extreme: xos

models:
  eos:
    username: username
    password: <PASSWORD>
    vars:
      enable: true
      ssh_encryption: aes256-ctr
  procurve:
    username: <username>
    password:  <PASSWORD>
    vars:
      ssh_encryption: des,3des-cbc,aes256-ctr


```

i tired using groups and assigned the group to the name of the switch 

```source:
  default: csv
  csv:
    file: ~/router.db
    delimiter: !ruby/regexp /:/
    map:
      name: 0
      model: 1
      group: 0

groups:
  switchname:
    password: blah 
    username: blah 
```

Which worked fine ( i think ) i am using git as my oputput and instead of storign the config for each switch by model it now started  sotring it by name. this means we lost all the history for each device in git, is there a way around this or a better way of dealing with edge cases 

```
```

Thanks
