### ISSUE TITLE
adding custom interval per group

### ISSUE THREAD

**Issue by from88** [ytti/oxidized#2266]
hello,

is it possible to add custom interval per group ?
Tried to do this, but seems doesn't work:

```
groups:
  defaultgroup:
    interval: 3600
  vpngroup:
    interval: 18000
```

Also, i see the same issue, but maybe it was missed: https://github.com/ytti/oxidized/issues/1985
