### ISSUE TITLE
Execution of ssh_proxy if block when the configuration variable is empty

### ISSUE THREAD

**Issue by jameskirsop** [ytti/oxidized#2267]
This is similar to #1936, but slightly different.

Take the following config extract:
```
source:
  default: sql
  sql:
    adapter: mysql2
...
    map:
      name: hostname
      ip: name
      model: model
      group: group
      username: username
      password: password
    vars_map:
      ssh_proxy: ssh_proxy
      enable: enable
```
      
and the following mysql table row:
```
hostid	|hostname	|name		|model		|group		|username	|password	|ssh_proxy	|enable	|comware_cmdline
11505	|myhost		|192.168.20.1	|netscaler	|<GROUPNAME>	|<USER>		|<redacted>	|		|	|512900
```

Currently, even though I've not set a value for `ssh_proxy`, the code block in this [if statement](https://github.com/ytti/oxidized/blob/c0dae48928ec391c01070a32c2eedb034d983c10/lib/oxidized/input/ssh.rb#L137) is executed, presumably because `""` in Ruby considered `true`:

```
Feb 23 12:29:14 nms oxidized[146462]: 192.168.20.1 raised Net::SSH::Proxy::ConnectError (rescued RuntimeError) with msg "command failed: ssh -o StrictHostKeyChecking=no  -W 192.168.20.1:22"
```

The linked if statement should be modified to grab the variable and check that it's not `nil` or `empty` before executing the corresponding code block.
