### ISSUE TITLE
githubrepo hook never fires.

### ISSUE THREAD

**Issue by iantriggs** [ytti/oxidized#2329]
I've tried the following in the official Docker image as well as a manual install on Ubuntu 20.04.

I have devices being backed up to a local git repo, I can confirm the commits are happening by checking `git log`.  I can also see revisions in the web UI.  I can't get the `githubrepo` hook to ever fire.  No log messages appear anywhere so this is proving very hard to troubleshoot.  Here are my relevant sanitised sections:

```yaml
     use_syslog: true
     debug: true
     output:
      default: git
      git:
        user: myuser
        email: myuser@xxxx.com.au
        single_repo: true
        repo: "/oxidized/git/networks_config_backups_TEST.git"
    hooks:
      push_to_remote:
        remote_repo:
          type: githubrepo
          events: [post_store]
          remote_repo: ssh://git@ssh.dev.azure.com:v3/xxxxcompany/NetworksTeam/networks_config_backups_TEST
          publickey: /root/.ssh/oxidized_test_id_rsa.pub
          privatekey: /root/.ssh/oxidized_test_id_rsa
          # remote_repo: https://xxxuser@dev.azure.com/xxxxcompany/NetworksTeam/_git/networks_config_backups_TEST
          # username: xxxuser
          # password: xxxxxxxxxxxpassword
```

No information about GithubRepo or git or github appear in `/var/log/messages`, `/var/log/syslog` or `/var/log/debug`.  It looks like the remote_repo hook is never firing at all, unless I'm looking in the wrong log file?

Things I've tried:
- converted SSH keys to RSA
- tried both HTTPS and SSH remotes
- tried Gitlab instead of Azure DevOps
- tested that post_store is firing OK by using an exec hook to write to a text file - this works fine
- checked internet firewall - no traffic is ever logged for Azure DevOps or Gitlab.

Only thing I can think of - I'm using device groups but am configured to keep it in a single repo. Is that likely to cause a problem?
