### ISSUE TITLE
awssns hook to use aws access key

### ISSUE THREAD

**Issue by longzhang-barchart** [ytti/oxidized#2335]
Hi
I'm trying to use awssns hook, I got the error below, does this hook support to use aws access key? 
`E, [2021-07-21T16:22:15.907655 #27] ERROR -- : Hook push_to_aws-sns (#<AwsSns:0x0000563b9cd0dbc0>) failed (#<Aws::Errors::MissingCredentialsError: unable to sign request without credentials set>) for event :node_fail`

My ~/.aws/credentials looks like this. Is this the right format? 
```
[us-east-1]
aws_access_key_id = *****************
aws_secret_access_key = xxxxxxxxxxxxxxxxxxxxxxxxx
```

This is my config. Oxidized is running as a container.
  ```
push_to_aws-sns:
    type: awssns
    events: [node_fail]
    region: us-east-1
    topic_arn: arn:aws:sns:us-east-1:00000000:xxxxxxxx
```

Thank you for you help.
