### ISSUE TITLE
Git Output creating folders

### ISSUE THREAD

**Issue by jonny190** [ytti/oxidized#2350]
Can i stop the Git Output creating folders and have everything in the root?

**Comment by mortzu** [comment]
```
output:
  default: git
  git:
    single_repo: true
```
