### ISSUE TITLE
Having issues with push to Github

### ISSUE THREAD

**Issue by bc-mmorris** [ytti/oxidized#2417]
I've been trying to setup Oxidized to push to a GitHub repo, but the issue I keep running into is the issue with ssh keys. I've read the multiple articles stating the key needs to be in PEM format. 

I've done that multiple times, but I keep getting the following error:

` Hook push_to_remote (#<GithubRepo:0x0000558c0d473170>) failed (#<Rugged::SshError: Failed to authenticate SSH session: Unable to send userauth-publickey request>) for event :post_store`

I've checked the permissions on the files and I beleive the oxidized user has permissions. Setting permissions in linux I admit is not my strong point, so I could have goofed something up with it. 

Where am I having an issue with this?

**Comment by MrMarioMichel** [comment]
For me it seems to work with the SSH Key files but something else is not working out as I want it 

```
oxidized    | I, [2021-12-06T12:44:17.329423 #27]  INFO -- : GithubRepo: Pushing local repository(/root/.config/oxidized/configs.git/)...
oxidized    | I, [2021-12-06T12:44:17.329555 #27]  INFO -- : GithubRepo: to remote: git@subdoman.domain.suffix:23/network-security/oxidized.git
oxidized    | D, [2021-12-06T12:44:17.401535 #27] DEBUG -- : GithubRepo: Authenticating using ssh keys as 'mario.michel'
oxidized    | E, [2021-12-06T12:44:17.401731 #27] ERROR -- : Hook push_to_remote (#<GithubRepo:0x000055a8a74e3130>) failed (#<Rugged::SshError: username does not match previous request>) for event :post_store
```


```
output:
   default: git
   git:
      user: "mario.michel"
      email: "mario.michel@domain.suffix"
      repo: "/root/.config/oxidized/configs.git"
hooks:
   push_to_remote:
      type: githubrepo
      events: [post_store]
      remote_repo: git@subdoman.domain.suffix:23/network-security/oxidized.git
      username: mario.michel
      publickey: /root/.ssh/id_rsa.pub
      privatekey: /root/.ssh/id_rsa
```
