### ISSUE TITLE
Work directory is empty when using git output

### ISSUE THREAD

**Issue by travbrack** [ytti/oxidized#244]
Hello, I'm using Oxidized on Joyent SmartOS.  

here's the the relevant bit of my config file.

```
output:
  default: git
  git:
    user: configbackup
    email: configbackup@faithlife.com
    repo: "/var/lib/oxidized/NetworkBackup/.git"
```

I'm specifying an existing git repo that I cloned before installing Oxidized.  This works okay, oxidized is making commits when configs change as expected, but it's doing something I find strange.  The work directory for the git repo is empty, even though the changes are showing up in a commit, and on github after pushing them.

Is this intended?  Reading a couple other issues, I get the impression I'm supposed to see files in the work directory.

Thanks!
Travis
