### ISSUE TITLE
Empty wr on Cisco Catalyst

### ISSUE THREAD

**Issue by usbport11** [ytti/oxidized#2442]
Good day.

If make empty config save (just wr without real changes) on Cisco Catalyst have got diff:
```
diff --git a/someip1 b/someip1
index c53e48b..1a3308c 100644
--- a/someip1
+++ b/someip1
@@ -14,7 +14,7 @@
 !
 !
 ! Last configuration change at 13:12:28 MSK Tue Dec 21 2021
-! NVRAM config last updated at 14:43:56 MSK Tue Dec 21 2021 by user
+! NVRAM config last updated at 14:27:15 MSK Tue Dec 21 2021 by user
 !
 version 15.0
 no service pad
```

Prepare scipt that run via post hook
Based on what is chanded script push or uncommit last change.
```
diff="/tmp/diff.log"

#get diff
cd /home/oxidized/.config/oxidized/output/configs.git
git diff master origin/master > $diff

#get all changes and info changes
all=`cat $diff | grep -v '^---' | grep -v '^+++' | grep '^+\|^-' | wc -l`
info=`cat $diff | grep '^+\|^-' | grep 'Last\|NVRAM' | wc -l`

#push to master or uncommit last change
if [ $all -eq $info ]
then
        echo "uncommit" > /tmp/res.dat
        git update-ref HEAD HEAD^
else
        echo "push" > /tmp/res.dat
        git push origin master
fi
```

This work with one device. 
But how it will work with many devices while oxidized use multithread logic?
Will the script work correctly?
Will async parameter in config with false value not allow other threads to push data at same time?
```
output:
  default: git
  git:
    single_repo: true
    user: oxidized
    email: sysadmin@nipigas.ru
    repo: "/home/oxidized/.config/oxidized/output/configs.git"
hooks:
  push_to_remote:
    type: exec
    events: [post_store]
    cmd: "/home/oxidized/.config/oxidized/update.sh"
    anync: false
    timeout: 120
```
