### ISSUE TITLE
git path being ignored, changes going to /home/oxidized/.config/oxidized/oxidized.git instead

### ISSUE THREAD

**Issue by athompson-merlin** [ytti/oxidized#2485]
It appears that all the config directives in this config (/etc/oxidized/config) file are being obeyed EXCEPT `repo` and I'm at a loss to understand why:
```YAML
output:
  default: git
  git:
    user: Oxidized
    email: root@merlinoffice.local
    repo: "/etc/oxidized/git-repos/default.git"
```

Instead, I finally just found the repo it's ACTUALLY writing to in /home/oxidized/.config/oxidized/oxidized.git.  (That's the bare git repo, it's not in a subdirectory of oxidized.git.)

I have commits in /etc/oxidized/git-repos/default.git (again, a bare repo) up until 2021-Sep-08, and then it looks like Oxidized started a fresh git repo in a new path (the one under /home/oxidized) and proceeded to log all the subsequent commits in this new repo.

I'm unable to find anywhere in the code that refers to this path as a default, but I also know ".config" is special in some frameworks, and I can't read Ruby well enough to figure it out.

I'm starting Oxidized with systemd from /etc/systemd/system/oxidized.service:
```
[Unit]
Description=Oxidized - Network Device Configuration Backup Tool
After=network-online.target multi-user.target
Wants=network-online.target

[Service]
ExecStart=/usr/local/bin/oxidized
User=oxidized
KillSignal=SIGKILL
Environment="OXIDIZED_HOME=/etc/oxidized"
Restart=on-failure
RestartSec=300s
AmbientCapabilities=CAP_NET_BIND_SERVICE

[Install]
WantedBy=multi-user.target
```

Running Alma Linux 8.5 with ruby 2.5.9p229 (2021-04-05 revision 67939) [x86_64-linux], nothing special that I know, this is based on the same VM template the other ~50 apps are.

Pretty sure OXIDIZED_HOME is working, because everything else in /etc/oxidized/config appears to be taking effect.  And /home/oxidized/.config/oxidized/config is empty... um, other than an output->git section with the unexpected path.

The entire contents of /home/oxidized/.config/oxidized/config are:
```YAML
---
output:
  git:
    user: Oxidized
    email: o@example.com
    repo: "/home/oxidized/.config/oxidized/oxidized.git"
```

Could Oxidized be reading more than one config file, with the second overriding the first??

(Also: once I figure this out, how do I merge two git repos, à la `cat  pre-Sep-commits  post-Sep-commits  >  all-commits` ?
