### ISSUE TITLE
Github SSH support changes

### ISSUE THREAD

**Issue by mdugdale** [ytti/oxidized#2526]
Due to github changing support for SSH keys: https://github.blog/2021-09-01-improving-git-protocol-security-github/, RSA keys with SHA-1 no longer work for github authentication. The solution would be to use ed25519 keys, but these are in the OPENSSH format, which does not work https://github.com/ytti/oxidized/issues/2324. I tried building a new oxidized docker image with hirsute which has libssh2 1.9, but this did not work. I also tried bumping the version of various gems like rugged and net-ssh to no avail. I'd get errors such as 
```
Failed to authenticate SSH session: Unable to send userauth-publickey request (Rugged::SshError)
```
Due to this, I am not able to configure oxidized to push to git

**Comment by thamiluz** [comment]
I am with the same problem.

Anyone could manage this?

**Comment by mortzu** [comment]
We need to update Net::SSH to the actual version in gemspec (and maybe update some code - I don't know if there are any breaking changes)

duplicate of #2314

**Comment by NoifP** [comment]
For anyone else that comes across this issue you might be able to use this workaround in your oxidized config file.

```
hooks:
  push_to_github:
    type: exec
    events: [post_store]
    cmd: 'git --git-dir=/opt/oxidized/git/oxidized.git push -u origin master'
    async: true
    timeout: 120
```
