### ISSUE TITLE
Using http as source and http as output craches the app

### ISSUE THREAD

**Issue by IvoGuerreiro** [ytti/oxidized#2547]
Hi,

This is a Snippet of my conf file:
```
output:
  default: http
  http:
    url: "http://device-inventory:5000/oxireport"
    scheme: http
source:
  default: http
  http:
    url: "http://device-inventory:5000/oxibatch2"
    scheme: http
```

If I change source to csv or any other one, the process runs smoothly til the end and the HTTP POST is made to the URL.

But if I use http also as source, the process will fail in the later stage when is posting the configuration.
The error is following:

```
undefined method `store' for #<Oxidized::HTTP:0x00007f6cd802dd38>
Traceback (most recent call last):
        12: from /usr/local/bundle/bin/oxidized:23:in `<main>'
        11: from /usr/local/bundle/bin/oxidized:23:in `load'
        10: from /usr/local/bundle/gems/oxidized-0.28.0/bin/oxidized:8:in `<top (required)>'
         9: from /usr/local/bundle/gems/oxidized-0.28.0/lib/oxidized/cli.rb:13:in `run'
         8: from /usr/local/bundle/gems/oxidized-0.28.0/lib/oxidized/core.rb:4:in `new'
         7: from /usr/local/bundle/gems/oxidized-0.28.0/lib/oxidized/core.rb:4:in `new'
         6: from /usr/local/bundle/gems/oxidized-0.28.0/lib/oxidized/core.rb:29:in `initialize'
         5: from /usr/local/bundle/gems/oxidized-0.28.0/lib/oxidized/core.rb:36:in `run'
         4: from /usr/local/bundle/gems/oxidized-0.28.0/lib/oxidized/worker.rb:16:in `work'
         3: from /usr/local/bundle/gems/oxidized-0.28.0/lib/oxidized/worker.rb:16:in `each'
         2: from /usr/local/bundle/gems/oxidized-0.28.0/lib/oxidized/worker.rb:16:in `block in work'
         1: from /usr/local/bundle/gems/oxidized-0.28.0/lib/oxidized/worker.rb:47:in `process'
/usr/local/bundle/gems/oxidized-0.28.0/lib/oxidized/worker.rb:65:in `process_success': undefined method `store' for #<Oxidized::HTTP:0x00007f6cd802dd38> (NoMethodError)
    
```

Best Regards
