### ISSUE TITLE
HTTP Source: source returns no usable nodes

### ISSUE THREAD

**Issue by supertylerc** [ytti/oxidized#255]
See ytti/oxidized-web#39 for history.

Bug has been confirmed with the following Oxidized config:

```yaml
---
username: abc
password: abc
model: junos
interval: 3600
log: "/home/vagrant/.config/oxidized/log"
debug: true
threads: 30
timeout: 20
retries: 3
prompt: !ruby/regexp /^([\w.@-]+[#>]\s?)$/
rest: 0.0.0.0:8888
vars: {}
groups: {}
input:
  default: ssh
  debug: false
  ssh:
    secure: false
output:
  default: git
  git:
    user: oxidized
    email: oxidized@tylerc.me
    repo: "/home/vagrant/.config/oxidized/configs.git"
    single_repo: true
source:
  default: http
  debug: true
  http:
    url: http://librenms.example.com/api/v0/oxidized
    scheme: http
    delimiter: !ruby/regexp /:/
    map:
      name: hostname
      model: os
    headers:
      X-Auth-Token: 'abc123'
model_map:
  cisco: ios
  juniper: junos
```

This is the output:

```
$ oxidized
source returns no usable nodes
/home/vagrant/.rvm/gems/ruby-2.2.4@oxidized/gems/oxidized-0.9.0/lib/oxidized/core.rb:23:in `initialize': source returns no usable nodes (Oxidized::Core::NoNodesFound)
        from /home/vagrant/.rvm/gems/ruby-2.2.4@oxidized/gems/oxidized-0.9.0/lib/oxidized/core.rb:12:in `new'
        from /home/vagrant/.rvm/gems/ruby-2.2.4@oxidized/gems/oxidized-0.9.0/lib/oxidized/core.rb:12:in `new'
        from /home/vagrant/.rvm/gems/ruby-2.2.4@oxidized/gems/oxidized-0.9.0/lib/oxidized/cli.rb:9:in `run'
        from /home/vagrant/.rvm/gems/ruby-2.2.4@oxidized/gems/oxidized-0.9.0/bin/oxidized:9:in `<top (required)>'
        from /home/vagrant/.rvm/gems/ruby-2.2.4@oxidized/bin/oxidized:23:in `load'
        from /home/vagrant/.rvm/gems/ruby-2.2.4@oxidized/bin/oxidized:23:in `<main>'
        from /home/vagrant/.rvm/gems/ruby-2.2.4@oxidized/bin/ruby_executable_hooks:15:in `eval'
        from /home/vagrant/.rvm/gems/ruby-2.2.4@oxidized/bin/ruby_executable_hooks:15:in `<main>'
$
```

The above was tested with LibreNMS returning the following data:

```json
[
    {
        "hostname": "192.168.33.2",
        "os": "vyos"
    },
    {
        "hostname": "192.168.33.3",
        "os": "vyos"
    }
]
```

**Comment by supertylerc** [comment]
I just tested this against a "dummy" API.  Here's what the API is:

```ruby
require 'json'
require 'sinatra'
get '/' do
  [{
    hostname: '192.168.33.2',
    os: 'vyos'
  }, {
    hostname: '192.168.33.3',
    os: 'vyos'
  }].to_json
end
```

The response:

```json
[
   {
      "hostname" : "192.168.33.2",
      "os" : "vyos"
   },
   {
      "os" : "vyos",
      "hostname" : "192.168.33.3"
   }
]
```

And Oxidized's errors (which are the same):

```
$ oxidized
source returns no usable nodes
/home/vagrant/.rvm/gems/ruby-2.2.4@oxidized/gems/oxidized-0.9.0/lib/oxidized/core.rb:23:in `initialize': source returns no usable nodes (Oxidized::Core::NoNodesFound)
        from /home/vagrant/.rvm/gems/ruby-2.2.4@oxidized/gems/oxidized-0.9.0/lib/oxidized/core.rb:12:in `new'
        from /home/vagrant/.rvm/gems/ruby-2.2.4@oxidized/gems/oxidized-0.9.0/lib/oxidized/core.rb:12:in `new'
        from /home/vagrant/.rvm/gems/ruby-2.2.4@oxidized/gems/oxidized-0.9.0/lib/oxidized/cli.rb:9:in `run'
        from /home/vagrant/.rvm/gems/ruby-2.2.4@oxidized/gems/oxidized-0.9.0/bin/oxidized:9:in `<top (required)>'
        from /home/vagrant/.rvm/gems/ruby-2.2.4@oxidized/bin/oxidized:23:in `load'
        from /home/vagrant/.rvm/gems/ruby-2.2.4@oxidized/bin/oxidized:23:in `<main>'
        from /home/vagrant/.rvm/gems/ruby-2.2.4@oxidized/bin/ruby_executable_hooks:15:in `eval'
        from /home/vagrant/.rvm/gems/ruby-2.2.4@oxidized/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by supertylerc** [comment]
Not a bug.  Resulted from misconfiguration.  Needed to add a model map: LibreNMS returns `vyos` as the model, but in Oxidized it is `vyatta`.  Working Oxidized config:

```yaml
---
username: abc
password: abc
model: junos
interval: 3600
log: "/home/vagrant/.config/oxidized/log"
debug: true
threads: 30
timeout: 20
retries: 3
prompt: !ruby/regexp /^([\w.@-]+[#>]\s?)$/
rest: 0.0.0.0:8888
vars: {}
groups: {}
input:
  default: ssh
  debug: true
  ssh:
    secure: false
output:
  default: git
  git:
    user: oxidized
    email: oxidized@tylerc.me
    repo: "/home/vagrant/.config/oxidized/configs.git"
    single_repo: true
source:
  default: http
  debug: true
  http:
    url: http://librenms.example.com/api/v0/oxidized
    scheme: http
    delimiter: !ruby/regexp /:/
    map:
      name: hostname
      model: os
    headers:
      X-Auth-Token: 'abc123'
model_map:
  cisco: ios
  juniper: junos
  vyos: vyatta
```
