### ISSUE TITLE
latest docker image not creating git repo output properly

### ISSUE THREAD

**Issue by rismoney** [ytti/oxidized#2566]
I am new to oxidized, and trying to validate some configs using docker.

looks like it is not placing the output in this path, and the repo is not properly initialized.
I do see my router config in /root/.config/oxidized/configs

```
myserver:/root/oxidized# docker exec -it oxidized_oxidized_1 /bin/bash
root@oxidized:/# cd ~/.config/oxidized/git
root@oxidized:~/.config/oxidized/git# ls -la
total 16
drwxr-xr-x. 6 root root 116 Jun 16 21:24 .
drwxr-xr-x. 6 root root 136 Jun 16 21:31 ..
-rw-r--r--. 1 root root 120 Jun 16 21:24 config
-rw-r--r--. 1 root root  73 Jun 16 21:24 description
-rw-r--r--. 1 root root  23 Jun 16 21:24 HEAD
drwxr-xr-x. 2 root root  27 Jun 16 21:24 hooks
-rw-r--r--. 1 root root 145 Jun 16 21:24 index
drwxr-xr-x. 2 root root  21 Jun 16 21:24 info
drwxr-xr-x. 7 root root  60 Jun 16 21:24 objects
drwxr-xr-x. 4 root root  31 Jun 16 21:24 refs
root@oxidized:~/.config/oxidized/git# git status
fatal: this operation must be run in a work tree
```

docker-compose file:

```yaml
oxidized:
  hostname: oxidized.example.com
  restart: always
  image: oxidized/oxidized:latest
  environment:
    CONFIG_RELOAD_INTERVAL: 600
  volumes:
    - ./oxidized_conf:/root/.config/oxidized
```

relevant config:

```yaml
output:
  default: git
  git:
    user: me
    email: me@example.com
    repo: "~/.config/oxidized/git"   # i tried with foo.git too.  also single-repo
```

**Comment by gbe0** [comment]
Hi,

The git repository is "bare repository" - there is no work tree.

You can clone it if you want to browse around:

`git clone /root/.config/oxidized/git /tmp/oxidized-clone`

**Comment by rismoney** [comment]
this makes sense now, and that command worked for local viewing.   i was expecting to see a see a non-bare/default repo just in gaining understanding of the tool.

so if i wanted to push to a remote repo, I'd need something like-

```yaml
hooks:
  push_to_remote:
    remote_repo:
      network-devices:
        url: user@stash.example.com:7999/NET/network-devices.git
        privatekey: /root/.config/oxidized/ssh.key.pem
```
From what I read in the hooks doc (I've now re-read them) the hooks repo and the output repo are not to be the same repo ?
So I am guessing I don't need the output to be git (unless I have a need for a local gitrepo?) ,
If my goal is a remote push I just need the hook like I have in the above?

Just wanted to clarify, and i appreciate your help!
