### ISSUE TITLE
Cisco - IPADDR raised Oxidized::PromptUndetect with msg "unable to detect prompt: (?-mix:^([\w.@()-]+[#>]\s?)$)"

### ISSUE THREAD

**Issue by krilson** [ytti/oxidized#2666]
Not so much an issue maybe, more just confusion.

LibreNMS feeds oxidized with devices. (mostly cisco switches). 

In LibreNMS the group is named: **cisco**

In .config/oxidized/config I have:

```
model_map:
  cisco: ios
  juniper: junos
  pfsense: pfsense
groups:
  pfsense:
    username: oxidized
    password: oxidized
  cisco:
    username: oxidized
    password: oxidized
```
For cisco devices I get (telnet) in the logs:
`IPADDR raised Oxidized::PromptUndetect with msg "unable to detect prompt: (?-mix:^([\w.@()-]+[#>]\s?)$)"
`

Found this https://github.com/ytti/oxidized/issues/1559#issuecomment-429574639 
If I understand correctly oxidized should understand cisco, but where do I tell it it is a cisco? Is it enough that the group name is cisco? Or this model_map or what exactly makes it treat a device like a cisco?

So I can not figure out where is this reference from group to model to model_map to this ciscosmb.rb. How is it all connected together? The docs arent very helpful on this...

My assumption is that oxidized at the moment does not identify this devices as cisco since I does not detect the prompt... 

Any hints appreciated.
