### ISSUE TITLE
SSH proxy and node credentials

### ISSUE THREAD

**Issue by angely-dev** [ytti/oxidized#2695]
Hello,

*Maybe related to #1609.*

I want Oxidized to access some network nodes behind a proxy ([Configuration.md#ssh-proxy-command](https://github.com/ytti/oxidized/blob/master/docs/Configuration.md#ssh-proxy-command)):

* Oxidized SSH public key has been added to `.ssh/authorized_keys` of the proxy
* And indeed the SSH authentication works between the two
* It fails when Oxidized tries to connect to the nodes behind the proxy

My guess is that Oxidized does not use the SSH credentials (username and password) provided for these nodes.

My `config` file looks like:

```yaml
resolve_dns: false
models:
    # SSH credentials to use for nodes behind the proxy   
    huawei_proxy:
        username: <USERNAME>
        password: <PASSWORD>
source:
  default: csv
  csv:
    file: "/home/oxidized/.config/oxidized/router.db"
    delimiter: !ruby/regexp /:/
    map:
      name: 0
      model: 1
    vars_map:
        ssh_proxy: 2
model_map:
  huawei: vrp
  huawei_proxy: vrp
```

And my `router.db`:

```csv
node1:huawei_proxy:the-proxy
node2:huawei
```

The debug:

```
$ oxidized --debug
I, [2023-01-16T12:25:42.109501 #81886]  INFO -- : Oxidized starting, running as pid 81886
I, [2023-01-16T12:25:42.109848 #81886]  INFO -- : lib/oxidized/nodes.rb: Loading nodes
D, [2023-01-16T12:25:42.109960 #81886] DEBUG -- : resolving DNS for node1...
(...)
Puma starting in single mode...
* Version 3.11.4 (ruby 2.7.4-p191), codename: Love Song
* Min threads: 0, max threads: 16
* Environment: development
* Listening on tcp://192.168.198.8:8888
Use Ctrl-C to stop
D, [2023-01-16T12:25:43.356455 #81886] DEBUG -- : lib/oxidized/worker.rb: Jobs running: 0 of 1 - ended: 0 of 4
D, [2023-01-16T12:25:43.356690 #81886] DEBUG -- : lib/oxidized/worker.rb: Added /node1 to the job queue
D, [2023-01-16T12:25:43.356709 #81886] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2023-01-16T12:25:43.356767 #81886] DEBUG -- : lib/oxidized/job.rb: Starting fetching process for node1 at 2023-01-16 11:25:43 UTC
D, [2023-01-16T12:25:43.356881 #81886] DEBUG -- : lib/oxidized/input/ssh.rb: Connecting to node1
D, [2023-01-16T12:25:43.356989 #81886] DEBUG -- : AUTH METHODS::["password"]
D, [2023-01-16T12:25:44.357834 #81886] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2023-01-16T12:25:45.359021 #81886] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
Password:
D, [2023-01-16T12:25:46.360194 #81886] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2023-01-16T12:25:47.361430 #81886] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2023-01-16T12:25:48.362646 #81886] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
```

At the end of the output, we can see the prompt of the node (`Password: `), meaning Oxidized successfully accessed the proxy and is trying to connect to the node, but it won't go further.

* Did I miss something?
* Is this supported?

Thanks!
