### ISSUE TITLE
ERROR -- : Hook slack (#<SlackDiff:0x00005572c9621e20>) failed (#<NameError: uninitialized constant Slack::Client>) for event :post_store

### ISSUE THREAD

**Issue by saintwolf** [ytti/oxidized#2697]
Hi all,

I've set up a new oxidized server to replace an old one and am having trouble getting the slackdiff hook to work.

I've installed the gem via `gem install slack-ruby-client` and included the following configuration:

```
hooks:
  slack:
    type: slackdiff
    events: [post_store]
    token: xoxb-REDACTED
    channel: "#network-changes"
```

Whenever any changes are made I seem to get the error `ERROR -- : Hook slack (#<SlackDiff:0x00005572c9621e20>) failed (#<NameError: uninitialized constant Slack::Client>) for event :post_store`

Has anyone experienced this and knows a fix/workaround?
