### ISSUE TITLE
PA220 and S3900

### ISSUE THREAD

**Issue by beta6nine9** [ytti/oxidized#2708]
EDIT:  Finally figured it out.  Documentation is lacking, but so is my YAML skills lol.
We have a PA220/S3900 and I cannot get oxidized working on it.  I can ssh as admin with no problem, it's just oxidized doesn't seem to like working with it.  

I've tried the PANOS.rb default and modified with suggestions from the issues posts.

router.db:
`1.1.1.1:panos:admin:password`
`2.2.2.2:edgecos:admin:admin`

When launching oxidized I get "`raised Net::SSH::AuthenticationFailed with msg "Authentication failed for user username@(routerIP)`".

I have no idea what I'm supposed to do next.  I've tried customizing the ~/.config/oxidized/config with:
```
groups:
  foo:
    models:
      panos:
        username: admin
        password: realpassword
      edgecos:
        username: admin
        password: realpassword
```

Is there someone that can post config/router.db for PA220 and S3900-48T6S-R (Version 2.2.0F Build 99729) that work?  Maybe post their modules that I can use?
