### ISSUE TITLE
Local repo to AWS Code commit.

### ISSUE THREAD

**Issue by Paddys2** [ytti/oxidized#2717]
I have been trying to push the local repo to aws code commit using hooks which is getting failed. appreciate if some once can help in to share there inputs. 

Below is the hooks command which I'm trying, appreciate if some once can help in this.

```
output:
  default: git
  git:
    user: oxidized
    email: o@example.com
    repo: "/home/oxidized/.config/oxidized/git-repos/default.git"
hooks:
  push_to_remote:
    type: exec
    events: [post_store]
    cmd: "git --/home/oxidized/.config/oxidized/ ssh://git-codecommit@URL"

```
