### ISSUE TITLE
Issue starting oxidized

### ISSUE THREAD

**Issue by neteqipfcsd25** [ytti/oxidized#2737]
Ubuntu version  22.04.2 LTS

Recive when starting
```
I, [2023-03-28T12:03:10.290182 #1982291]  INFO -- : Oxidized starting, running as pid 1982291
I, [2023-03-28T12:03:10.377085 #1982291]  INFO -- : lib/oxidized/nodes.rb: Loading nodes
F, [2023-03-28T12:03:10.379531 #1982291] FATAL -- : Oxidized crashed, crashfile written in /home/oxidized/.config/oxidized/crash
undefined method `include?' for nil:NilClass
```

```
oxidized@libreNMS:~/.config/oxidized$ oxidized -debug
unknown option `-e'
/var/lib/gems/3.0.0/gems/slop-4.10.1/lib/slop/parser.rb:131:in `try_process': unknown option `-e' (Slop::UnknownOption)
        from /var/lib/gems/3.0.0/gems/slop-4.10.1/lib/slop/parser.rb:151:in `block in try_process_grouped_flags'
        from /var/lib/gems/3.0.0/gems/slop-4.10.1/lib/slop/parser.rb:151:in `each'
        from /var/lib/gems/3.0.0/gems/slop-4.10.1/lib/slop/parser.rb:151:in `try_process_grouped_flags'
        from /var/lib/gems/3.0.0/gems/slop-4.10.1/lib/slop/parser.rb:128:in `try_process'
        from /var/lib/gems/3.0.0/gems/slop-4.10.1/lib/slop/parser.rb:59:in `block in parse'
        from /var/lib/gems/3.0.0/gems/slop-4.10.1/lib/slop/parser.rb:49:in `each'
        from /var/lib/gems/3.0.0/gems/slop-4.10.1/lib/slop/parser.rb:49:in `each_with_index'
        from /var/lib/gems/3.0.0/gems/slop-4.10.1/lib/slop/parser.rb:49:in `parse'
        from /var/lib/gems/3.0.0/gems/slop-4.10.1/lib/slop/options.rb:76:in `parse'
        from /var/lib/gems/3.0.0/gems/slop-4.10.1/lib/slop.rb:23:in `parse'
        from /var/lib/gems/3.0.0/gems/oxidized-0.28.0/lib/oxidized/cli.rb:44:in `parse_opts'
        from /var/lib/gems/3.0.0/gems/oxidized-0.28.0/lib/oxidized/cli.rb:23:in `initialize'
        from /var/lib/gems/3.0.0/gems/oxidized-0.28.0/bin/oxidized:8:in `new'
        from /var/lib/gems/3.0.0/gems/oxidized-0.28.0/bin/oxidized:8:in `<top (required)>'
        from /usr/local/bin/oxidized:25:in `load'
        from /usr/local/bin/oxidized:25:in `<main>'
```

Config

```yaml
---
username: something you dont need to know
password: same
model: cisco
resolve_dns: true
interval: 3600
use_syslog: false
debug: false
threads: 30
timeout: 20
retries: 3
prompt: !ruby/regexp /^([\w.@-]+[#>]\s?)$/
rest: 10.0.1.85
next_adds_job: false
vars: {}
groups: {}
models: {}
pid: "/home/oxidized/.config/oxidized/pid"
crash:
  directory: "/home/oxidized/.config/oxidized/crashes"
  hostnames: false
stats:
  history_size: 10
input:
  default: ssh, telnet
  debug: true
  ssh:
    secure: false
  ftp:
    passive: false
  utf8_encoded: true
output:
  default: file
  file:
    directory: "/home/oxididized/.config/oxidized/configs"
source:
  default: http
  debug: true
  http:
    url: http:///10.0.1.85/api/v0/oxidized
    scheme: http
    file: "/home/oxidized/.config/oxidized/router.db"
    delimiter: !rudy/regexp /:/
    map:
      name: hostname
      model: os
      username: username
      password: password
      group: group
    vars_map:
      ssh_port: ssh_port
    headers:
      X-Auth-Token: 'cff9a6e08e35f585362cb3c7387b0dec'
model_map:
  cisco: iOS
```

Doig a Curl works fine.
