### ISSUE TITLE
Oxidized crushed 

### ISSUE THREAD

**Issue by goro22052** [ytti/oxidized#2744]
Hi, I have a problem oxidized 0.28.0.
I added one router mikrotik in file 
~/.config/oxidized/mikrotik/router.db

MKlteRivne:routeros:1.1.1.1:22:kiwi:password

And I have the config

/home/oxidized/.config/oxidized/config

```yaml
model: routeros
resolve_dns: true
interval: 60
use_syslog: true
threads: 30
timeout: 180
retries: 3
prompt: !ruby/regexp /^([\w.@-]+[#>]\s?)$/
rest: 0.0.0.0:8888
next_adds_job: false
vars: {}
groups: {}
models: {}
pid: "~/.config/oxidized/pid"
log: "~/.config/oxidized/logs/"
crash: "~/.config/oxidized/crashes/"
stats:
  history_size: 10
input:
  default: ssh
  debug: true
  ssh:
    secure: false
map:
  verify_host_key: never
  utf8_encoded: true
output:
  default: git
  git:
    user: oxidized
    email: go@gmail.com
    repo: "~/.config/oxidized/devices/devices.git"
source:
  default: csv
  csv:
    file: "~/.config/oxidized/mikrotik/router.db"
    delimiter: !ruby/regexp /:/
    map:
      name: 0
      model: 1
      ip: 2
      port: 3
      username: 4
      password: 5
model_map:
  Cisco: ios
  mikrotik: routeros
```

but when I run oxidized I see the error 

```

Puma starting in single mode...
* Version 3.11.4 (ruby 3.0.2-p107), codename: Love Song
* Min threads: 0, max threads: 16
* Environment: development
* Listening on tcp://0.0.0.0:8888
Use Ctrl-C to stop



#<Oxidized::Job:0x000055bb9f111bc8 /var/lib/gems/3.0.0/gems/oxidized-0.28.0/lib/oxidized/job.rb:7 run> terminated with exception (report_on_exception is true):
/var/lib/gems/3.0.0/gems/oxidized-0.28.0/lib/oxidized/node.rb:78:in `rescue in run_input': undefined method `directory' for "~/.config/oxidized/crashes/":String (NoMethodError)
        from /var/lib/gems/3.0.0/gems/oxidized-0.28.0/lib/oxidized/node.rb:66:in `run_input'
        from /var/lib/gems/3.0.0/gems/oxidized-0.28.0/lib/oxidized/node.rb:44:in `block in run'
        from /var/lib/gems/3.0.0/gems/oxidized-0.28.0/lib/oxidized/node.rb:38:in `each'
        from /var/lib/gems/3.0.0/gems/oxidized-0.28.0/lib/oxidized/node.rb:38:in `run'
        from /var/lib/gems/3.0.0/gems/oxidized-0.28.0/lib/oxidized/job.rb:9:in `block in initialize'
/var/lib/gems/3.0.0/gems/net-ssh-5.2.0/lib/net/ssh/transport/kex/diffie_hellman_group1_sha1.rb:124:in `set_pqg': dh#set_pqg= is incompatible with OpenSSL 3.0 (OpenSSL::PKey::PKeyError)
        from /var/lib/gems/3.0.0/gems/net-ssh-5.2.0/lib/net/ssh/transport/kex/diffie_hellman_group1_sha1.rb:124:in `generate_key'
        from /var/lib/gems/3.0.0/gems/net-ssh-5.2.0/lib/net/ssh/transport/kex/diffie_hellman_group1_sha1.rb:55:in `initialize'
        from /var/lib/gems/3.0.0/gems/net-ssh-5.2.0/lib/net/ssh/transport/kex/diffie_hellman_group_exchange_sha256.rb:9:in `initialize'
        from /var/lib/gems/3.0.0/gems/net-ssh-5.2.0/lib/net/ssh/transport/algorithms.rb:398:in `new'
        from /var/lib/gems/3.0.0/gems/net-ssh-5.2.0/lib/net/ssh/transport/algorithms.rb:398:in `exchange_keys'
        from /var/lib/gems/3.0.0/gems/net-ssh-5.2.0/lib/net/ssh/transport/algorithms.rb:228:in `proceed!'
        from /var/lib/gems/3.0.0/gems/net-ssh-5.2.0/lib/net/ssh/transport/algorithms.rb:167:in `accept_kexinit'
        from /var/lib/gems/3.0.0/gems/net-ssh-5.2.0/lib/net/ssh/transport/session.rb:210:in `block in poll_message'
        from /var/lib/gems/3.0.0/gems/net-ssh-5.2.0/lib/net/ssh/transport/session.rb:190:in `loop'
        from /var/lib/gems/3.0.0/gems/net-ssh-5.2.0/lib/net/ssh/transport/session.rb:190:in `poll_message'
        from /var/lib/gems/3.0.0/gems/net-ssh-5.2.0/lib/net/ssh/transport/session.rb:225:in `block in wait'
        from /var/lib/gems/3.0.0/gems/net-ssh-5.2.0/lib/net/ssh/transport/session.rb:223:in `loop'
        from /var/lib/gems/3.0.0/gems/net-ssh-5.2.0/lib/net/ssh/transport/session.rb:223:in `wait'
        from /var/lib/gems/3.0.0/gems/net-ssh-5.2.0/lib/net/ssh/transport/session.rb:90:in `initialize'
        from /var/lib/gems/3.0.0/gems/net-ssh-5.2.0/lib/net/ssh.rb:246:in `new'
        from /var/lib/gems/3.0.0/gems/net-ssh-5.2.0/lib/net/ssh.rb:246:in `start'
        from /var/lib/gems/3.0.0/gems/oxidized-0.28.0/lib/oxidized/input/ssh.rb:27:in `connect'
        from /var/lib/gems/3.0.0/gems/oxidized-0.28.0/lib/oxidized/node.rb:67:in `run_input'
        from /var/lib/gems/3.0.0/gems/oxidized-0.28.0/lib/oxidized/node.rb:44:in `block in run'
        from /var/lib/gems/3.0.0/gems/oxidized-0.28.0/lib/oxidized/node.rb:38:in `each'
        from /var/lib/gems/3.0.0/gems/oxidized-0.28.0/lib/oxidized/node.rb:38:in `run'
        from /var/lib/gems/3.0.0/gems/oxidized-0.28.0/lib/oxidized/job.rb:9:in `block in initialize'
undefined method `directory' for "~/.config/oxidized/crashes/":String
```

How I can fix this problem?
