### ISSUE TITLE
Running in container with bind mount

### ISSUE THREAD

**Issue by ZummiGummi** [ytti/oxidized#2775]
I'm running the latest Oxidized container, image ID, 9b95fd2be45d.
Below is the docker-compose.yml file.
```
version: "3"
services:
  oxidized:
    restart: always
    image: oxidized/oxidized: latest
    container_name: oxidized2
    ports:
      - 9999:8888/tcp
    environment:
      CONFIG_RELOAD_INTERVAL: 600
    volumes:
       - ./config:/home/oxidized/.config/oxidized/
```
Note that I'm using a bind mount  `       - ./config:/home/oxidized/.config/oxidized/`

When the container is started, the ./config folder is created with permissions of user and group 30000. My host system doesn't have a user or group ID of 30000. I would like to remap the container user ID and group ID to a user account on the host.
But this isn't possible, as the container is running as root, but Oxidized is running as user oxidized (30000). I could be wrong here, but the container generates lots of permission errors when I try this.

Adding
```
version: "3"
services:
  oxidized:
    restart: always
    user: 1000:1000
```

> oxidized2   | PermissionError: [Errno 13] Permission denied: '/etc/container_environment'
> oxidized2   | *** Killing all processes...
> oxidized2   | Traceback (most recent call last):
> oxidized2   |   File "/sbin/my_init", line 414, in <module>
> oxidized2   |     main(args)
> oxidized2   |   File "/sbin/my_init", line 330, in main
> oxidized2   |     import_envvars(False, False)
> oxidized2   |   File "/sbin/my_init", line 90, in import_envvars
> oxidized2   |     for envfile in listdir("/etc/container_environment"):
> oxidized2   |   File "/sbin/my_init", line 74, in listdir
> oxidized2   |     return sorted(os.listdir(path))

Has anyone managed to run Oxidized in a container with a bind mounted volume?

Thank you.
