### ISSUE TITLE
Customize hooks for specific groups / models

### ISSUE THREAD

**Issue by falkenbe** [ytti/oxidized#2806]
Is it possible to customize hooks for specific groups or device types?  I have a working Oxidized setup with two hooks, one to push config changes to a github repo and one to email a diff of config changes.   I'd like to trigger the github repo hook for all devices, but not skip the email hook for a particular model of devices (F5 / tmos) since there are some dynamic elements in the config that change every few minutes.   It is useful to keep these elements in the config file so I don't want to mark them as secrets and mask them, I just want to skip the email hook for this model.  

I've tried setting the hook type and the hook events in the groups and models sections but it seems that groups and models don't override the hooks section.

This is my hooks definition
```yaml
hooks:
  push_to_git:
    type: githubrepo
    events: [post_store]
    remote_repo: https://git.example.com/oxidized.git
    username: username
    password: secret
  email_output:
    type: exec
    events: [post_store, node_fail]
    cmd: '/home/oxidized/extra/oxidized-report-git-commits -s "Oxidized updates for ${OX_NODE_NAME}" -r me@example.com'
    async: true
    timeout: 120
```

I've tried the following but all 4 attempts result in the email_output hook triggering on the post_store event and sending an email.   The devices in question are identified as a model of TMOS and are in the default group (` :group=>nil, :model=>"TMOS",` when viewing the node information with oxidized-web )

```yaml
models:
  tmos:
    email_output:
      type: noophook
      events: []
```
```yaml
models:
  tmos:
    hooks:
      email_output:
        type: noophook
        events: []
```
```yaml
# Disable the hook by default just to see if this works
groups:
  default:
    hooks:
      email_output:
        type: noophook
        events: []
```
```yaml
# Disable the hook by default just to see if this works
groups:
  default:
    email_output:
      type: noophook
      events: []
```

If possible, I'd like to do this in the Oxidized config, but if not I could always modify the oxidized-report-git-commits script locally to exit for certain devices.
