### ISSUE TITLE
I want to git push from Oxidized using a reverse proxy container, but it doesn't work.

### ISSUE THREAD

**Issue by naoamiiii** [ytti/oxidized#2843]
Hi,

In output:git/hook:githubrepo in Oxidized, it is not possible to git push via a proxy, so I'm thinking about using a reverse proxy container via a proxy.

I want to git push from Oxidized using a reverse proxy container, but it doesn't work.

config is set like this.
```
output:
  default: git
  git:
    user: user0001
    email: example.com
    single_repo: true
    repo: "/home/oxidized/.config/oxidized/"
hooks:
  push_to_remote:
    type: githubrepo
    events: [node success]
    remote_repo: "http://192.168.99.98:8887/"
    username: user001
    password: tokenpass001
``` 

The content of nginx.conf describes the forwarding URL as follows.
```
server {
    listen     8888 default_server:
    listen     [: :]:80 default_server:
    server _name _;
    root       /usr/share/nginx/html;

    # Load configuration files for the default server block.
    include /etc/nginx/default. d/*. conf;

    location/ {
    return 301 https://github.com/user0001/oxidized.git/$request_uri;
    }
``` 

In the nginx container, communication itself comes from the Oxidized container, and the following transfer log is output, but it seems that git push has failed on the Oxidized container side.

```
198.19.15.1 - - [27/Jun/2023:06:58:10 +0000] "GET /info/refs?service=git-upload-pack HITP/1.1" 301 169 "-" "git/2.0" (libgit2 1.6.3)" "-"
``` 

If anyone is working on a similar topic, please advise.
