### ISSUE TITLE
When running docker, git output repo "fatal dubious ownership in repo"

### ISSUE THREAD

**Issue by sliddjur** [ytti/oxidized#2855]
I run oxidized with the latest docker image.

```
docker image ls oxidized/oxidized:latest
REPOSITORY          TAG       IMAGE ID       CREATED        SIZE
oxidized/oxidized   latest    01882ed1baac   19 hours ago   1.07GB
```

My simple `docker-compose` config.

```
---
version: "3"
services:
  oxidized:
    restart: always
    image: oxidized/oxidized:latest
    ports:
      - 8888:8888/tcp
    environment:
      CONFIG_RELOAD_INTERVAL: 600
    volumes:
       - /opt/oxidized:/home/oxidized/.config/oxidized
```

And finally parts of my oxidized config:

```
output:
  default: git
  git:
    repo: "/home/oxidized/.config/oxidized/repos/"
    single_repo: false
```
Does the `repo` config stanza only take effect when I have `single_repo: true`? Because when set to `false`, all repos are put in oxidized root dir.
Now I tried both `single_repo` `true` and `false`, but I still have the issue when git repo is created. 
First of all, user and group ownership is always changed back to `30000`, and secondly, when issuing `git status`, I get this error:

```
/opt/oxidized/f5.git$ git status
fatal: detected dubious ownership in repository at '/opt/oxidized/f5.git'
To add an exception for this directory, call:

	git config --global --add safe.directory /opt/oxidized/f5.git
```

When running the command and restarting oxidized, I still get the same error.
