### ISSUE TITLE
Problems with credentials defined globally

### ISSUE THREAD

**Issue by anewadventure** [ytti/oxidized#2862]
Hello, I have a question regarding the configuration. I currently have the following config file located at `/etc/oxidized/config`:

```yaml
---
username: <username>
password: <password>
model: fortios
resolve_dns: true
interval: 10
use_syslog: false
debug: false
threads: 30
use_max_threads: false
timeout: 10
retries: -1
prompt: !ruby/regexp /^([\w.@-]+[#>]\s?)$/
rest: 127.0.0.1:8888
next_adds_job: false
vars: {}

groups:
  network_devices:
    models:
      fortios:
        username: <username>
        password: <password>

group_map: {}
models: {}

pid: "/etc/oxidized/pid"
crash:
  directory: "/etc/oxidized/crashes"
  hostnames: false

stats:
  history_size: 10

input:
  default: ssh, telnet
  debug: false
  ssh:
    secure: false
  ftp:
    passive: true
  utf8_encoded: true

output:
  default: git
  git:
    user: anewadventure
    email: 128881078+anewadventure@users.noreply.github.com
    repo: "/root/fortigate-backup/default.git"

source:
  default: csv
  csv:
    file: "/etc/oxidized/router.db"
    delimiter: !ruby/regexp /:/
    map:
      name: 0
      model: 1
    gpg: false

model_map:
  juniper: junos
  cisco: ios
```

Additionally, I have an `/etc/oxidized/router.db` file with the following entry:

```arduino
192.168.11.99:fortios:::
```

The issue I'm facing is that I need to define the `username` and `password` globally, which is not ideal since it's a bad practice to do so. I attempted to move the `username` and `password` inside `groups: models: fortios:` while omitting the global definition, but Oxidized couldn't successfully log in to my Fortigate device in that state. I'm aware that the syntax for the `router.db` file is `ip:model:username:password:enable_password`. However, even when I defined the `username` and `password` there, it didn't work unless they were defined globally.

The problem with using global definitions for `username` and `password` is that it's not recommended and becomes incompatible when dealing with multiple devices, each requiring different passwords.
