### ISSUE TITLE
GithubRepo push to remote not work after upgade gitlab to 16.3.4

### ISSUE THREAD

**Issue by Mascherus** [ytti/oxidized#2948]
Hello!
Oxidized can't push to remote repository after upgrade gitlab...
In log I can see:

if ruby 3.1:
```
2023-09-21T09:40:59.493989+07:00 tsk-oxi-01 oxidized[235849]: GithubRepo: to remote: git@git.local.net:oxidized/device_configs.git
2023-09-21T09:40:59.595370+07:00 tsk-oxi-01 oxidized[235849]: Hook push_to_remote (#<GithubRepo:0x00007f9b3d3a1fe7>) failed (#<Rugged::SshError: remote rejected authentication: Failed getting response>) for event :post_store

```
if ruby 2.7
```
Sep 20 17:17:17 tsk-oxi-01 oxidized[693]: GithubRepo: to remote: git@git.local.net:oxidized/device_configs.git
Sep 20 17:17:17 tsk-oxi-01 oxidized[693]: /var/lib/gems/2.7.0/gems/rugged-0.28.5/lib/rugged/repository.rb:258: warning: Using the last argument as keyword parameters is deprecated
Sep 20 17:17:17 tsk-oxi-01 oxidized[693]: Hook push_to_remote (#<GithubRepo:0x00006690915c4a90>) failed (#<Rugged::SshError: failed to start SSH session: Unable to exchange encryption keys>) for event :post_store
```

ssh with keys work fine:
```
oxidized@oxidized:~$ ssh -T git@git.local.net
Welcome to GitLab, @oxidized!
oxidized@oxidized:~$

```

**Comment by Mascherus** [comment]
Fixed.
This problem only appears on Debian with libssh2-1 1.10.0-3+b1
If you install the libssh package from Ubuntu (libssh2-1 1.11.0-2), everything works fine

**Comment by eoli3n** [comment]
This is not a fix, but a workaround

**Comment by rkerr** [comment]
I had a similar issue - there's quite a few variables here - gitlab can use OpenSSH or it's own built in ssh server depending on what you have configured, and there are lots of different key types you can use to authenticate for ssh.

What I found in my case was if oxidized is using an RSA key it was attempting to use the older ssh-rsa method (ie RSA with SHA1) but the gitlab end wouldn't accept that and only supports rsa-sha2-256 or rsa-sha2-512. OpenSSH deprecated ssh-rsa in version 8.8 so this should really be dependant on the OpenSSH version not the version of gitlab, but maybe you're running gitlab in a container and the gitlab update updated OpenSSH in the container? or maybe you're using gitlabs own ssh server (not the default).

I didn't dig too much further into what changed to break this. For me there was another easy work around - switching to an ED25519 key which is more secure than RSA anyway and doesn't have this issue.

**Comment by eoli3n** [comment]
please reopen

**Comment by robertcheramy** [comment]
Reopening this bug as a request from @eoli3n . This seems an upstream Problem from libssh2, so I'm not sure what we could do here...

**Comment by YellowJacket51** [comment]
Still having issues with this.

**Comment by eoli3n** [comment]
workaround:

```
hooks:
  push_to_remote:
    events: [post_store]
    #type: githubrepo
    #remote_repo: git@gitlab.domain.fr:username/oxidized-configs.git
    #publickey: /opt/oxidized/.ssh/id_rsa.pub
    #privatekey: /opt/oxidized/.ssh/id_rsa
    type: exec
    cmd: 'git --git-dir /opt/oxidized/oxidized.git remote add origin git@gitlab.domain.fr:username/oxidized-configs.git; git --git-dir /opt/oxidized/oxidized.git push origin master --force'
```
