### ISSUE TITLE
problem when you specify the ssh port

### ISSUE THREAD

**Issue by marmack95** [ytti/oxidized#3127]
Hello,
It's seems exist a problem when ssh_port is specified.

My list of device (i use groups to define username/password except for few devices):
```
#name:ip:port:model:group:input:username:password
device1:1.2.3.1::huawei:switch:ssh
device2:1.2.3.2:22:sonios:firewall:ssh
device3:1.2.3.3:22:fortinet:firewall:ssh:myser:mypassword
device4:1.2.3.4:12345:fortinet:firewall:ssh:myser:mypassword
```
My configuration file:
````
    map:
      name: 0
      ip: 1
      model: 3
      group: 4
      input: 5
      username: 6
      password: 7
    vars_map:
      ssh_port: 2
````
It only works for device4 which use a specific port.

After some test, i moved ssh_port to the end in my list of device.

list of device :
````
#name:ip:model:group:input:username:password:port
device1:1.2.3.1:huawei:switch:ssh
device2:1.2.3.2:sonios:firewall:ssh:::22
device3:1.2.3.3:fortinet:firewall:ssh:myser:mypassword:22
device4:1.2.3.4:fortinet:firewall:ssh:myser:mypassword:12345
````
configuration file:
````
    map:
      name: 0
      ip: 1
      model: 2
      group: 3
      input: 4
      username: 5
      password: 6
    vars_map:
      ssh_port: 7
````
It works after this change but not for device2 (but this is another problem).

Update: i solved the problem of device2, by using 'nil' as explain in documentation.
`device2:1.2.3.2:sonios:firewall:ssh:nil:nil:22`

NB: Oxidized 0.30.1 - Docker version
