### ISSUE TITLE
Rugged githubrepo unsupported URL Protocol

### ISSUE THREAD

**Issue by Atroskelis** [ytti/oxidized#3132]
gives a 

`Hook push_to_remote (#<GithubRepo:0x0000000001346b00>) failed (#<Rugged::NetworkError: unsupported URL protocol>) for event :post_store`

config is 

```
hooks:
  push_to_remote:
    type: githubrepo
    events: [post_store]
    remote_repo: git@<ip>:oxidized/<repo>.git
    publickey: /root/.ssh/id_rsa.pub
    privatekey: /root/.ssh/id_rsa
```

rugged has ssh installed, i thought that was the error
git push works ok
ruby 2.0.0p648 (2015-12-16) [x86_64-linux]
oxidized (0.22.0)
rugged (0.27.1)
