### ISSUE TITLE
undefined method 'url'

### ISSUE THREAD

**Issue by Dazza0311** [ytti/oxidized#3171]
I have installed oxidized on Ubuntu 22.04 server.

I followed the instructions as per GitHub
![oxidized](https://github.com/ytti/oxidized/assets/170534812/28acdcdf-3995-4af4-a3b0-29c9444e62d9)
 and the libre documentation, I have edited my config file to point to my LibreNMS server as the source.

The config file does not seem to have any issues, I only have this issue that keeps occurring when trying to start oxidized.

I have done a lot of research and it seems that the issue is in the http.rb config, I am just not sure as to how to fix it.

Any assistance would greatly be appreciated.

**Comment by yoakim** [comment]
Posting your config would be a great start, mask out sensitive parts.

**Comment by Dazza0311** [comment]
![config](https://github.com/ytti/oxidized/assets/170534812/7d086c73-843c-4b71-b1b3-6203205cfd41)

here we go

**Comment by yoakim** [comment]
Maybe your source section is indented wrong, this is my config:

`source:
  default: http
  http:
    url: URL
    scheme: http
    delimiter: !ruby/regexp /:/
    read_timeout: 120
    map:
      name: hostname
      ip: ip
      model: os
    vars_map:
      enable: enable`

**Comment by Dazza0311** [comment]
how does it connect to LibreNMS though without the Auth Token?

**Comment by yoakim** [comment]
Oh sorry, my example doesnt use any token in the header. I just ment you should try to fix the indents accordingly.
From URL and down, indent it one step

**Comment by Dazza0311** [comment]
Tried to edit it but still got the same error, this seems like an issue with Ruby to be honest. It's like it does not know how to handle the method for url

**Comment by yoakim** [comment]
I tried to reproduce it and was successful in doing so:
`oxidized_1  | /var/lib/gems/3.0.0/gems/oxidized-0.29.1/lib/oxidized/source/http.rb:9:in `setup': undefined method `url' for nil:NilClass (NoMethodError)`

This was when my indentation was wrong, when i fixed it, it worked.

My two scenarios:
Not working:
```
source:
  default: http
  http:
  url: $OXIDIZED_SRC_API_URL
  scheme: http
  delimiter: !ruby/regexp /:/
  read_timeout: 120
  map:
    name: hostname
    ip: ip
    model: os
  vars_map:
    enable: enable
```

Working:
```
source:
  default: http
  http:
    url: $OXIDIZED_SRC_API_URL
    scheme: http
    delimiter: !ruby/regexp /:/
    read_timeout: 120
    map:
      name: hostname
      ip: ip
      model: os
    vars_map:
      enable: enable
```
