### ISSUE TITLE
Fortigate config backup failing

### ISSUE THREAD

**Issue by LoveSkylark** [ytti/oxidized#3218]
I am trying to backup my FortiGate Firewalls and I keep getting the error:

│ W, [2024-07-05T11:01:20.253418 #33]  WARN -- : x.x.x.x raised Timeout::Error with msg "execution expired"     

I'm successfully backing up 100+ other devices from different vendors.
It is large config and it takes few minutes to scroll though the CLI if I run 'show | grep .' manually, I have seen previous posts about similar issues and Have tried those solutions.

I changed the global timeout to 600 and I have also tried:

```
models:
  fortios:
    timeout: 600
    vars:
      fullconfig: false
```

Problem is I see this time out error  1-2 minutes after the server has started so there is no chance that 10 minutes have passed.

This is how my config file looks like:

```
    model: cisco
    resolve_dns: true
    interval: 72000
    use_syslog: false
    threads: 30
    use_max_threads: false
    timeout: 600
    retries: 3
    prompt: !ruby/regexp /^([\w.@-]+[#>]\s?)$/
    rest: 0.0.0.0:8888
    next_adds_job: false
    vars: {}
    groups:
      core:
        username: xxxx
        password: yyyy
    models:
      fortios:
        timeout: 600
        vars:
          fullconfig: false
    model_map:
      juniper: junos
      cisco: ios
      cisco: iosxe
      mikrotik: routeros
      ubiquiti: airos
      fortigate: fortios
      fortiswitch: fortios
    pid: "/home/oxidized/.config/oxidized/pid"
    crash:
      directory: "/home/oxidized/.config/oxidized/crashes"
      hostnames: false
    stats:
      history_size: 10
    input:
      default: ssh, telnet
      ssh:
        secure: false
      ftp:
        passive: true
      utf8_encoded: true
    output:
      default: git
      git:
          user: Oxidized
          email: x@z.y
          repo: "/home/oxidized/.config/oxidized/configs"
    source:
      default: http
```

Any help/suggestion on what I may be doing wrong is greatly appreciated.
