### ISSUE TITLE
Cisco Switches configs not fully backedup

### ISSUE THREAD

**Issue by IASAH** [ytti/oxidized#3274]
I have Oxidized with Librenms installed via docker from [https://github.com/dcbell/librenms-oxidized_docker](url) and configured as followed

- Docker network both are in the same network librenms-oxidized_default with mapped Ports for both and Working
- In Librenms settings Poller both Port and Communities (priority) are configured.
- In API Created New API key for Oxidized and copied it to Config file.
- Then Librenms >> Global Settings>> External >> Oxidized is set and enabled like:
     Enable Oxidized support: Enabled
     URL to your Oxidized API: http://librenms_oxidized:8888
     Enable config versioning access: Enabled
     Enable the return of groups to Oxidized: Enabled
     Set the default group returned: False

     In (Variable Mapping) I added:
        os = ios        os < ios
        os = iosxe     os < ios
        os = iosxr      os < iosxr

- In the Config file I modified as followed
```yaml
---
username: [Switches Username]
password: [Switches Password]
model_map: {}
resolve_dns: true
interval: 3600
use_syslog: false
debug: false
run_once: false
threads: 30
use_max_threads: false
timeout: 60
retries: 3
prompt: !ruby/regexp /^([\w.@-]+[#>]\s?)$/
rest: 0.0.0.0:8888
next_adds_job: false
vars: {}
groups: {}
group_map: {}
models:
  cisco-telnet:
    username: read_only
    password: iamclever123
    vars:
      enable: true
    input:
     default: telnet
     debug: true
  aoscx:
    username: [None]
    password: [None]
  procurve:
    username: [None]
    password: [None]
pid: "/home/oxidized/.config/oxidized/pid"
crash:
  directory: "/home/oxidized/.config/oxidized/crashes"
  hostnames: false
stats:
  history_size: 10
input:
  default: ssh, telnet
  debug: false
  ssh:
    secure: false
  ftp:
    passive: true
  utf8_encoded: true
output:
  default: git
  file:
    directory: "/home/oxidized/.config/oxidized/configs"
  git:
    user: Oxidized
    email: o@example.com
    repo: "/home/oxidized/.config/oxidized/oxidized.git"
source:
  default: http
  debug: false
  http:
    insecure: true
    url: http://librenms:8000/api/v0/oxidized
    map:
      name: hostname
      model: os
      group: group
    headers:
      X-Auth-Token: [Token From My Librenms]
                                                         
```
the result I get in Librenms Oxidized Configuration is only information about the switches like hardware and software versions but no configuration included even in the Oxidized web GUI the same no configuration Can any one Help.
