### ISSUE TITLE
Netgear gs752tpp login failed

### ISSUE THREAD

**Issue by maggo1404** [ytti/oxidized#3287]
Hi,

The Netgera gs752tpp can not login via ssh or telnet

```
W, [2024-10-10T12:31:00.897841 #32]  WARN -- : 10.10.66.21 raised Oxidized::PromptUndetect with msg "
10sw011#  not matching configured prompt (?-mix:^(\([\w\s\-\+.]+\)\s?[#>])$)"
W, [2024-10-10T12:31:01.003170 #32]  WARN -- : default/10.10.66.21 status no_connection, retry attempt 1
W, [2024-10-10T12:31:32.886639 #32]  WARN -- : 10.10.66.21 raised Oxidized::PromptUndetect with msg "
10sw011#  not matching configured prompt (?-mix:^(\([\w\s\-\+.]+\)\s?[#>])$)"
W, [2024-10-10T12:31:33.034175 #32]  WARN -- : default/10.10.66.21 status no_connection, retry attempt 2
W, [2024-10-10T12:32:04.878503 #32]  WARN -- : 10.10.66.21 raised Oxidized::PromptUndetect with msg "
10sw011#  not matching configured prompt (?-mix:^(\([\w\s\-\+.]+\)\s?[#>])$)"
W, [2024-10-10T12:32:05.066164 #32]  WARN -- : default/10.10.66.21 status no_connection, retries exhausted, giving up
W, [2024-10-10T12:32:37.011976 #32]  WARN -- : 10.10.66.19 raised Oxidized::PromptUndetect with msg "
10sw009#  not matching configured prompt (?-mix:^(\([\w\s\-\+.]+\)\s?[#>])$)"
W, [2024-10-10T12:32:37.097067 #32]  WARN -- : netgeat60000/10.10.66.19 status no_connection, retry attempt 1
W, [2024-10-10T12:33:09.070512 #32]  WARN -- : 10.10.66.19 raised Oxidized::PromptUndetect with msg "
10sw009#  not matching configured prompt (?-mix:^(\([\w\s\-\+.]+\)\s?[#>])$)"
W, [2024-10-10T12:33:09.128707 #32]  WARN -- : netgeat60000/10.10.66.19 status no_connection, retry attempt 2
W, [2024-10-10T12:33:40.999111 #32]  WARN -- : 10.10.66.19 raised Oxidized::PromptUndetect with msg "
10sw009#  not matching configured prompt (?-mix:^(\([\w\s\-\+.]+\)\s?[#>])$)"
W, [2024-10-10T12:33:41.160125 #32]  WARN -- : netgeat60000/10.10.66.19 status no_connection, retries exhausted, giving up
```

The relevant config

```
models:
  netgear:
    username: admin
    password: password
    delay: 3
    prompt_wait: '#'
#    vars:
#      enable: true
#      telnet_port: 60000
vars:
  auth_methods: [ "none", "publickey", "password", "keyboard-interactive" ]
groups:
#  netgeat60000:
#    vars:
#      telnet_port: 60000
#      enable: true
#    input:
#      default: telnet
```

The ssh login:
```
login as: admin
Keyboard-interactive authentication prompts from server:
| Password:
End of keyboard-interactive prompts from server
10sw009#
```

The telnet login:
```
Username: admin
Password: *****
10sw009#
```
