### ISSUE TITLE
Oxidized unable to parse/search multiple tags in http api call from PRTG

### ISSUE THREAD

**Issue by MedicoreV8** [ytti/oxidized#3360]
I'm not a seasoned programmer, nor am I a linux engineer. I'm a network engineer with a goal, and I'm motivated.

We are running PRTG with a myriad of devices.
I'm running Oxidized and using the PRTG API to retrieve a list of devices containing certain tags like fortios, procurve, aoscx, etc.
(Since I believe this is the only way Oxidized is able to figure out the type of device and what script to use for logging in and making a backup?)

I've configured it according to the documentation, and that works. As long as I only have 1 tag per device.

```
source:
  default: http
  http:
    url: [Redacted]
    hosts_location: devices
    scheme: https
    secure: false
    map:
      name: device
      ip: host
      model: tags
      group: group
model_map:
  juniper: junos
  cisco: ios
  fortinet: fortios
  aoscx: aoscx
  procuve: procurve
  aossw: procurve
```

When I have more than 1 tag per device in PRTG the tag field in the API call is shown as a single string separated by spaces.

For example:

```
    {
      "device": "LAB-XXX-XXX-SW01",
      "device_raw": "LAB-XXX-XXX-SW01",
      "host": "xxx.xxx.xxx.xxx",
      "host_raw": "xxx.xxx.xxx.xxx",
      "tags": "procurve switch",
      "tags_raw": "procurve switch",
      "group": "LAB-Probe",
      "group_raw": "LAB-Probe"
    },
```

Oxidized then doesn't show the device in the webUI and is not contained in the backup.
I've seen someone (although commented out) use a ruby regex in the config file after model: tags.
(https://github.com/ytti/oxidized/issues/1999)

```
      model: tags !ruby/regexp /\bios|\bdnos|\bnxos|\bftos|\bfortios|\betherhaul|\bsonicos|\bairfiber/ig
```

I tried this, (added procurve to the regex ofcourse) and it doesn't work. all devices are added as Junos (default in the config file)

We use multiple tags for other automation tasks and right now I'd have to break them in order to automatically back-up devices with the correct model in oxidized.

Is there a way to use a regex? and so, what would be the right one to use?
