### ISSUE TITLE
Facing issues pushing to gitlab Oxidized switches congfiguration

### ISSUE THREAD

**Issue by ankitsinghvisen** [ytti/oxidized#3420]
Hello,
I'm facing an issue when attempting to push switch configurations to GitLab using Oxidized. The push seems to fail during the push step, but I can manually push the configuration to GitLab without issues. The problem only occurs when trying to push automatically through Oxidized.

Here are the details:

Oxidized version: 0.30.1
OS: Rocky Linux 9.5
GitLab Repo: SSH URL
I’ve configured the push in Oxidized with the following settings:

```
output:
  default: git
  git:
    user: <<username>>
    email: <<emailID>>
    repo: "/home/oxidized/switches-configuration.git"
    branch: main

hooks:
  push_to_remote:
    type: githubrepo
    events:
      - post_store
    remote_repo: GitLab URL   # SSH
    branch: main
    private_key: "/home/oxidized/.ssh/id_rsa"
    public_key: "/home/oxidized/.ssh/id_rsa.pub"
```
However, in Oxidized Logs, I get the following error:
```
GithubRepo: Pushing local repository(/home/oxidized/switches-configuration.git/)...
I, [2025-02-21T10:32:13.806240 #70261]  INFO -- : GithubRepo: to remote: GitLab URL   # SSH
E, [2025-02-21T10:32:13.807190 #70261] ERROR -- : Hook push_to_remote (#<GithubRepo:0x00007411c96436e8>) failed (#<Rugged::NetworkError: unsupported URL protocol>) for event :post_store
```
I've confirmed that SSH access is working fine, as I can push manually. The error message mentions unsupported URL protocol, which leads me to believe there might be an issue with the way the URL is being handled in the Oxidized configuration.

Has anyone encountered this issue or have suggestions on how to resolve it?
