### ISSUE TITLE
How to set per node password with prtg as source

### ISSUE THREAD

**Issue by juggler11** [ytti/oxidized#3426]
Hello all,

My previous post about this was closed but the answer didnt help me. I have prtg as source but some nodes have a different password then the group. How do i put this in the config file? When i set username and password per group that works but dont know how to do that for nodes.

this is part of my config:

```
groups:
  somegroup:
    username: user
    password: pwd
source:
  default: http
  http:
    url: https://10.10.10.10/api/table.json?content=devices&columns=device,host,tags,group&output=json&filter_tags=@tag(FortiOS,aoscx,procurve,aossw,comware)&filter_type=@sub(device)&sortby=name&apitoken=secret&filter_status=3&filter_status=4
    hosts_location: devices
    scheme: https
    secure: false
    map:
      name: device
      ip: host
      model: tags
      group: group
model_map:
  juniper: junos
  !ruby/regexp /cisco/i: ios
  !ruby/regexp /fortios/i: fortios
  !ruby/regexp /aoscx/i: aoscx
  !ruby/regexp /procurve/i: procurve
  !ruby/regexp /aossw/i: procurve
  !ruby/regexp /comware/i: comware
  aossw: procurve
```
