### ISSUE TITLE
ProCurve old firmwares

### ISSUE THREAD

**Issue by falkheiland** [ytti/oxidized#3466]
had issues to get configs from old pro curve devices, that i cannot update atm. in my old 0.25.x version i could get the configs still.

# config

```yml
...
vars:
  ...
  auth_methods:
    - none
    - password
    - publickey
...
source:
  default: csv
  csv:
    file: "/sources/router.db"
    delimiter: !ruby/regexp /:/
    map:
      ip: 0
      name: 1
      model: 2
      username: 3
      password: 4
    vars_map:
      ssh_kex: 5
      ssh_host_key: 6
      ssh_hmac: 7
      ssh_encryption: 8
```

# router.db

```csv
192.168.1.2:J9279A-V_11_52:procurve:manager::diffie-hellman-group1-sha1:ssh-rsa:hmac-sha1:3des-cbc
192.168.1.3:J8698A-K_16_02_0014:procurve:manager:<password>:diffie-hellman-group14-sha1:ssh-rsa:hmac-sha1:3des-cbc
```
