### ISSUE TITLE
File/Git output fails silently when using CSV group mapping in Docker on Windows (0.33.0, 0.32.1)

### ISSUE THREAD

**Issue by ZDM-JEAN** [ytti/oxidized#3499]
**Title:** File/Git output fails silently when using CSV `group` mapping in Docker on Windows (`0.33.0`, `0.32.1`)

**Description:**
When running Oxidized in a Docker container on Windows 11 using Docker Desktop (with --network host mode), and reading device information from a CSV file (router.db) with a mapping for the group attribute (`source.csv.map: { ..., group: 5 }`), Oxidized fails to write any configuration files to the mounted volume directory. This happens with both file and git output types, and regardless of the `output.file.group_dir` setting (true or false). The output directory remains empty.

The Web UI successfully displays the device list and their correct groups. Debug logs show `INFO -- : Configuration updated for GroupName/NodeName` messages, but no errors related to file writing or Git operations.

If the group mapping is removed from the `source.csv.map`, the file output works correctly (saving files to the root output directory).

**Environment:**

- **Oxidized version:** 0.33.0 and 0.32.1 (both tested)
- **Deployment:** Docker container (`oxidized/oxidized` image) on Docker Desktop on Windows 11
- **Docker Network:** `host` mode
- **Device Source:** CSV file (`source.csv`)
- **Output Type:** `file` and `git` (both tested)

**Steps to Reproduce:**

1. Deploy the `oxidized/oxidized` Docker container on Docker Desktop on Windows 11 using `--network host` mode and volume mounts for `config`, `router.db`, `logs`, and an empty output directory (e.g., mounted to `/home/oxidized/output` for `file` or `/home/oxidized/configs.git` for `git`).
2. Ensure the `router.db` file is a CSV with a column containing group names (ASCII, non-ASCII, or empty), mapped as `group: <column_index>` in `config`.
   Example `router.db` format:
   ```csv
   192.168.1.1:cisco:user:pass::Group1
   192.168.1.2:cisco:user:pass::分组二
   192.168.1.3:cisco:user:pass::  # No group
   ```
3. Configure `config` to use the `source.csv.map: { group: 5 }` setting for group mapping.
4. Set `output.default` to `file` or `git` and configure the relevant directory (`output.file.directory` or `output.git.repo`).
5. Start/Restart the container.
6. Wait for Oxidized to complete a backup cycle.

**Expected Behavior:**

Oxidized should write the fetched configuration files to the configured output directory/Git repository, potentially creating group subdirectories if `group_dir: true`. The Web UI should display the correct groups.

**Actual Behavior:**

- Oxidized successfully fetches configurations.
- The Web UI shows the correct groups.
- **However, no files are written to the output directory/Git repository. The output directory remains empty, and no file writing or Git-specific errors are shown in the debug logs.**

**Configuration:**

```yaml
output:
  default: file  # Or 'git'
  file:
    directory: /home/oxidized/.config/oxidized/output  # Mounted from D:\oxidized_config\output
    group_dir: false  # Setting true also fails

# With output.default: git
# output:
#   default: git
#   git:
#     user: Oxidized Backup
#     email: oxidized@yourcompany.local
#     repo: /home/oxidized/configs.git  # Mounted from D:\oxidized_config\git-repo

source:
  default: csv
  csv:
    file: "/home/oxidized/.config/oxidized/router.db"  # Mounted from D:\oxidized_config\router.db
    delimiter: !ruby/regexp /:/
    map:
      name: 0
      model: 1
      username: 2
      password: 3
      group: 5  # <--- Enabling this mapping causes the output failure
    vars_map:
      enable: 4

# group_map was also tested but did not resolve the issue.
```

**Logs:**
```bash
# Example log snippet showing config fetch and 'update' messages, but no output activity (like file writes or git commands)
# Logfile created on 2025-04-28 03:14:27 +0000 by logger.rb/v1.5.3
I, [2025-04-28T03:14:27.944011 #31]  INFO -- : Oxidized starting, running as pid 31
I, [2025-04-28T03:14:28.131412 #31]  INFO -- : lib/oxidized/nodes.rb: Loaded 19 nodes
D, [2025-04-28T03:14:28.304456 #31] DEBUG -- : lib/oxidized/core.rb: Starting the worker...
D, [2025-04-28T03:14:28.306565 #31] DEBUG -- : lib/oxidized/worker.rb: Added GroupName/172.xx.xx.xx to the job queue
# ... config fetching logs ...
D, [2025-04-28T03:14:31.496719 #31] DEBUG -- : lib/oxidized/job.rb: Config fetched for 172.20.1.104 at 2025-04-28 03:14:31 UTC
I, [2025-04-28T03:14:32.499097 #31]  INFO -- : Configuration updated for 1901/172.16.19.15
I, [2025-04-28T03:14:32.502416 #31]  INFO -- : Configuration updated for 中心/172.17.1.2
I, [2025-04-28T03:14:32.505109 #31]  INFO -- : Configuration updated for XinWenZhongXin/172.17.1.34
# ... similar updated messages for all fetched configs ...
D, [2025-04-28T03:14:59.590595 #31] DEBUG -- : lib/oxidized/worker.rb: Running :nodes_done hook
# No file writing or git command logs are present.
```

**Running environment:**
- **OS:** Docker Desktop on Windows 11 (via WSL2 or Hyper-V, standard Docker Desktop setup)
- **Oxidized version:** 0.33.0 (also tested 0.32.1, same issue)
- **Oxidized-web version:** Included with the standard `oxidized/oxidized` image.
- **Manufacturer model and software version:** Affected devices include various ZTE, H3C, Cisco IOS-XR, Cisco IOS, Juniper Junos, Raisecom, and a custom 'yotc' model. The issue appears independent of the specific device model.
- **Oxidized model name:** zteswitch, h3cswitch, iosxr, ios, junos, raisecom, yotc (issue not model-specific)

**Additional context:**
The issue is consistently triggered by the presence of the group mapping in `source.csv.map`. Disabling the group map allows file output to work (saving files to the root directory). This seems like a significant bug or incompatibility specific to Oxidized on Docker Desktop on Windows with the host network mode, affecting both file and git outputs silently.  
The `--privileged` flag on `docker run` was also tested without effect on this issue.

---
