### ISSUE TITLE
Output Types and Git Hooks

### ISSUE THREAD

**Issue by phoenix1589** [ytti/oxidized#3535]
- [X] I have read and understood [docs/Issues.md](https://github.com/ytti/oxidized/blob/master/docs/Issues.md).

**Describe the problem**
Creating a model with different output types (from https://github.com/ytti/oxidized/blob/master/docs/Outputs.md#output-types) gives me a local git repository in the folder `~/.config/oxidized/git-config/`.  My `default.git` is in this same folder.

I'd like to be able to use the `githubrepo` hook to push this new repo to a remote repo, but I can't find the correct configuration options to do so. I'm using `single_repo` so before the new type, I only have a single repo for everything.

**Expected behavior**
The existing default repo continues to be pushed, and the new repo is also pushed to a different remote repo.

**Configuration**
I've updated a model:
```
require 'oxidized/model/junos.rb'
class JunOS < Oxidized::Model
	using Refinements
	cmd 'show configuration | display xml' do |automate|
		automate.type = 'xml'
		automate
	end
end
```

My initial config (before any changes):
```
output:
  default: git
  git:
    user: oxidized
    email: <snip>
    single_repo: true
    repo: "~/.config/oxidized/git-config/default.git"
hooks:
  push_to_remote:
    type: githubrepo
    events: [post_store]
    remote_repo: https://x-token-auth:<snip>@bitbucket.org/<snip>/<repo-name>.git
```

I've attempted to update my hooks, as I'm using `single_repo` this doesn't feel right, but I couldn't find anything else to attempt:
```
hooks:
  push_to_remote:
    type: githubrepo
    events: [post_store]
    remote_repo:
        default: https://x-token-auth:<snip>@bitbucket.org/<snip>/<repo-name>.git
        xml: https://x-token-auth:<snip>@bitbucket.org/<snip>/<second-repo-name>.git
```

**Logs**
When attempting to convert remote_repo to a dictionary:
```
oxidized-1  | D, [2025-06-06T07:23:21.977085 #31] DEBUG -- : lib/oxidized/job.rb: Config fetched for BROUT01 at 2025-06-06 07:23:21 UTC
oxidized-1  | I, [2025-06-06T07:23:22.958892 #31]  INFO -- : Configuration updated for router/BROUT01
oxidized-1  | E, [2025-06-06T07:23:22.959792 #31] ERROR -- : GithubRepo: No repository defined for router/BROUT01
```
This is only referencing the 'default' config file. The new file in the new repo ends up with a name `router/BROUT01--show_configuration_|_display_xml` and that isn't reference anywhere (I can see it in the local repo).

**Running environment (please complete the following information):**

- OS: RHEL 8.10 / Docker 26.0.0 with the official docker image.
- oxidized version: 0.32.2

**Additional context**
