### ISSUE TITLE
Multiple Oxidized Instances, Multiple Branches via CI/CD, But Branch Isolation Not Working

### ISSUE THREAD

**Issue by Aprazor** [ytti/oxidized#3545]
- [x] I have read and understood [docs/Issues.md](https://github.com/ytti/oxidized/blob/master/docs/Issues.md).

**Problem**
I deploy multiple Oxidized instances (one per datacenter) via Concourse CI/CD.
Each pod is configured to push to a unique branch (e.g., dc11, dc2) in a shared GitHub repo using only the built-in githubrepo hook:
Despite this, device configs from multiple clusters still end up in the master branch, or files get deleted after a new cluster push.
I’ve removed all shell-based hooks, set unique branches per cluster, and verified device lists are unique.

**Expected behavior**
I expect the oxidized to create different branches on github and then push the config per branch

**Configuration**
```
output:
  default: git
  git:
    single_repo: true
    user: "Oxidized"
    email: "net@test.com"
    repo: "/home/oxidized/.config/oxidized/configs.git"
    branch: {{ .Values.git.remote_branch }}  # set per cluster in pipeline
hooks:
  push_to_remote:
    type: githubrepo
    events: [post_store]
    remote_repo: "https://github.com/myrepo/repo.git"
    username: "username"
    password: !file /pass.txt

```
