### ISSUE TITLE
Feauture Request: VyOS support

### ISSUE THREAD

**Issue by paszczus** [ytti/oxidized#372]
I know that this is currently not supported, but it is almost same config as EdgeOS.
So show configuration should work for VyOS same as for EdgeOS.

**Comment by ytti** [comment]
doesnt this work? https://github.com/ytti/oxidized/blob/master/lib/oxidized/model/vyatta.rb

**Comment by paszczus** [comment]
Ahh, i am using different port for SSH on that VyOS device than 22.
I have added:

groups:
  vyos:
    ssh_port: 1022

but still cannot get config and log is empty :(

**Comment by paszczus** [comment]
checking another way; removing comments ;)

**Comment by ytti** [comment]
I would advice against removing comments, there is absolutely no shame making mistakes. Other people who google etc, can find them most invaluable to explain their own predicament.

**Comment by paszczus** [comment]
I am using SSH for vyos on different port. How i can set it for a specified device/group?
I am trying:

```
  vyatta:
    ssh_port: 1022
```

but this seems to not work.

**Comment by ytti** [comment]
try:

```
groups:
  vyatta:
    vars:
      ssh_port: 1022
```

Or you can pass it from your source (sql, csv (router.db), http...)

**Comment by paszczus** [comment]
It looks like ssh_port is working fine now but i am unable to get config.
I don't see authorization failures or sucess at vyos for oxidized, but tcpdump is showing that there are connections from oxidized to vyos on 1022 port. Debug log is empty :(

**Comment by paszczus** [comment]
W, [2016-03-29T09:33:50.375666 #3813]  WARN -- : 172.16.254.254 raised Net::SSH::AuthenticationFailed with msg "Authentication failed for user oxidized@172.16.254.254"
W, [2016-03-29T09:33:51.225902 #3813]  WARN -- : 172.16.254.254 status no_connection, retry attempt 3

**Comment by ytti** [comment]
That seems like your username or password is wrong.

**Comment by paszczus** [comment]
Yeah, i have put another credentials to 'vars' instead of group. Now it`s ok, thank you!

**Comment by ytti** [comment]
You can put them in group too, but they must be under vars under group

```
groups:
  xyzzy:
    vars:
       var_name: var_value
```

**Comment by paszczus** [comment]
Yeah, now it`s OK like this:
```
groups:
  vyatta:
    username: oxidized
    password: foo.1
    vars:
      ssh_port: 1022

```
But before it was like this:

```
groups:
  vyatta:
    vars:
      ssh_port: 1022
      username: oxidized
      password: foo.1
```
