### ISSUE TITLE
Using Git groups with sqlite db

### ISSUE THREAD

**Issue by davama** [ytti/oxidized#394]
Hello 
Trying to follow the wiki and post found here [https://github.com/ytti/oxidized/issues/387](url) but i get some errors:

Error:
`Invalid value; config files can only store string, bool or int keys`

oxidized config looks like this:
```
_output:
  default: git
  git:
    user: config
    emeail: config@nwk.jwm2.net
    repo: /home/config/repository/TESTING/.git
source:
  default: sql
  sql:
    adapter: sqlite
    database: "/home/config/repository/amer-oxidized.db"
    table: devices
    map:
      name: name
      model: model
      group: group
      username: config
      password: <password>
    vars_map:
      enable: enable_
```

In the "TESTING" folder when i run "oxidized" a new repo group is created "USA-PAT-L1.git" but it crashes with the error shown at the beginning.

Anywhere i can look?

Thanks in advance.
-Dave
