### ISSUE TITLE
Nested Groups?

### ISSUE THREAD

**Issue by tdurack** [ytti/oxidized#396]
Does Oxidized support nested groups? Something like:

Country/Pop/Core
Country/Pop/Agg
Country/Pop/Access

Etc.

Thanks in advance!

Tim:>

**Comment by ytti** [comment]
Not right now, but this was recently brought up in recent ticket where user did this, and ended up getting configs in those directories but also in parent. 

I think this is useful and something we should support and it does not appear to be very complicated to support. But I won't have time to work on it any time soon.

**Comment by davama** [comment]
I believe i tried this using a file as output. It did create a folder for each group with the configs inside the folders. Now using git output and a repo for each group is created.

nested groups would be convenient.
can you point me to the right direction so i can take a stab at it?

Thanks

**Comment by ytti** [comment]
I guess output/git.rb output/file.rb etc. Split group by '/' and go from there.

**Comment by davama** [comment]
Folder within folder worked. So it looks like so
using git as output
`GROUP/subgroup{a,b,c}.git  
`

or with file as output: ( these are all flat files of course)
`GROUP/subgroup{a,b,c}/device{a,b,c}
`

I was attempting to combine the two but noticed that the last "default" takes precedence. in this instance the default output is a file.
```
output:
   default: git
   git:
    user: config
    email: config@nwk.jwm2.net
    repo: /home/config/repository/.git
   default: file
   file:
     directory: /home/config/repository/.
```

I was wondering is this is possible?
```
GROUP/subgroupa/deviceflatfile
GROUP/subgroupa/.git
```

So the output would be saved on a flat file and the git commit would monitor all the flat file devices.

Hope it makes sense.

Thanks
Dave

**Comment by davama** [comment]
Think i found a solution for this.

Noticed the hooks section and so i changed the config to this:

```
output:
   default: file
   file:
     directory: /home/config/repository/.
hooks:
   first_hook:
     type: exec
     events: [post_store]
     cmd: 'cd /home/config/repository/$OX_NODE_GROUP && git add --all . && git config user.name "config" && git config user.email "config@nwk.jwm2.net" && git commit --quiet -m "$OX_NODE_GROUP"'
     timeout: 10
```

So in the end i still have a visible flat device file which is monitored by git. 
Structure looks like so:

```
GROUP/subgroupa/deviceflatfile
GROUP/subgroupa/.git
```

May not be an elegant solution. 
What do you guys think? Any "oxidized like" solution? Multiple outputs?

Thanks
Dave

**Comment by ytti** [comment]
Multiple outputs would be easy to support, and I would accept PR for that. I also think the / as nested groups should be supported, so would accept PR for that too.

**Comment by reavenm** [comment]
hey @davama  I am trying to use your workaround but just getting file output, git is not working.
this is my config:
```
next_adds_job: false
vars: {}
groups: {}
models: {}
pid: "/home/administrator/.config/oxidized/pid"
input:
  default: ssh, telnet
  debug: false
  ssh:
    secure: false
output:
  default: file
  file:
    directory: "/home/administrator/.config/oxidized/repo"
  hooks:
    first_hook:
    type: exec
    events: [post_store]
    cmd: 'cd /home/administrator/.config/oxidized/repo/$OX_NODE_GROUP && git add --all . && git config user.name "administrator" && git config user.email "administrator@ubuntu.com" && git commit --quiet -m "$OX_NODE_GROUP"'
source:
  default: csv
  csv:
    file: "/home/administrator/.config/oxidized/router.db"
    delimiter: !ruby/regexp /:/
    map:
      name: 0
      ip: 1
      model: 2
      group: 3
      username: 4
      password: 5

```
another weird thing it doesn't respect my directory path, the group folder it getting created alongside of <repo>

**Comment by davama** [comment]
> git is not working.

installed? `/usr/bin/git` maybe

>another weird thing it doesn't respect my directory path, the group folder it getting created alongside of

So it gets created but here i assume `/home/administrator/.config/oxidized/`

Try `    directory: "/home/administrator/.config/oxidized/repo/."`

**Comment by reavenm** [comment]
I assumed it was installed because it was working when i tried to use git only, anyways i install it but still not working.
i add --global to git config user.name but no success and still create the files outside of the path i put in the config.
You didnt see anything wrong in the config I post?

**Comment by davama** [comment]
> still create the files outside of the path i put in the config.

Ah i think i know why. dont know if your  Groups use `/` cuz ours does. That's an accidental semi 'working' function https://github.com/ytti/oxidized/pull/654#issuecomment-271000463

At least for me to get the configs in the correct directory i had to have the config as so:
`     directory: /home/config/repository/dummydirecotry/.`
where dummydirectory is just a placeholder and it does not exist. All files are created under `repository` folder. I suspect that that's how we have to have it configured because we use `/` in our Groups but not sure really. https://github.com/ytti/oxidized/issues/594

> You didnt see anything wrong in the config I post?

Unfortunately nothing sticks out

Regarding `git` can you run the `cmd` successfully in the shell? Do you have a ~/.gitconfig file. You could run oxidized in the shell with `debug: true` in the global section of your config to see the behavior

**Comment by reavenm** [comment]
the dummy file works great to store the config in the intent folder but I cant make the git works.
I install git config user.name and email I event git init the repo folder but its like the config is not reading that part I cant even see anything in the syslog regarding git. when oxidized is ran it create the group inside repo and the config inside the group and thats it the log ends there , the hook is not running.

**Comment by davama** [comment]
Did you run in debug mode? See line after `log:` https://github.com/ytti/oxidized#advanced-configuration

output would look like so:
```
D, [2017-08-11T16:00:14.921309 #2991] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2017-08-11T16:00:15.487603 #2991] DEBUG -- : lib/oxidized/input/cli.rb Running pre_logout commands at W-F-R59-SW-1
D, [2017-08-11T16:00:15.487703 #2991] DEBUG -- : lib/oxidized/input/ssh.rb exit @ W-F-R59-SW-1 with expect: nil
D, [2017-08-11T16:00:15.487908 #2991] DEBUG -- : lib/oxidized/input/ssh.rb exit @ W-F-R59-SW-1 with expect: nil
D, [2017-08-11T16:00:15.921618 #2991] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2017-08-11T16:00:16.921960 #2991] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2017-08-11T16:00:17.922283 #2991] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2017-08-11T16:00:18.922590 #2991] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2017-08-11T16:00:19.922919 #2991] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2017-08-11T16:00:20.496365 #2991] DEBUG -- : lib/oxidized/node.rb: Oxidized::SSH ran for W-F-R59-SW-1 successfully
D, [2017-08-11T16:00:20.496494 #2991] DEBUG -- : lib/oxidized/job.rb: Config fetched for W-F-R59-SW-1 at 2017-08-11 20:00:20 UTC
I, [2017-08-11T16:00:20.930433 #2991]  INFO -- : Configuration updated for USA-WKL/FTTX/W-F-R59-SW-1/W-F-R59-SW-1
D, [2017-08-11T16:00:20.930742 #2991] DEBUG -- : Exec: Execute: "cd /home/config/repository/$OX_NODE_GROUP && git init && echo \"$OX_NODE_NAME commit\" > .git/description"
Initialized empty Git repository in /home/config/repository/USA-WKL/FTTX/W-F-R59-SW-1/.git/
D, [2017-08-11T16:00:20.942808 #2991] DEBUG -- : Exec: Execute: "cd /home/config/repository/$OX_NODE_GROUP && git add --all . && git config user.name \"config\" && git config user.email \"config@nwk.jwm2.net\" && git commit --quiet -m \"Updated by oxidized\""
D, [2017-08-11T16:00:20.959354 #2991] DEBUG -- : lib/oxidized/worker.rb: Jobs 0, Want: 1
D, [2017-08-11T16:00:21.959784 #2991] DEBUG -- : lib/oxidized/worker.rb: Jobs 0, Want: 1
D, [2017-08-11T16:00:22.960120 #2991] DEBUG -- : lib/oxidized/worker.rb: Jobs 0, Want: 1

```

Also my Group has the hostname in it. This is how i have the db:
`W-F-R59-SW-1|<ipaddress>|ciscosmb|USA-WKL/FTTX/W-F-R59-SW-1`
Which would `cd` into the device folder name which according to oxidize is a group. In that folder you find the device flat file with an `.git` directory which you update with the `hook` statement.

The `first_hook` is for new repositories and the `second_hook` is to update existing repos. Regardless one hook should pass execution whether old or new

**Comment by reavenm** [comment]
both hook are on [post_store] ?

**Comment by davama** [comment]
> both hook are on [post_store] ?

yes. there are only so many [Events](https://github.com/ytti/oxidized#events)

**Comment by reavenm** [comment]
I am seeing git in the debug now, believe it or not it was an indentation error  but still
```
D, [2017-08-11T13:43:16.669514 #1606] DEBUG -- : lib/oxidized/job.rb: Config fetched for TSTRT250 at 2017-08-11 20:43:16 UTC
I, [2017-08-11T13:43:17.056795 #1606]  INFO -- : Configuration updated for stores/TSTRT250
D, [2017-08-11T13:43:17.057514 #1606] DEBUG -- : Exec: Execute: " cd /home/administrator/.config/oxidized/repo/$OX_NODE_GROUP && git init && echo $OX_NODE_NAME commit > .git/description "
D, [2017-08-11T13:43:17.062801 #1606] DEBUG -- : Exec: Execute: " cd /home/administrator/.config/oxidized/repo/$OX_NODE_GROUP && git add --all . && git config user.name \"administrator\" && git config user.email \"administrator@ubuntu.com\" && git commit --quiet -m $OX_NODE_GROUP "
E, [2017-08-11T13:43:17.074112 #1606] ERROR -- : Exec: " cd /home/administrator/.config/oxidized/repo/$OX_NODE_GROUP && git add --all . && git config user.name \"administrator\" && git config user.email \"administrator@ubuntu.com\" && git commit --quiet -m $OX_NODE_GROUP " failed with exit value 1
E, [2017-08-11T13:43:17.076262 #1606] ERROR -- : Hook my_second_hook (#<Exec:0x000000012c8408>) failed (#<RuntimeError: " cd /home/administrator/.config/oxidized/repo/$OX_NODE_GROUP && git add --all . && git config user.name \"administrator\" && git config user.email \"administrator@ubuntu.com\" && git commit --quiet -m $OX_NODE_GROUP " failed with exit value 1>) for event :post_store
```

and my hooks
```
hooks:
  my_first_hook:
    type: exec
    events: [post_store]
    cmd: ' cd /home/administrator/.config/oxidized/repo/$OX_NODE_GROUP && git init && echo $OX_NODE_NAME commit > .git/description '
  my_second_hook:
    type: exec
    events: [post_store]
    cmd: ' cd /home/administrator/.config/oxidized/repo/$OX_NODE_GROUP && git add --all . && git config user.name "administrator" && git config user.email "administrator@ubuntu.com" && git commit --quiet -m $OX_NODE_GROUP '
```

**Comment by davama** [comment]
> believe it or not it was an indentation error but still

means you getting closer :)

my current hooks:
```
hooks:
   first_hook:
     type: exec
     events: [post_store]
     cmd: 'cd /home/config/repository/$OX_NODE_GROUP && git init && echo "$OX_NODE_NAME commit" > .git/description'
     timeout: 10
   second_hook:
     type: exec
     events: [post_store]
     cmd: 'cd /home/config/repository/$OX_NODE_GROUP && git add --all . && git config user.name "config" && git config user.email "config@nwk.jwm2.net" && git commit --quiet -m "Updated by oxidized"'
     timeout: 10
```

hope that helps
