### ISSUE TITLE
Multiple vendors(multiple passwords)

### ISSUE THREAD

**Issue by pedrosiqr** [ytti/oxidized#460]
Hi everyone is just a kid in linux world, so i would like to know if someone can help me.
I want to set multiple passwords to my devices(for each vendor group), but a dont know where i put this.
I tried to put a single device on router.db(_hostname:model:username:password:enable_password) but it doesn't worked.
If someone can help-me, i would greatly appreciate it!

Best regards!

**Comment by ytti** [comment]
login/password can be either in source (Router.db, sql, http), per group or global. Or  combination of thereof.

Maybe it would be best for you, to give group in router.db and then in config give each group unique user/password.

If you want each router.db line to have username/password/enable, then you need to make sure you map those variables to correct locations in config.
That is your router.db will work, if you've mapped it correctly. How you've mapped now, is unclear without seeing your configuration.

**Comment by ytti** [comment]
No worries. Our docs are not good. You'll need something like this

```
groups:
  somename:
    username: foo1
    password: bar1
    vars:
      enable: baz1
  anothername:
    username: foo2
    password: bar2
    vars:
      enable: baz2
source:
  csv:
    map:
       group: 3
```

This would map 3rd field in router.db to ```group``` and would defined per-group authentication.
