### ISSUE TITLE
Force Config Pull

### ISSUE THREAD

**Issue by davama** [ytti/oxidized#471]
Is it possible on an already running oxidized process to force oxidized to pull the config on a particular device?

Thanks
Dave

**Comment by laf** [comment]
You can call for the device to be backed up next in the Webui / api:

/node/next/default/myrtr.example.com is one example.

**Comment by davama** [comment]
Right!!
completely forgot.
Any CML way ?

**Comment by laf** [comment]
curl :)

**Comment by davama** [comment]
Ok, interestingly oxidzed webui/api says "link status" is red when it's actually alive and well. DNS is fine too. 
i clicked on "update" button and got this page:
```
Sinatra doesn’t know this ditty.


Try this:
# in webapp.rb
class Oxidized::API::WebApp
  get '/node/next/CAN/FTTX/CAN-A2-152-SW-5/CAN-A2-152-SW-5' do
    "Hello World"
  end
end
```
Dont know if it's timing out or what but we do have a few thousands of devices on this oxidized process, if that makes a difference. Running curl didn't help, unless doing it wrong:
`curl -k https://<ip-addr>:9002/node/next/CAN/FTTX/CAN-A2-152-SW-5/CAN-A2-152-SW-5`
This gave me the above 'sinatra' output but in html format.

Ran oxidized in debug mode with only that switch in the DB and it's timing out, interesting...
I increase the timeout to 30 and that worked.

But still couldnt get it to force pull

**Comment by laf** [comment]
We just hit:

`curl http://ip/node/next/HOSTNAME` which works for us.

Do your group names contain /'s? Running the latest version?

**Comment by davama** [comment]
yes to divide by groups.
and yes

**Comment by danilopopeye** [comment]
@davama can you post the `config` and the `router.db` line for this device?

**Comment by davama** [comment]
DB table name is "devices"
Table fields/columns: "name,model,group"
```
echo "select * from devices where Name like '%CAN-A2-152-SW-5%';" | sqlite3 repository/region-oxidized.db
```
which outputs:
` 
CAN-A2-152-SW-5|ciscosmb|CAN/FTTX/CAN-A2-152-SW-5
`

Config: (posting only what i think may be relevant, let me know if otherwise)
```
.....
output:
   default: file
   file:
     directory: /home/config/repository/.
.....
source:
  default: sql
  sql:
    adapter: sqlite
    database: "/home/config/repository/region-oxidized.db"
    table: devices
    map:
      name: name
      model: model
      group: group
    vars_map:
      enable: enable
....

```
