### ISSUE TITLE
Rest API JSON Output error

### ISSUE THREAD

**Issue by jbaker48** [ytti/oxidized#478]
Pretty useless with ruby but I'm having an issue getting oxidized speaking to a DB. I've setup oxidized to use http as a source which from what I gather works however it seems to have a problem with the response the server gives and how oxidized parses it? I've pretty much formatted the http response to be the exact same as librenms's api however I'm still running into issues.

Error:

```
no implicit conversion of String into Integer
/var/lib/gems/2.2.0/gems/oxidized-0.14.3/lib/oxidized/source/http.rb:42:in `[]': no implicit conversion of String into Integer (TypeError)
    from /var/lib/gems/2.2.0/gems/oxidized-0.14.3/lib/oxidized/source/http.rb:42:in `block (2 levels) in load'
    from /var/lib/gems/2.2.0/gems/asetus-0.3.0/lib/asetus/configstruct.rb:21:in `each'
    from /var/lib/gems/2.2.0/gems/asetus-0.3.0/lib/asetus/configstruct.rb:21:in `each'
    from /var/lib/gems/2.2.0/gems/oxidized-0.14.3/lib/oxidized/source/http.rb:41:in `block in load'
    from /var/lib/gems/2.2.0/gems/oxidized-0.14.3/lib/oxidized/source/http.rb:37:in `each'
    from /var/lib/gems/2.2.0/gems/oxidized-0.14.3/lib/oxidized/source/http.rb:37:in `load'
    from /var/lib/gems/2.2.0/gems/oxidized-0.14.3/lib/oxidized/nodes.rb:14:in `block in load'
    from /var/lib/gems/2.2.0/gems/oxidized-0.14.3/lib/oxidized/nodes.rb:110:in `synchronize'
    from /var/lib/gems/2.2.0/gems/oxidized-0.14.3/lib/oxidized/nodes.rb:110:in `with_lock'
    from /var/lib/gems/2.2.0/gems/oxidized-0.14.3/lib/oxidized/nodes.rb:10:in `load'
    from /var/lib/gems/2.2.0/gems/oxidized-0.14.3/lib/oxidized/nodes.rb:105:in `initialize'
    from /var/lib/gems/2.2.0/gems/oxidized-0.14.3/lib/oxidized/core.rb:14:in `new'
    from /var/lib/gems/2.2.0/gems/oxidized-0.14.3/lib/oxidized/core.rb:14:in `initialize'
    from /var/lib/gems/2.2.0/gems/oxidized-0.14.3/lib/oxidized/core.rb:4:in `new'
    from /var/lib/gems/2.2.0/gems/oxidized-0.14.3/lib/oxidized/core.rb:4:in `new'
    from /var/lib/gems/2.2.0/gems/oxidized-0.14.3/lib/oxidized/cli.rb:12:in `run'
    from /var/lib/gems/2.2.0/gems/oxidized-0.14.3/bin/oxidized:9:in `<top (required)>'
    from /usr/local/bin/oxidized:23:in `load'
    from /usr/local/bin/oxidized:23:in `<main>'
```

HTTP Response from DB:

```
curl -X GET http://db.local/all
[
    {
        "hostname": "testswt01",
        "os": "juniper",
        "group": "default"
    }
]
```

Oxidized Config:

``` yaml

---
username: abc
password: abc
model: junos
interval: 3600
log: "/home/abc/.config/oxidized/log"
debug: true
threads: 30
timeout: 20
retries: 3
prompt: !ruby/regexp /^([\w.@-]+[#>]\s?)$/
rest: 0.0.0.0:8888
vars: {}
groups: {}
input:
  default: ssh
  debug: true
  ssh:
    secure: false
output:
  default: git
  git:
    user: oxidized
    email: oxidized@abc.com
    repo: "/home/abc/oxidized-testing.git"
    single_repo: true
source:
  default: http
  debug: true
  http:
    url: http://db.local/all
    scheme: http
    delimiter: !ruby/regexp /:/
    map:
      name: hostname
      model: os
      group: group
    headers:
      Accept: 'application/json'
model_map:
  cisco: ios
  juniper: junos
```

**Comment by jbaker48** [comment]
So I've done a bit more digging since I first posted an have found I am getting a 401 Authentication error due to a Basic Authorization header being pased into the http request:

This string translates to:
#<Asetus::ConfigStruct:0x00000001fde5e8>:#<Asetus::ConfigStruct:0x00000001fde3b8>

curl -v -H "Authorization: Basic IzxBc2V0dXM6OkNvbmZpZ1N0cnVjdDoweDAwMDAwMDAxNDNlNDkwPjojPEFzZXR1czo6Q29uZmlnU3RydWN0OjB4MDAwMDAwMDE0M2UxYzA+" -H "Content-type:application/json" -X GET http://10.12.1.199:5984/sample_db/_design/lists/_list/tojson/all
* Hostname was NOT found in DNS cache
*   Trying 10.12.1.199...
* Connected to 10.12.1.199 (10.12.1.199) port 5984 (#0)
> GET /sample_db/_design/lists/_list/tojson/all HTTP/1.1
> User-Agent: curl/7.35.0
> Host: 10.12.1.199:5984
> Accept: */*
> Authorization: Basic IzxBc2V0dXM6OkNvbmZpZ1N0cnVjdDoweDAwMDAwMDAxNDNlNDkwPjojPEFzZXR1czo6Q29uZmlnU3RydWN0OjB4MDAwMDAwMDE0M2UxYzA+
> Content-type:application/json
> 
< HTTP/1.1 401 Unauthorized
< 
{"error":"unauthorized","reason":"Name or password is incorrect."}
* Connection #0 to host 10.12.1.199 left intact

**Comment by laf** [comment]
Basic auth is only sent if user + pass is specified in your config which it doesn't appear to be. However that curl command isn't hitting the same url (I realise you will have masked the hostname from the config) as your config (http://db.local/all vs http://10.12.1.199:5984/sample_db/_design/lists/_list/tojson/all)

**Comment by jbaker48** [comment]
Same box just  the un-shortened URL. Passing in a session cookie into the header seems to fixes the issue (while the session is valid).

**Comment by danilopopeye** [comment]
> Passing in a session cookie into the header seems to fix the issue (while the session is valid)

have you tried to supply the credentials in the oxidized config?

``` yaml
  http:
    url: http://db.local/all
    scheme: http
    user: username
    pass: password
```
