### ISSUE TITLE
Name and IP distinction

### ISSUE THREAD

**Issue by rverchere** [ytti/oxidized#481]
Hello,
I'm using the IP address in the router.db table as the name of the device.
Is it possible to have another name of the device (making the difference between the name, the IP and maybe an alias name)?

Thanks for your feedback,

Rémi

**Comment by danilopopeye** [comment]
Using the hostname in the router.db didn't work for you? In the interface, if you're using it, you can view both.
![captura_de_tela_062416_111742_am](https://cloud.githubusercontent.com/assets/27297/16340232/45612de4-39fd-11e6-84e8-45e40a8da086.jpg)

**Comment by rverchere** [comment]
Yes I can have the IP plus hostname, but only for routers that have a DNS entry.

**Comment by danilopopeye** [comment]
> but only for routers that have a DNS entry.

can't you give them a name and put it on `/etc/hosts` ?

**Comment by shailigum** [comment]
add the variable `ip` under var_map in the config.

then in router.db give the device an arbitrary hostname (whatever you want it to appear as) and if un-resolvable it'll instead use whatever is in the IP field to try and reach your device.

**Comment by danilopopeye** [comment]
ping @rverchere

**Comment by ytti** [comment]
closed due to inactivity, @rverchere please reopen if needed

**Comment by rverchere** [comment]
Hello,

Sorry for the late feedback, but it does not work.

* `router.db`:
```
my-switch:powerconnect:admin:passwd:192.168.1.250
```
* `config`:
```
source:
  default: csv
  csv:
    file: "/var/lib/oxidized/.config/oxidized/router.db"
    delimiter: !ruby/regexp /:/
    map:
      name: 0
      model: 1
      username: 2
      password: 3
    var_map:
      ip: 4
```

In log file I have the following when I start the application:
```
ERROR -- : node {:name=>"my-switch", :model=>"powerconnect", :username=>"admin", :password=>"passwd"} is not resolvable, raised Resolv::ResolvError with message 'no address for sw-virt-1'
```

I'm using oxidized v0.14.3
