### ISSUE TITLE
In source how to differentiate not set, set with no value, set with value?

### ISSUE THREAD

**Issue by ytti** [ytti/oxidized#500]
@ElvinEfendi @danilopopeye 

I'd like your input. Consider variable 'enable', user might want

  1. not have it set, enable not given to device
  2. have it set, with no value => we expect normal prompt after 'enable' is issued
  3. have it set, with value => we expect password prompt after 'enable' is issued

Should this be different in SQL, HTTP, CSV?

Currently as far as I can see, we don't support case 2, either it is set with value or it is not set.

**Comment by ytti** [comment]
I'm thinking perhaps in . SQL, HTTP expect backend to deliver nil/false/true types, and remove the code which makes empty a nil.

In CSV, I'm thinking perhaps add pseudotypes, like __nil__, __false__ and __true__ strings which map to the types, and remove code which makes empty a nil.

May break backwards, but YOLO, we're at version 0.

**Comment by danilopopeye** [comment]
lets say we have the config:

``` yaml
source:
  default: csv
  csv:
    file: /var/lib/oxidized/router.db
    delimiter: !ruby/regexp /:/
    map:
      name: 0
      model: 1
      username: 2
      password: 3
    vars_map:
      enable: 4
```

Then in the `router.db` we could configure with your example above:

``` csv
first:ios:user:pass #1
first:ios:user:pass:false #2
first:ios:user:pass:true #3-1
first:ios:user:pass:password #3-2
```

It's not super intuitive, but if we document it... I don't like it, but it was be first thing that comes to mind!
