### ISSUE TITLE
When groups are defined Group directory is not created in configs directory

### ISSUE THREAD

**Issue by Alexanderis** [ytti/oxidized#594]
```
output:
   default: file
   file:
     directory: /etc/oxidized/configs
```
I have custom groups specified in the router.db file. Instead of creating the folders under /etc/oxidized/configs it creates them under /etc/oxidized/.

Changed oxidized-0.16.3/lib/oxidized/output/file.rb from 
```
    if opt[:group]
      file = File.join File.dirname(file), opt[:group]
    end
```
to 

```
    if opt[:group]
      file = File.join file, opt[:group]
    end

```
and it looks like its creating folders correctly under  /etc/oxidized/configs
