### ISSUE TITLE
Enable password in group support

### ISSUE THREAD

**Issue by NerdBlender** [ytti/oxidized#623]
Hi, 

Is it currently possible to specify an enable password under a group name? My groups are being passed though via librenms.

I have the global enable var specified, but I have some devices that either don't require it, or use a different one. I was trying this:

> 
vars:
  enable: enable1
groups:
  Switches:
   username: user
   password: password
  ASA:
   username: user
   password: password2
   enable: false
  OtherSwitches:
   enable: s3cret

Should this work?

**Comment by ytti** [comment]
Close. 

```
groups:
  ASA:
    vars:
      enable: false
  OtherSwitches:
    vars:
      enable: s3cret
```
