### ISSUE TITLE
multiple inputs

### ISSUE THREAD

**Issue by mattttv** [ytti/oxidized#625]
Hello Guys!
Firstly: thanks ytti and other supporters for this software :)

Just to make sure - it is not possible to have multiple input csv sources, right? As far as I can see only the last config file is used. I would need multiple inputs due to the fact that the config files are in a hierarchical structure.
Anyway don't you think it would be a good idea if the (debug-) output shows which config file is read. The only thing that is logged is how many nodes were loaded.

If someone could verify that mutliple configs are not possibe I would be very thankful.
Kind Regards,
Matthias

**Comment by ytti** [comment]
I'm trying to follow your question, but struggling. I fully agree that multiple CSV sources makes sense and I think we should support that, I'll get back to that later. 

You say 'you need multiple inputs due to the facts that config files are in a hierarchical structure'. I do not understand what you mean by this, can you try to reword or elaborate on it?


To the main question, how do you think multiple CSV files should optimally work? Would best be, that if config is detected to be a directory, we treat all files in that directory as CSV sources? If it's not detected to be a directory, business as usual?
Does it need to be recursive, or is it enough to be single depth?

So if you do
```
source:
  cvs:
    file: ~/.config/oxidized/routerdb.d
```

It would read all files in that directory?

Or should we rather introduce ```directory``` stanza, which overrides ```file``` stanza? From UX POV maybe new stanza is better, even though technically directory is a file, and there is nothing wrong the first example either.

I don't feel strongly, about either of these, best would be to go by your use-case, what would be best for the guy with the actual real-life requirement for this.

**Comment by rfdrake** [comment]
Maybe support a YAML array for source, so you could do:

```
source:
   - csv:
        file: ~/.config/oxidized/routerdb
   - csv:
        file: ~/.config/oxidized/routerdb2
```

Then they could use duplicate sources and as many as they like.  It might be nice to have an "output" flag for the source so you could say:

```
source:
   - csv:
        file:  ~/.config/oxidized/routers_in_europe.csv
        output: europe
output:
    europe:
        repo: /oxidized/routers_in_europe.git
```

**Comment by ytti** [comment]
Groups allow you to put files in different git repo, so that does not seem like priority.

Why I'm thinking of just loading all files in given directory, instead of manual config, is that I could imagine use-case where you can't know what files you'll generate, as you'll use some variable as file name. 
Would supporting directory work for you? That it loads all files in given directory? I think it might cover more potential use cases.

**Comment by jgroom33** [comment]
#685 duplicate

**Comment by jwgitprof** [comment]
I'd like to bump that this feature would really simplify things for us. We'd like to use multiple Librenms instances like the fellow in #685 .

**Comment by laf** [comment]
You could just write some middleware to combine multiple api sources.

**Comment by mattttv** [comment]
hi ytti! sorry that I overlooked this issue.
We did not use multiple inputs after all - we merged them by hand into one file.

But the original usecase was that we had multiple folders which were structured in different ways - for example
D groupa:
 - F inputfile1.csv
D groupb:
 - F inputfile2.csv
 - D groupb1
   -> F inputfile3.csv
D groupc:
 - F inputfile3.csv

I think all the proposed solutions would be fine. But I think it would be best to use a new stanza directory so that it is clear that a directory is scanned and go through all directories and search for *.csv - files. Maybe this is overkill and we would rather fall back to reading in every file on a single directory on one level.

Kind Regards,
Matt

**Comment by NoifP** [comment]
> Or should we rather introduce directory stanza, which overrides file stanza? From UX POV maybe new stanza is better.

Multiple inputs would be great! I think the directory stanza is the way to go!

**Comment by ytti** [comment]
I'm not opposed to this, it's not complex thing to add, I'm not seeing myself adding it at any rate any time soon.

Generally I feel Oxidized should not have any manually updated source-of-truth of devices, that the list of devices should from some database consumed by your entire infrastructure, and Oxidized should just have facilities to access that with what ever tooling is appropriate.

Current we support direct SQL queries and HTTP JSON API queries for source-of-truth, so yeah flat router.db files are bit of an antipattern, which reduces my desire to help people do things more comfortably wrong. 

Again having said that, I'm not against that, just I'm not doing it myself.

**Comment by DYoung7** [comment]
As a possible use case, I have a database that is the source-of-truth.  Some of the devices are in a lab and have a different username/password than the production devices.  I would like to do a database pull for the lab devices and be able to put them in a "lab" group and assign the appropriate username and password.  All the other devices would be in a "production" group and use a different username and password.
It seems like this could be done with a SQL query, but that would need one query for the "lab" and one for the "production".  Your current support of direct SQL queries is great, but if the database does not group the devices, multiple sources could.

**Comment by freedomwarrior** [comment]
Hello!
So, does oxidized support multiple sources?

**Comment by lucdnb** [comment]
> Hello!
> So, does oxidized support multiple sources?
UP! Anything?

**Comment by penfold1972** [comment]
I too will ask for some clarification. I read this thread as the original request was to have multiple sources... like maybe I have a CSV file of some old legacy equipment, so a static file is just fine for that "source", but then I might have another source that pulls a CSV that is generated for a lab. it's dynamic enough to be a generated file, from a lab source of truth, and doesn't have the same passwords/requirements as production. Meanwhile, production might be a database or API source of truth and maybe needs an email for every backup that fails.

But it sounds like this morphed into adding a low priority directory source that will load several files to use as sources... which isn't exactly what I thought was the original request, thus my confusion.

Which leads to me asking the same question as freedomwarrior and lucdnb on weather Oxidized supports multiple sources of devices to backup?

**Comment by alexeyhuc** [comment]
Hi! Regarding multiple sources, in my case, I want to have two db files, as one of them will contain a map that includes authentication passwords; the second source is for devices that have ssh-key authentication. This is the only way that comes to my mind to have both authentication schemes. 

Have you guys had this issue? Is there another way to have both authentication schemes?

For your reference, I'd like to have these sources with their maps:

```
source:
  default: csv
  csv:
    file: /opt/oxidized/.config/oxidized/router1.db
    delimiter: !ruby/regexp /:/
    map:
      name: 0
      model: 1
      username: 2
      password: 3
      group: 4

source:
  default: csv
  csv:
    file: /opt/oxidized/.config/oxidized/router2.db
    delimiter: !ruby/regexp /:/
    map:
      name: 0
      model: 1
      username: 2
      group: 3
```
Ps. ofc, I defined for router2, a group that includes publickey.

**Comment by chinow12** [comment]
Hi, I'm also trying to manage several different sources:

I coupled oxidized to librenms, I picked up the nodes via API but I have some equipment that has to use different credentials, and so I would have liked to retrieve them in a csv file, so I had thought of something like this:

```
source:
  csv:
    file: /home/oxidized/.config/oxidized/local_devices.csv
    delimiter: !ruby/regexp /,/
    map:
      name: 0
      model: 1
      username: 2
      password: 3
      ip: 4
  http:
    url: https://librenms.local/api/v0/oxidized
    headers:
      X-Auth-Token: 1d73fabef8a44f5714b585cf0xxxxx
    map:
      name: hostname
      model: os
      ip: ip

``` 

but it does not take the blocks into account if I do not pass it on default and in this case it only manages the source indicated in the defect, in fact normal.

Has anyone ever managed to get two sources?
