### ISSUE TITLE
githubrepo fails to fetch_and_merge_remote on node_success

### ISSUE THREAD

**Issue by dowlingw** [ytti/oxidized#631]
**What happens**
When using the `git` output and `githubrepo` hook: If `githubrepo` is triggered from the `node_success` hook and the directory does not exist, an error is logged.

```
E, [2016-12-06T15:07:40.995492 #30746] ERROR -- : Hook kekepush (#<GithubRepo:0x00000001b91df0>) failed (#<Rugged::OSError: Failed to resolve path '/opt/oxidized/configs.git': No such file or directory>) for event :node_success
```

In the case where the files being generated are already present on the remote, this means that future `post_store` events will fail the call to `fetch_and_merge_remote` and be unable to push new configurations to the remote (because the `git` output plugin will implicitly create a new empty repository with a different history).

This is relevant in the case that Oxidized is moved to a new server or the server is rebuilt.

**Expected Behaviour**
When using the `git` output and `githubrepo` hook: If `githubrepo` is triggered from the `node_success` hook and the directory does not exist, *the `githubrepo` hook should clone the remote repository locally*.

**Environment**
Oxidized: 0.18.0
Ruby: 2.0.0p384

```
output:
  default: git
  git:
    single_repo: true
    user: confcollector
    email: devops@REMOVED
    repo: /opt/oxidized/configs.git
hooks:
  remote:
    type: githubrepo
    events: [node_success,post_store]
    remote_repo: REMOVED
    publickey: /opt/oxidized/id_rsa.pub
    privatekey: /opt/oxidized/id_rsa
```
