### ISSUE TITLE
Group Authentication Not Working

### ISSUE THREAD

**Issue by mattschwen** [ytti/oxidized#646]
I cannot seem to get group authentication to work. I have removed the default username and password at the top of the config file and have added the following:

```

groups:
  juniper:
    username: xxxxxxxxxx
    password: xxxxxxxxxx
  cisco:
    username: xxxxxxxxxx
    password: xxxxxxxxxx
  cumulus:
    username: oxidized
    publickey: /home/oxidized/.ssh/id_rsa.pub
    privatekey: /home/oxidized/.ssh/id_rsa
  brocade:
    username: xxxxxxxxxx
    password: xxxxxxxxxx
  vyatta:
    username: xxxxxxxxxx
    password: xxxxxxxxxx
```

```
source:
  default: csv
  csv:
    file: /home/oxidized/.config/oxidized/router.db
    delimiter: !ruby/regexp /:/
    map:
      name: 0
      model: 1
      group: 2

```
I get the following error message:

```
Puma 2.16.0 starting...
* Min threads: 0, max threads: 16
* Environment: development
* Listening on tcp://127.0.0.1:8888
W, [2016-12-20T19:05:43.400396 #2190]  WARN -- : 10.4.3.4 raised Net::SSH::AuthenticationFailed with msg "Authentication failed for user username@10.4.3.4"
W, [2016-12-20T19:05:43.593057 #2190]  WARN -- : lndoffesw01.corp.alianza.com status no_connection, retry attempt 1

```
It is attempting to use the username of username. Which I assume is default since it is not noticing any username. 

I also wondered if SSH Key based authentication works instead of passwords.

**Comment by ytti** [comment]
Which Oxidized version are you running, this was added very very recently. SSH key auth works, it either uses keys as defined in openssh config, or if you set variables. The config you have is not correct config for SSH auth.

**Comment by mattschwen** [comment]
I am running 0.18.0

**Comment by ytti** [comment]
Ok that should support specifying auth details in group. What does it say when you run it with ```-d``` it should tell about username/password resolution.

**Comment by mattschwen** [comment]
I got group authentication working by specifying the map and adding the group to the end of my hosts in router.db.

Now for ssh, would my config look like this? This is assuming only cumulus is using key based auth and nobody else is. 

```
groups:
  juniper:
    username: rancid
    password: password
  cisco:
    username: rancid
    password: password
  cumulus:
    username: oxidized
  brocade:
    username: rancid
    password: password
  vyatta:
    username: rancid
    password: password
```

/etc/ssh/ssh_config

I just commented out:

```
#   StrictHostKeyChecking ask
#   IdentityFile ~/.ssh/identity
   IdentityFile ~/.ssh/id_rsa
```
