### ISSUE TITLE
tinytds all results nil

### ISSUE THREAD

**Issue by kunwon1** [ytti/oxidized#647]
Using tinytds sequel adapter after modifying sql.rb (detailed below), getting 'source returns no usable nodes' when I know there is data there. Wondering how I can dig deeper into this problem.

I get hundreds of these errors:
`E, [2016-12-20T21:38:30.069826 #25063] ERROR -- : node {:name=>nil, :model=>nil, :username=>nil, :password=>nil} is not resolvable, raised ArgumentError with message 'cannot interpret as DNS name: nil'`

This is after I added another rescue statement to catch this ArgumentError:

```
 Oxidized.mgr.source[@source].new.load.each do |node|
          # we want to load specific node(s), not all of them
          next unless node_want? node_want, node
          begin
            _node = Node.new node
            new.push _node
          rescue ModelNotFound => err
            Oxidized.logger.error "node %s raised %s with message '%s'" % [node, err.class, err.message]
          rescue Resolv::ResolvError => err
            Oxidized.logger.error "node %s is not resolvable, raised %s with message '%s'" % [node, err.class, err.message]
          rescue ArgumentError => err
            Oxidized.logger.error "node %s is not resolvable, raised %s with message '%s'" % [node, err.class, err.message]
          end
        end
```

i have modified sql.rb for tinytds:

```
    Sequel.connect(:adapter  => @cfg.adapter,
                   :dataserver => @cfg.dataserver?,
                   :tds_version => @cfg.tds_version?,
                   :encoding => @cfg.encoding?,
                   :host     => @cfg.host?,
                   :user     => @cfg.user?,
                   :password => @cfg.password?,
                   :database => @cfg.database)
```

I have this source config:

```
source:
  default: sql
  sql:
    adapter: tinytds
    database: device
    table: Devices
    user: user
    password: password
    host: 172.16.0.1
    tds_version: 7.3
    encoding: ISO-8859-1
    login_timeout: 5
    timeout: 40
    map:
      name: Field23
      model: DeviceType
      username: Field24
      password: Field25
  vars_map:
    enable: Field26


```
