### ISSUE TITLE
source http map: Support nested keys

### ISSUE THREAD

**Issue by jgroom33** [ytti/oxidized#695]
Currently, keys must exist at the top level of the http response

https://github.com/chengguangnan/vine

The above gem would allow nested object access such as:

```yaml
source:
  default: http
  http:
    url: https://url/api
    scheme: https
    delimiter: !ruby/regexp /:/
    user: username
    pass: password
    map:
      name: properties.hostname
      model: properties.os
      username: properties.credentials.username
      password: properties.credentials.password
```

**Comment by ytti** [comment]
I'm bit confused. Can you explain how things are now, now they would be ideally and how would the change be useful.

**Comment by jgroom33** [comment]
## current behavior

http source response data

```json
{"hostname":"1.1.1.1",
   "os":"cisco",
    "username":"cisco",
     "password":"pays"
}
```

configuration

```yml
source:
  default: http
  http:
    url: https://url/api
    scheme: https
    delimiter: !ruby/regexp /:/
    user: username
    pass: password
    map:
      name: hostname
      model: os
      username: username
      password: password
```

## desired behavior

http source response data

```json
{ 
   "properties":{
      "hostname":"1.1.1.1",
      "os":"cisco",
      "credentials":{
          "username":"cisco",
          "password":"pays"
      }
   }
}
```

configuration

```yml
source:
  default: http
  http:
    url: https://url/api
    scheme: https
    delimiter: !ruby/regexp /:/
    user: username
    pass: password
    map:
      name: properties.hostname
      model: properties.os
      username: properties.credentials.username
      password: properties.credentials.password
```
