### ISSUE TITLE
Username and Password

### ISSUE THREAD

**Issue by drobert31** [ytti/oxidized#706]
Hi,

I would like to use by default username and password from the router.db file or sql and if no username or password is set then use those defined in group.

Extract from config file 

```
groups:
  Cisco:
   username: cisco
   password: cisco
  Brocade:
   username: admin
   password: password

source:
  default: sql
  sql:
    adapter: mysql2
    database: my_oxidized
    table: machines
    username: toto
    password: toto
    map:
      name: nom
      ip: ip
      model: modele
      group: groupe
      username: username
      password: password
```

regards,
DR
