### ISSUE TITLE
http source uses basic auth even if no user and password set

### ISSUE THREAD

**Issue by matejv** [ytti/oxidized#720]
I was just testing oxidized and ran into an issue with the http source.

Even if I didn't set the user and pass options in the config for http input, oxidized still sent out a HTTP GET request with the Authorization header set.

So this gets sent out as if user and pass are set:

```
source:
  default: http
  http:
    url: http://url/api
    map:
      name: hostname
      model: os
```

If I set user to false, it worked fine:
```
source:
  default: http
  http:
    url: http://url/api
    user: false
    map:
      name: hostname
      model: os
```
