### ISSUE TITLE
Slack diff notification issue

### ISSUE THREAD

**Issue by ninoabbate** [ytti/oxidized#790]
I setup a custom bot user in my Slack team and invited it to the channel where it needs to send the notifications.
I've configured the hook as described in README
```
hooks:
  slack:
    type: slackdiff
    events: [post_store]
    token: ....
    channel: "#..."

```
But it doesn't work:
```
I, [2017-03-31T10:32:18.912827 #18]  INFO -- : SlackDiff: Connecting to slack
I, [2017-03-31T10:32:19.278022 #18]  INFO -- : SlackDiff: Connected
I, [2017-03-31T10:32:19.278540 #18]  INFO -- : SlackDiff: Posting diff as snippet to #....
E, [2017-03-31T10:32:19.278686 #18] ERROR -- : Hook slack (#<SlackDiff:0x000000014d8090>) failed (#<TypeError: no implicit conversion of Symbol into Integer>) for event :post_store
```
Note: I've removed the token and channel.
I'm running oxidized in a docker container.
