### ISSUE TITLE
Group mapping sql

### ISSUE THREAD

**Issue by matthewmdn** [ytti/oxidized#797]
Trying to map a group column in the mySQL source. I wasn't able to use group as it is used in mySQL internally. I added a column in my table called **dev_group**. 

I get this error 

> oxidized: undefined method `has_key?' for nil:NilClass

This is my conf section

```
source:
  default: sql
  sql:
    adapter: mysql2
    database: oxidized
    table: nodes
    username: scrubbed-user
    password: scrubbed-pass
    map:
      name: name
      model: model
      username: username
      password: password
      group: dev_group
    vars_map:
      enable: enable
    model_map:
      cisco: ios
      cisco-nx: nxos
      hp: procurve
      paloalto: panos
      opengear: opengear
```
If I just remove the group map the nodes get loaded into the default group
