### ISSUE TITLE
Change notification

### ISSUE THREAD

**Issue by goro22052** [ytti/oxidized#888]
How to configure a network configuration change notification?

**Comment by laf** [comment]
Have a look here: https://github.com/ytti/oxidized/issues/516

**Comment by goro22052** [comment]
I do not need to change the author.
I only need to send a mail notification about the configuration change.

**Comment by laf** [comment]
Sorry I mis-understood what you wanted. However you really should look existing open and closed issues as both of these have been asked an answered before. A search for 'email' led me to: https://github.com/ytti/oxidized/pull/278/files

**Comment by goro22052** [comment]
It's more like what I'm looking for.
But I do not understand how to use it.

**Comment by laf** [comment]
That contains the examples to use:

```
 hooks:
  email_output:
    type: exec
    events: [post_store, node_fail]
    cmd: '/home/oxidized/extra/oxidized-report-git-commits ~/gitdir/ | mail -s "Oxidized updates for ${OX_NODE_NAME}" update-recipient@example.com'
    async: true
    timeout: 120
```

Change what you need in that.
