### ISSUE TITLE
Oxidized + git = crash

### ISSUE THREAD

**Issue by geordish** [ytti/oxidized#898]
Hi,

We are setting up a new oxidized instance on Ubuntu 16.04, and are running into the following error

```
undefined method `default' for nil:NilClass
/var/lib/gems/2.3.0/gems/oxidized-0.20.0/lib/oxidized/node.rb:152:in `resolve_output': undefined method `default' for nil:NilClass (NoMethodError)
	from /var/lib/gems/2.3.0/gems/oxidized-0.20.0/lib/oxidized/node.rb:21:in `initialize'
	from /var/lib/gems/2.3.0/gems/oxidized-0.20.0/lib/oxidized/nodes.rb:19:in `new'
	from /var/lib/gems/2.3.0/gems/oxidized-0.20.0/lib/oxidized/nodes.rb:19:in `block (2 levels) in load'
	from /var/lib/gems/2.3.0/gems/oxidized-0.20.0/lib/oxidized/nodes.rb:15:in `each'
	from /var/lib/gems/2.3.0/gems/oxidized-0.20.0/lib/oxidized/nodes.rb:15:in `block in load'
	from /var/lib/gems/2.3.0/gems/oxidized-0.20.0/lib/oxidized/nodes.rb:127:in `synchronize'
	from /var/lib/gems/2.3.0/gems/oxidized-0.20.0/lib/oxidized/nodes.rb:127:in `with_lock'
	from /var/lib/gems/2.3.0/gems/oxidized-0.20.0/lib/oxidized/nodes.rb:10:in `load'
	from /var/lib/gems/2.3.0/gems/oxidized-0.20.0/lib/oxidized/nodes.rb:122:in `initialize'
	from /var/lib/gems/2.3.0/gems/oxidized-0.20.0/lib/oxidized/core.rb:14:in `new'
	from /var/lib/gems/2.3.0/gems/oxidized-0.20.0/lib/oxidized/core.rb:14:in `initialize'
	from /var/lib/gems/2.3.0/gems/oxidized-0.20.0/lib/oxidized/core.rb:4:in `new'
	from /var/lib/gems/2.3.0/gems/oxidized-0.20.0/lib/oxidized/core.rb:4:in `new'
	from /var/lib/gems/2.3.0/gems/oxidized-0.20.0/lib/oxidized/cli.rb:12:in `run'
	from /var/lib/gems/2.3.0/gems/oxidized-0.20.0/bin/oxidized:9:in `<top (required)>'
	from /usr/local/bin/oxidized:23:in `load'
	from /usr/local/bin/oxidized:23:in `<main>'
```

Our config looks like so:
```yaml
---
username: user
password: pass
interval: 3600
use_syslog: false
debug: false
threads: 30
timeout: 20
retries: 3
log: /home/oxidized/.config/oxidized/log
prompt: !ruby/regexp /^([\w.@-]+[#>]\s?)$/
rest: 127.0.0.1:8888
next_adds_job: false
vars: {}
groups: {}
models: {}
pid: "/home/oxidized/.config/oxidized/pid"
input:
  default: ssh
  debug: false
  ssh:
    secure: false
output:
  default: git
  git:
    user: Oxidized
    email: o@example.com
    repo: "/var/lib/oxidized/devices.git"
source:
  default: csv
  csv:
    file: "/home/oxidized/.config/oxidized/router.db"
    delimiter: !ruby/regexp /:/
    map:
      name: 0
      model: 1
    gpg: false
model_map:
  cisco: ios
  juniper: junos
```

We've noticed that if we change the output to a local file output instead of git, it works.

List of installed gems:
```
*** LOCAL GEMS ***

asetus (0.3.0)
backports (3.8.0)
bigdecimal (1.2.8)
did_you_mean (1.0.0)
emk-sinatra-url-for (0.2.1)
haml (4.0.7)
htmlentities (4.3.4)
io-console (0.4.5)
json (1.8.3)
minitest (5.8.4)
multi_json (1.12.1)
net-ssh (3.0.2)
net-telnet (0.1.1)
oxidized (0.20.0)
oxidized-script (0.4.0)
oxidized-web (0.9.1)
power_assert (0.2.7)
psych (2.0.17)
puma (3.9.1)
rack (1.6.8)
rack-protection (1.5.3)
rack-test (0.6.3)
rake (10.5.0)
rdoc (4.2.1)
rugged (0.25.1.1)
sass (3.4.24)
sinatra (1.4.8)
sinatra-contrib (1.4.7)
slop (3.6.0)
test-unit (3.1.7)
tilt (2.0.7)
```
