### ISSUE TITLE
Issue with SSH Proxy and group set up

### ISSUE THREAD

**Issue by papatango71** [ytti/oxidized#904]
I have set up Oxidized and I am trying to get the SSH connections to proxy through another host that has been set up with SSH keys so authentication isn't an issue.  My groups config looks like:

```
groups:
  cisco:
    username: oxidized
    password: XXX
    vars:
      ssh_proxy_host: 10.104.197.194
  juniper:
    username: oxidized
    password: XXX
    vars:
      ssh_proxy_host: 10.104.197.194
  opengear:
    username: root
    password: XXX
    vars:
      ssh_proxy_host: 10.104.197.194
  fortios:
    username: oxidized
    password: XXX
    vars:
      ssh_proxy_host: 10.104.197.194
  acos:
    username: oxidized
    password: XXXX
    vars:
      ssh_proxy_host: 10.104.197.194
```

My input looks like:

```
input:
  default: ssh, telnet
  debug: true
  ssh:
    secure: false
  vars_map:
    ssh_proxy_host: 10.104.197.194
```

My source looks like:

```
source:
        default: http
        debug: false
        http:
          url: http://librenms.xxx.xxx.net/api/v0/oxidized
          map:
            name: hostname
            model: os
            group: group
          headers:
            X-Auth-Token: '60ab5b181aa2ecbb1888025ce641e131'
```

I am not seeing any of the SSH connections being proxied to 10.104.197.194.  Do I have the vars_map configured in the wrong area..??

Thank you.

-Patrick
