### ISSUE TITLE
Add support for Allied Telesis 

### ISSUE THREAD

**Issue by mattie47** [ytti/oxidized#929]
https://www.alliedtelesis.com/products/software/AlliedWare-Plus

I've written the following config which seems to work okay, but I'm not entirely sure if it's the correct way of doing it.

```
matt@matt-tb:/var/lib/gems/2.3.0/gems/oxidized-0.20.0/lib/oxidized/model$ cat awplus.rb
class Awplus < Oxidized::Model

  #Allied Telesis Alliedware Plus Model#

  prompt /^(\r?[\w.@:\/-]+[#>]\s?)$/
  comment  '! '

  #This shows the system information at the top and comments it out#
  cmd 'show system' do |cfg|
    comment cfg
  end

  #Actually get the devices running config#
  cmd 'show running-config' do |cfg|
    cfg
  end

  #Only configured for SSH. Needed to add 'enable' as Priv-Exec users don't get
  #put into "enable mode" by default on login.
  #Set term length to 0 so the entire config is output without intervention.
  #Finally, "terminal no length" is added to set the terminal length back to default.

  cfg :ssh do
    post_login 'enable'
    post_login 'terminal length 0'
    pre_logout 'terminal no length'
    pre_logout 'exit'
  end
```

As per the comments above:
- Run "show system" when the device first logs in. This is similar to Cisco's show inventory, but has some more detailed information as per the example below.
- Priv 15 does not automatically put the user in Priv-Exec mode. The user still needs to type "enable" once they've logged in
- I've added "terminal length 0" so the whole config file is output on the terminal
- On logging out, I've added "terminal no length" so the term length is globally set back to default.
- Added "exit" to actually exit the session. Without this, the session didn't end.

In terms of how the output file looks:

```
! show system
! System Status                                           Mon Jul 10 11:17:46 2017
! 
! Board      ID   Bay     Board Name                        Rev   Serial number
! --------------------------------------------------------------------------------
! Base       390          AT-x930-52GTX                     X3-0  A04878A143000039
! PSU        337  PSU1    PWR250                            A-0   A212DC01Y       
! --------------------------------------------------------------------------------
! RAM: Total: 1929732 kB Free: 1725132 kB
! Flash: 253.8MB Used: 113.3MB Available: 140.5MB
! --------------------------------------------------------------------------------
! Environment Status : Normal
! Uptime             : 0 days 00:31:01
! Bootloader version : 3.1.3
! 
! Current software   : x930-5.4.7-0.1.rel
! Software version   : 5.4.7-0.1
! Build date         : Fri Jul 7 22:33:21 UTC 2017
! 
! Current boot config: flash:/default.cfg (file exists)
! 
! System Name
!  Server-A
! System Contact
! 
! System Location
!  kochi 
! Server-A#show running-config
!
service password-encryption
!
hostname Server-A
!
no banner motd
!
....<rest of config>
```

Config file:

```
matt@matt-tb:~/.config/oxidized$ cat config
---
#This sets a global username and passwords for logging in and getting config
# manager/friend is the default login/pass
username: manager
password: friend

#This sets the default global product type.
model: alliedtelesis

.....


model_map:
  cisco: ios
  juniper: junos
  alliedtelesis: awplus

```

Thoughts?

Thanks,

Matt
