### ISSUE TITLE
SSH connection refused

### ISSUE THREAD

**Issue by victorehp17** [ytti/oxidized#955]
Hey guys so i have a couple of devices Powerconnect and Force10 dnos that are able to backup via telnet, but whenever i try to use SSH returns error:

    D, [2017-07-31T16:53:28.593363 #2875] DEBUG -- : 10.200.200.28 raised Errno::ECONNREFUSED with msg "Connection refused - connect(2)"

These are the settings i'm using:

``` yaml
source:
  default: csv
  csv:
    file: /home/oxidized/.config/oxidized/router.db
    delimiter: !ruby/regexp /:/
    map:
      name: 0
      model: 1
    vars_map:
      ssh_port: 8422
    gpg: false
model_map:
  cisco: ios
  juniper: junos
  dell: powerconnect
  fortigate: fortios
  force10: dnos
```

It seems as if oxidized is not trying port 8422, but 22 instead, or most probably, i'm not doing it correctly
