### ISSUE TITLE
Getting Encoding::UndefinedConversionError at /node/version/view oxidized 0.20.0

### ISSUE THREAD

**Issue by jh1990** [ytti/oxidized#966]
Hi,

I'm getting the error mentioned at trying to view the configs in version view.
My nodes are stored in a mysql db and I'm using git as output.

Here is my config:

``` yaml
interval: 3600
use_syslog: yes
debug: true
threads: 100
timeout: 200
retries: 3
prompt: !ruby/regexp /^([\w.@-]+[#>]\s?)$/
rest: 127.0.0.1:8888
next_adds_job: true
#vars: {}
#groups: {}
#models: {}
pid: "/home/oxidized/.config/oxidized/pid"

input:
  default: ssh, telnet
  debug: true
  ssh:
    secure: false

output:
  default: git
  git:
    user: Oxidized
    email: noc@localhost
    repo: "/srv/oxidized/repository/devices.git"

source:
  default: sql

  sql:

    adapter: mysql2
    database: oxidized
    user: oxidized
    password: xxxxxxxxxxxxxxx
    table: devices
    map:
      name: name
      ip: IP
      ssh_port: SSH_Port
      model: Device Type
      username: Username
      password: Password
      enable: enable
model_map:
  cisco: ios
  juniper: junos
  juniper: screenos
  fortigate: fortios
  checkpoint: gaiaos
```

Here is the trimmed output from journalctl

```
2017-08-10 15:33:53 - Encoding::UndefinedConversionError - "\xFC" from ASCII-8BIT to UTF-8:
/var/lib/gems/2.1.0/gems/htmlentities-4.3.4/lib/htmlentities/encoder.rb:25:in `encode'
/var/lib/gems/2.1.0/gems/htmlentities-4.3.4/lib/htmlentities/encoder.rb:25:in `prepare'
/var/lib/gems/2.1.0/gems/htmlentities-4.3.4/lib/htmlentities/encoder.rb:19:in `encode'
/var/lib/gems/2.1.0/gems/htmlentities-4.3.4/lib/htmlentities.rb:73:in `encode'
/var/lib/gems/2.1.0/gems/oxidized-web-0.9.2/lib/oxidized/web/webapp.rb:178:in `block in <class:WebApp>'
/var/lib/gems/2.1.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1611:in `call'
/var/lib/gems/2.1.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1611:in `block in compile!'
/var/lib/gems/2.1.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:975:in `[]'
/var/lib/gems/2.1.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:975:in `block (3 levels) in route!'
/var/lib/gems/2.1.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:994:in `route_eval'
/var/lib/gems/2.1.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:975:in `block (2 levels) in route!'
/var/lib/gems/2.1.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1015:in `block in process_route'
/var/lib/gems/2.1.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1013:in `catch'
/var/lib/gems/2.1.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1013:in `process_route'
/var/lib/gems/2.1.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:973:in `block in route!'
/var/lib/gems/2.1.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:972:in `each'
/var/lib/gems/2.1.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:972:in `route!'
/var/lib/gems/2.1.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1085:in `block in dispatch!'
/var/lib/gems/2.1.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `block in invoke'
/var/lib/gems/2.1.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `catch'
/var/lib/gems/2.1.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `invoke'
/var/lib/gems/2.1.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1082:in `dispatch!'
/var/lib/gems/2.1.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:907:in `block in call!'
/var/lib/gems/2.1.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `block in invoke'
/var/lib/gems/2.1.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `catch'
/var/lib/gems/2.1.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `invoke'
/var/lib/gems/2.1.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:907:in `call!'
/var/lib/gems/2.1.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:895:in `call'
/var/lib/gems/2.1.0/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb:18:in `call'
/var/lib/gems/2.1.0/gems/rack-protection-1.5.3/lib/rack/protection/path_traversal.rb:16:in `call'
/var/lib/gems/2.1.0/gems/rack-protection-1.5.3/lib/rack/protection/json_csrf.rb:18:in `call'
/var/lib/gems/2.1.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
/var/lib/gems/2.1.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
/var/lib/gems/2.1.0/gems/rack-protection-1.5.3/lib/rack/protection/frame_options.rb:31:in `call'
/var/lib/gems/2.1.0/gems/rack-1.6.8/lib/rack/nulllogger.rb:9:in `call'
/var/lib/gems/2.1.0/gems/rack-1.6.8/lib/rack/head.rb:13:in `call'
/var/lib/gems/2.1.0/gems/sinatra-1.4.8/lib/sinatra/show_exceptions.rb:25:in `call'
/var/lib/gems/2.1.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:182:in `call'
/var/lib/gems/2.1.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:2013:in `call'
/var/lib/gems/2.1.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1487:in `block in call'
/var/lib/gems/2.1.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1787:in `synchronize'
/var/lib/gems/2.1.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1487:in `call'
/var/lib/gems/2.1.0/gems/rack-1.6.8/lib/rack/urlmap.rb:66:in `block in call'
/var/lib/gems/2.1.0/gems/rack-1.6.8/lib/rack/urlmap.rb:50:in `each'
/var/lib/gems/2.1.0/gems/rack-1.6.8/lib/rack/urlmap.rb:50:in `call'
/var/lib/gems/2.1.0/gems/rack-1.6.8/lib/rack/builder.rb:153:in `call'
/var/lib/gems/2.1.0/gems/puma-3.8.2/lib/puma/configuration.rb:224:in `call'
/var/lib/gems/2.1.0/gems/puma-3.8.2/lib/puma/server.rb:600:in `handle_request'
/var/lib/gems/2.1.0/gems/puma-3.8.2/lib/puma/server.rb:435:in `process_client'
/var/lib/gems/2.1.0/gems/puma-3.8.2/lib/puma/server.rb:299:in `block in run'
/var/lib/gems/2.1.0/gems/puma-3.8.2/lib/puma/thread_pool.rb:120:in `call'
/var/lib/gems/2.1.0/gems/puma-3.8.2/lib/puma/thread_pool.rb:120:in `block in spawn_thread'
```

Is there any mistake in my config? Can you please help me?
