### ISSUE TITLE
oxidized crash when I change config from file to git

### ISSUE THREAD

**Issue by spial** [ytti/oxidized#975]
Hello there,

I am not from linux or programming field. I have recently installed oxidized and it was running flawless. But today I have changed the output from file to git and now I am getting the error. I would be happy if somebody can help me what could the issue:

the error I have seen after running the oxidized
Use Ctrl-C to stop

```
Invalid value; config files can only store string, bool or int keys
/usr/local/share/gems/gems/oxidized-0.20.0/lib/oxidized/output/git.rb:192:in `[]=': Invalid value; config files can only store string, bool or int keys (TypeError)
```
and  I have seen debug log:

    [user.err] oxidized[2714]: Oxidized crashed, crashfile written in /home/oxidized/.config/oxidized/crash.

only I understand that I have added username and email which I didn't had my last configuration.

``` yaml
output:
  default: file
  file:
    directory: /home/oxidized/.config/oxidized/deviceconfigs
```

and now the present one with git:

I would really appreciate if someone could shed some light on.

``` yaml
---
username: default
password: defpassword
model: cisco
interval: 28800
model: asa
interval: 3600
model: procurve
interval: 86400
model: aireos
interval: 86400
use_syslog: true
log: /home/oxidized/.config/oxidized/logs/
debug: true
threads: 30
timeout: 20
retries: 3
prompt: !ruby/regexp /^([\w.@-]+[#>]\s?)$/
rest: 127.0.0.1:8888
next_adds_job: false
vars: {}
groups: {}
models: {}
pid: /home/oxidized/.config/oxidized/pid
vars:
  enable: enpassword
input:
  default: ssh
  debug: true
  ssh:
    secure: false
output:
  default: git
  git:
    username: oxidized
    email: oxidized@quarzwerke.com
    repo: "/home/oxidized/.config/oxidized/deviceconfigs.git"
source:
  default: csv
  csv:
    file: /home/oxidized/.config/oxidized/router.db
    delimiter: !ruby/regexp /:/
    map:
      name: 0
      model: 1
      username: 2
      password: 3
    var_map:
      enable: 4
    gpg: false
model_map:
  router: ios
  asa: asa
  hp: procurve
  wlc: aireos
  nexus: nxos
```
