### ISSUE TITLE
slackdiff error occurs at oxidized startup

### ISSUE THREAD

**Issue by sls89** [ytti/oxidized#986]
Everytime I start oxidized, an error occurs: 

    Hook slack (#<SlackDiff:0x000000024531f0>) failed (#<TypeError: no implicit conversion of Symbol into Integer>) for event :stuck_out_tongue:ost_store

That's my config snippet:

``` yaml
hooks:
  slack:
    type: slackdiff
    events: [post_store]
    token: the-token
    channel: "#thechannel"
```

BOT is online and in the channel.
