### ISSUE TITLE
Issuing /node/next/... removes node

### ISSUE THREAD

**Issue by mrplow87** [ytti/oxidized#988]
I've come across that issuing `PUT /node/next/$nodename` through the RESTful API sometimes removes the node from the configuration of Oxidized and the API call returns "node not found".
When issuing `GET /node/reload`, the node gets re-added and further `/node/next/...` requests work without a hitch. Version history is kept intact after re-adding the node.

This was observed with Brocade (XMR, ICX and VDX models) and HP Procurve nodes.

The node source is MySQL, the versioning backend is a Gitlab EE. My work-around is to issue a `/node/reload` request, if a "node not found" error is encoutered. 

Anyone else notice this behaviour?

----

My config:

``` yaml
---
username: radiususer
password: radiuspass
use_syslog: false
log: /var/log/oxidized/log
interval: 0
debug: false
threads: 30
timeout: 120
retries: 2
prompt: !ruby/regexp /^([\w.@-]+[#>]\s?)$/
rest: 127.0.0.1:8888
next_adds_job: true
vars:
  ssh_no_exec: true
  remove_secret: true
groups: {}
models: {}
pid: /var/run/oxidized/pid
input:
  default: ssh
  debug: false
  ssh:
    secure: false
output:
  default: git
  git:
    user: 'Oxidized'
    email: 'network@domain.tld'
    repo: '/var/lib/oxidized/repository'
source:
  default: sql
  sql:
    adapter: mysql2
    database: 'oxidized'
    table: 'nodes'
    user: 'oxidized'
    password: 'dbpassword'
    host: '192.0.2.1'
    query: 'SELECT name,ipv4,model FROM nodes;'
    map:
      name: name
      ip: ipv4
      model: model
hooks:
  push_to_remote:
    type: githubrepo
    events: [post_store]
    remote_repo: https://gitlab
    username: gitlabusername
    password: gitlabpassword
```
